use common_enums::{BankHolderType, BankType};
use common_utils::{pii::Email, types::FloatMajorUnit};

use domain_types::{
    connector_types::{
        ClientAuthenticationTokenData, ClientAuthenticationTokenRequestData, EligibilityErrorInfo,
        GetPaymentMethodData, GetPaymentMethodResponseData, PMEligibility, PaymentFlowData,
        PaymentMethodEligibilityData, PaymentMethodEligibilityResponse, PaymentMethodTokenResponse,
        PaymentMethodTokenizationData, PaymentsResponseData, PlaidClientAuthenticationResponse,
    },
    errors::{ConnectorError, IntegrationError, IntegrationErrorContext},
    merchant_authentication_flow_data::MerchantAuthenticationFlowData,
    payment_method_data::{
        BankAccount, BankAccountAchDetails, BankAccountBacsDetails, BankAccountDetails,
        BankAccountRoutingDetails, BankAccountSepaDetails, PaymentMethodDataTypes,
        PaymentMethodDetails,
    },
    router_data::ConnectorSpecificConfig,
    router_data_v2::RouterDataV2,
};
use error_stack::report;
use hyperswitch_masking::{ExposeInterface, PeekInterface, Secret};
use serde::{Deserialize, Serialize};

use crate::types::ResponseRouterData;

// PlaidRouterData is generated by create_all_prerequisites! in the parent plaid.rs module
use super::PlaidRouterData;

const PLAID_SUBTYPE_CHECKING: &str = "checking";
const PLAID_SUBTYPE_SAVINGS: &str = "savings";
// =============================================================================
// AUTH TYPE
// =============================================================================

#[derive(Debug)]
pub struct PlaidAuthType {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub client_name: Option<String>,
}

impl TryFrom<&ConnectorSpecificConfig> for PlaidAuthType {
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(config: &ConnectorSpecificConfig) -> Result<Self, Self::Error> {
        match config {
            ConnectorSpecificConfig::Plaid {
                client_id,
                secret,
                client_name,
                ..
            } => Ok(Self {
                client_id: client_id.clone(),
                secret: secret.clone(),
                client_name: client_name.clone(),
            }),
            _ => Err(report!(IntegrationError::FailedToObtainAuthType {
                context: IntegrationErrorContext {
                    additional_context: Some("Expected ConnectorSpecificConfig::Plaid".to_owned()),
                    suggested_action: Some(
                        "Ensure the connector config provides Plaid client_id and secret"
                            .to_owned(),
                    ),
                    doc_url: Some("https://plaid.com/docs/api/".to_owned()),
                }
            })),
        }
    }
}

// =============================================================================
// FLOW 1: /link/token/create
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidLinkTokenRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub client_name: String,
    pub user: PlaidUser,
    pub products: Vec<String>,
    pub country_codes: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redirect_uri: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub android_package_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct PlaidUser {
    pub client_user_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<Secret<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_address: Option<Email>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<Secret<String>>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::ClientAuthenticationToken,
                MerchantAuthenticationFlowData,
                ClientAuthenticationTokenRequestData,
                PaymentsResponseData,
            >,
            T,
        >,
    > for PlaidLinkTokenRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::ClientAuthenticationToken,
                MerchantAuthenticationFlowData,
                ClientAuthenticationTokenRequestData,
                PaymentsResponseData,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;
        let req = &item.router_data.request;

        let client_name = auth.client_name.ok_or_else(|| {
            report!(IntegrationError::MissingRequiredField {
                field_name: "client_name",
                context: IntegrationErrorContext {
                    additional_context: Some(
                        "client_name must be set in the Plaid connector config".to_owned(),
                    ),
                    suggested_action: Some(
                        "Set client_name in the Plaid connector config".to_owned(),
                    ),
                    doc_url: Some(
                        "https://plaid.com/docs/api/tokens/#linktokencreate-client_name".to_owned(),
                    ),
                },
            })
        })?;

        let customer = req.customer.as_ref().ok_or_else(|| {
            report!(IntegrationError::MissingRequiredField {
                field_name: "customer",
                context: IntegrationErrorContext {
                    additional_context: Some(
                        "customer is required for Plaid Link token creation".to_owned()
                    ),
                    suggested_action: Some(
                        "Provide customer details including customer_id in the request".to_owned()
                    ),
                    doc_url: Some(
                        "https://plaid.com/docs/api/tokens/#linktokencreate-user".to_owned()
                    ),
                },
            })
        })?;

        let user = PlaidUser {
            client_user_id: customer.get_customer_id()?.get_string_repr().to_owned(),
            legal_name: customer.customer_name.clone(),
            email_address: customer.customer_email.clone(),
            phone_number: customer.customer_phone_number.clone(),
        };

        let country_codes = req
            .country_codes
            .iter()
            .map(|country_code| country_code.to_string())
            .collect::<Vec<_>>();

        if country_codes.is_empty() {
            return Err(report!(IntegrationError::MissingRequiredField {
                field_name: "country_codes",
                context: IntegrationErrorContext {
                    additional_context: Some(
                        "Plaid /link/token/create requires at least one country code".to_owned(),
                    ),
                    suggested_action: Some(
                        "Set country_codes in the Authenticator domain context, e.g. [\"US\"]"
                            .to_owned(),
                    ),
                    doc_url: Some(
                        "https://plaid.com/docs/api/tokens/#linktokencreate-country-codes"
                            .to_owned(),
                    ),
                },
            }));
        }

        // Plaid's Link token "return target": web/iOS merchants send a return
        // URL (-> redirect_uri), native-app merchants send a native app
        // identifier (-> android_package_name). We forward whatever was
        // provided without asserting mutual exclusivity.
        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            client_name,
            user,
            products: vec!["auth".to_owned()],
            country_codes,
            language: req.locale.clone(),
            redirect_uri: item.router_data.resource_common_data.return_url.clone(),
            android_package_name: req.native_app_identifier.clone(),
            webhook: req.webhook_url.clone(),
        })
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidLinkTokenResponse {
    pub link_token: Secret<String>,
    pub expiration: Option<String>,
    pub hosted_link_url: Option<String>,
    pub request_id: String,
}

impl TryFrom<ResponseRouterData<PlaidLinkTokenResponse, Self>>
    for RouterDataV2<
        domain_types::connector_flow::ClientAuthenticationToken,
        MerchantAuthenticationFlowData,
        ClientAuthenticationTokenRequestData,
        PaymentsResponseData,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(
        item: ResponseRouterData<PlaidLinkTokenResponse, Self>,
    ) -> Result<Self, Self::Error> {
        let res = item.response;

        let expires_in_seconds: Option<i64> = res.expiration.as_deref().and_then(|exp| {
            time::OffsetDateTime::parse(exp, &time::format_description::well_known::Rfc3339)
                .inspect_err(|e| {
                    tracing::debug!(
                        error = %e,
                        raw_expiration = %exp,
                        "Plaid link_token expiration is not RFC3339; expires_in_seconds will be omitted"
                    );
                })
                .ok()
                .and_then(|expiry_time| {
                    let secs = (expiry_time - common_utils::date_time::now().assume_utc()).whole_seconds();
                    if secs > 0 { Some(secs) } else { None }
                })
        });

        let plaid_auth_response = PlaidClientAuthenticationResponse {
            link_token: res.link_token,
            expires_in_seconds,
            hosted_link_url: res.hosted_link_url,
        };

        let session_data = ClientAuthenticationTokenData::Plaid(Box::new(plaid_auth_response));

        Ok(Self {
            response: Ok(PaymentsResponseData::ClientAuthenticationTokenResponse {
                session_data,
                status_code: item.http_code,
            }),
            ..item.router_data
        })
    }
}

// =============================================================================
// FLOW 2: /item/public_token/exchange
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidPublicTokenExchangeRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub public_token: Secret<String>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodToken,
                PaymentFlowData,
                PaymentMethodTokenizationData<T>,
                PaymentMethodTokenResponse,
            >,
            T,
        >,
    > for PlaidPublicTokenExchangeRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodToken,
                PaymentFlowData,
                PaymentMethodTokenizationData<T>,
                PaymentMethodTokenResponse,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;

        let public_token = item
            .router_data
            .request
            .metadata
            .as_ref()
            .and_then(|metadata_str| {
                serde_json::from_str::<serde_json::Value>(metadata_str.peek()).ok()
            })
            .and_then(|metadata_json| {
                metadata_json
                    .get("public_token")
                    .and_then(|val| val.as_str())
                    .map(|s| Secret::new(s.to_owned()))
            })
            .ok_or_else(|| {
                report!(IntegrationError::MissingRequiredField {
                    field_name: "metadata.public_token",
                    context: IntegrationErrorContext {
                        additional_context: Some(
                            "metadata must be a JSON object containing a \"public_token\" field"
                                .to_owned(),
                        ),
                        suggested_action: Some(
                            "Pass metadata as JSON: {\"public_token\": \"<token from Plaid Link\"}"
                                .to_owned(),
                        ),
                        doc_url: Some(
                            "https://plaid.com/docs/api/items/#itempublic_tokenexchange".to_owned(),
                        ),
                    },
                })
            })?;

        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            public_token,
        })
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidPublicTokenExchangeResponse {
    pub access_token: Secret<String>,
    pub item_id: String,
    pub request_id: String,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static>
    TryFrom<ResponseRouterData<PlaidPublicTokenExchangeResponse, Self>>
    for RouterDataV2<
        domain_types::connector_flow::PaymentMethodToken,
        PaymentFlowData,
        PaymentMethodTokenizationData<T>,
        PaymentMethodTokenResponse,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(
        item: ResponseRouterData<PlaidPublicTokenExchangeResponse, Self>,
    ) -> Result<Self, Self::Error> {
        let res = item.response;
        Ok(Self {
            response: Ok(PaymentMethodTokenResponse {
                token: res.access_token.expose(),
                connector_payment_method_id: Some(res.item_id),
                status_code: item.http_code,
            }),
            ..item.router_data
        })
    }
}

// =============================================================================
// FLOW 3: /auth/get
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidAuthGetRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub access_token: Secret<String>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::GetPaymentMethod,
                PaymentFlowData,
                GetPaymentMethodData,
                GetPaymentMethodResponseData,
            >,
            T,
        >,
    > for PlaidAuthGetRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::GetPaymentMethod,
                PaymentFlowData,
                GetPaymentMethodData,
                GetPaymentMethodResponseData,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;

        let access_token = item
            .router_data
            .request
            .payment_method_token
            .ok_or_else(|| {
                report!(IntegrationError::MissingRequiredField {
                    field_name: "payment_method_token (access_token)",
                    context: IntegrationErrorContext {
                        additional_context: Some(
                            "Plaid /auth/get requires the access_token as payment_method_token"
                                .to_owned(),
                        ),
                        suggested_action: Some(
                            "Pass the Plaid access_token (obtained from token exchange) as payment_method_token"
                                .to_owned(),
                        ),
                        doc_url: Some(
                            "https://plaid.com/docs/api/products/auth/#authget".to_owned(),
                        ),
                    },
                })
            })?;

        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            access_token,
        })
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidAuthGetResponse {
    pub accounts: Vec<PlaidAccount>,
    pub numbers: PlaidNumbers,
    pub item: PlaidItem,
    pub request_id: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PlaidItem {
    pub item_id: String,
    pub institution_name: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PlaidHolderCategory {
    Personal,
    Business,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PlaidAccount {
    pub account_id: Secret<String>,
    pub name: Secret<String>,
    pub subtype: Option<String>,
    pub holder_category: Option<PlaidHolderCategory>,
    #[serde(default)]
    pub mask: Option<Secret<String>>,
    #[serde(default)]
    pub official_name: Option<Secret<String>>,
    #[serde(rename = "type")]
    #[serde(default)]
    pub account_type: Option<String>,
    pub balances: PlaidBalances,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PlaidBalances {
    #[serde(default)]
    pub current: Option<FloatMajorUnit>,
    #[serde(default)]
    pub available: Option<FloatMajorUnit>,
    #[serde(default)]
    pub limit: Option<FloatMajorUnit>,
    #[serde(default)]
    pub iso_currency_code: Option<common_enums::Currency>,
    #[serde(default)]
    pub unofficial_currency_code: Option<String>,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(default)]
pub struct PlaidNumbers {
    pub ach: Vec<PlaidAchNumbers>,
    pub eft: Vec<PlaidEftNumbers>,
    pub bacs: Vec<PlaidBacsNumbers>,
    pub international: Vec<PlaidInternationalNumbers>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidAchNumbers {
    pub account_id: Secret<String>,
    pub account: Secret<String>,
    pub routing: Secret<String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidEftNumbers {
    pub account_id: Secret<String>,
    pub account: Secret<String>,
    pub routing: Secret<String>,
    pub institution: Secret<String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidBacsNumbers {
    pub account_id: Secret<String>,
    pub account: Secret<String>,
    pub sort_code: Secret<String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidInternationalNumbers {
    pub account_id: Secret<String>,
    pub iban: Secret<String>,
    pub bic: Option<Secret<String>>,
}

impl TryFrom<ResponseRouterData<PlaidAuthGetResponse, Self>>
    for RouterDataV2<
        domain_types::connector_flow::GetPaymentMethod,
        PaymentFlowData,
        GetPaymentMethodData,
        GetPaymentMethodResponseData,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(item: ResponseRouterData<PlaidAuthGetResponse, Self>) -> Result<Self, Self::Error> {
        let res = item.response;
        let request_currency = item.router_data.resource_common_data.get_currency();

        let institution_name = res.item.institution_name.clone();
        let (numbers, accounts_info) = (res.numbers, res.accounts);
        // The domain BankAccount captures identity (id/name), typology and
        // balances; routing details are attached per number-kind below.
        let id_to_account: std::collections::HashMap<String, BankAccount> = accounts_info
            .iter()
            .map(|acct| {
                (
                    acct.account_id.peek().to_owned(),
                    plaid_account_to_bank_account(acct, request_currency, institution_name.clone()),
                )
            })
            .collect();

        let mut accounts: Vec<BankAccount> = Vec::new();

        numbers.ach.into_iter().for_each(|ach| {
            if let Some(account) = id_to_account.get(ach.account_id.peek()) {
                accounts.push(BankAccount {
                    account_details: Some(BankAccountRoutingDetails::Ach(BankAccountAchDetails {
                        account_number: ach.account,
                        routing_number: ach.routing,
                    })),
                    ..account.clone()
                });
            }
        });

        numbers.bacs.into_iter().for_each(|bacs| {
            if let Some(account) = id_to_account.get(bacs.account_id.peek()) {
                accounts.push(BankAccount {
                    account_details: Some(BankAccountRoutingDetails::Bacs(
                        BankAccountBacsDetails {
                            account_number: bacs.account,
                            sort_code: bacs.sort_code,
                        },
                    )),
                    ..account.clone()
                });
            }
        });

        numbers.international.into_iter().for_each(|sepa| {
            if let Some(account) = id_to_account.get(sepa.account_id.peek()) {
                accounts.push(BankAccount {
                    account_details: Some(BankAccountRoutingDetails::Sepa(
                        BankAccountSepaDetails {
                            iban: sepa.iban,
                            bic: sepa.bic,
                        },
                    )),
                    ..account.clone()
                });
            }
        });

        Ok(Self {
            response: Ok(GetPaymentMethodResponseData {
                merchant_payment_method_id: None,
                connector_payment_method_id: Some(res.item.item_id),
                customer: None,
                payment_method_details: Some(PaymentMethodDetails::BankAccount(
                    BankAccountDetails { accounts },
                )),
                status_code: item.http_code,
            }),
            ..item.router_data
        })
    }
}

/// Map Plaid account subtype strings to the domain `BankType` enum.
fn plaid_subtype_to_bank_type(subtype: &str) -> Option<BankType> {
    match subtype {
        PLAID_SUBTYPE_CHECKING => Some(BankType::Checking),
        PLAID_SUBTYPE_SAVINGS => Some(BankType::Savings),
        _ => None,
    }
}

/// Map a Plaid account (no routing numbers) to the domain `BankAccount`.
///
/// Conversion failures for balance amounts degrade to `None` (both `current`
/// and `available` are nullable on the wire) rather than failing the whole
/// flow.
fn plaid_account_to_bank_account(
    acct: &PlaidAccount,
    request_currency: Option<common_enums::Currency>,
    institution_name: Option<String>,
) -> BankAccount {
    let currency = acct.balances.iso_currency_code.or(request_currency);
    let convert = |amount: Option<FloatMajorUnit>| {
        amount.zip(currency).and_then(|(amt, c)| {
            super::PlaidAmountConvertor::convert_back(amt, c)
                .ok()
                .map(|amount| common_utils::types::Money {
                    amount,
                    currency: c,
                })
        })
    };
    BankAccount {
        account_id: acct.account_id.clone(),
        account_name: acct.name.clone(),
        bank_type: acct.subtype.as_deref().and_then(plaid_subtype_to_bank_type),
        bank_holder_type: acct.holder_category.as_ref().map(|hc| match hc {
            PlaidHolderCategory::Personal => BankHolderType::Personal,
            PlaidHolderCategory::Business => BankHolderType::Business,
        }),
        balance: convert(acct.balances.current),
        available_balance: convert(acct.balances.available),
        account_details: None,
        bank_name: institution_name,
    }
}

// =============================================================================
// FLOW 4: /accounts/balance/get (PaymentMethodEligibility)
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidBalanceGetRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub access_token: Secret<String>,
    /// Account filter. `PaymentMethodEligibilityData.connector_payment_method_id`
    /// is the Plaid account_id, so a set value narrows the balance lookup to
    /// that single account; when absent the whole item's accounts are returned.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<PlaidBalanceGetRequestOptions>,
}

#[derive(Debug, Serialize)]
pub struct PlaidBalanceGetRequestOptions {
    pub account_ids: Vec<String>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodEligibility,
                PaymentFlowData,
                PaymentMethodEligibilityData,
                PaymentMethodEligibilityResponse,
            >,
            T,
        >,
    > for PlaidBalanceGetRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodEligibility,
                PaymentFlowData,
                PaymentMethodEligibilityData,
                PaymentMethodEligibilityResponse,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;

        // Plaid maps: access_token ← payment_method_token, account_ids ←
        // connector_payment_method_id.
        let access_token = item
            .router_data
            .request
            .payment_method_token
            .ok_or_else(|| {
                report!(IntegrationError::MissingRequiredField {
                    field_name: "payment_method_token (access_token)",
                    context: IntegrationErrorContext {
                        additional_context: Some(
                            "Plaid /accounts/balance/get requires the access_token as payment_method_token"
                                .to_owned(),
                        ),
                        suggested_action: Some(
                            "Pass the Plaid access_token (obtained from token exchange) as payment_method_token"
                                .to_owned(),
                        ),
                        doc_url: Some(
                            "https://plaid.com/docs/api/products/balance/#accountsbalanceget"
                                .to_owned(),
                        ),
                    },
                })
            })?;

        // connector_payment_method_id carries the Plaid account_id: scope the
        // balance lookup to that account when present, else return all of the
        // item's accounts.
        let options = item
            .router_data
            .request
            .connector_payment_method_id
            .map(|account_id| PlaidBalanceGetRequestOptions {
                account_ids: vec![account_id],
            });

        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            access_token: Secret::new(access_token),
            options,
        })
    }
}

/// `/accounts/balance/get` returns `AccountsGetResponse`: the same account
/// array as `/auth/get`, but no `numbers` (no routing data) — eligibility
/// results therefore carry balances only (via `payment_method_details`).
#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidBalanceGetResponse {
    pub accounts: Vec<PlaidAccount>,
    pub item: PlaidItem,
    pub request_id: String,
}

impl TryFrom<ResponseRouterData<PlaidBalanceGetResponse, Self>>
    for RouterDataV2<
        domain_types::connector_flow::PaymentMethodEligibility,
        PaymentFlowData,
        PaymentMethodEligibilityData,
        PaymentMethodEligibilityResponse,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(
        item: ResponseRouterData<PlaidBalanceGetResponse, Self>,
    ) -> Result<Self, Self::Error> {
        let mut data = item.router_data;
        let res = &item.response;
        data.resource_common_data.raw_connector_response =
            serde_json::to_string(res).ok().map(Secret::new);

        let request_currency = Some(data.request.amount.currency);
        let institution_name = res.item.institution_name.clone();

        // Plaid signals failure via HTTP status (the connector error path);
        // a 200 with zero accounts means the item resolved but exposes no
        // accounts — Ineligible, with the reason in error_info. When accounts
        // exist, eligibility is gated on a balance check: at least one account
        // must cover the request amount. The spendable figure is `available`,
        // falling back to `current` when `available` is null (e.g. some
        // depository accounts only report `current`). Derive the verdict from
        // the payload, never from a constant.
        let (eligibility, error_info) = if res.accounts.is_empty() {
            (
                common_enums::EligibilityStatus::Ineligible,
                Some(EligibilityErrorInfo {
                    code: "NO_ACCOUNTS".to_owned(),
                    message: "No accounts returned for access token".to_owned(),
                    reason: None,
                }),
            )
        } else {
            let request_amount = data.request.amount.amount;
            let currency = data.request.amount.currency;

            // An account covers the request when its comparable balance
            // (available, else current) converts to more than the request
            // amount; equality is not sufficient for this eligibility check.
            // A null/unparseable balance cannot verify sufficiency, so it is not eligible.
            let covers = |acct: &PlaidAccount| {
                let comparable = acct.balances.available.or(acct.balances.current);
                comparable
                    .and_then(|bal| super::PlaidAmountConvertor::convert_back(bal, currency).ok())
                    .is_some_and(|balance_minor| balance_minor > request_amount)
            };

            // When the request pins a specific account (connector_payment_method_id
            // carries the Plaid account_id), the verdict is that account alone;
            // otherwise any account covering the amount suffices.
            let sufficient = match &data.request.connector_payment_method_id {
                Some(account_id) => res
                    .accounts
                    .iter()
                    .find(|acct| acct.account_id.peek() == account_id)
                    .map(|acct| (covers(acct), true))
                    .unwrap_or((false, false)),
                None => (res.accounts.iter().any(covers), true),
            };

            match sufficient {
                (true, _) => (common_enums::EligibilityStatus::Eligible, None),
                (false, true) => (
                    common_enums::EligibilityStatus::Ineligible,
                    Some(EligibilityErrorInfo {
                        code: "INSUFFICIENT_BALANCE".to_owned(),
                        message: "Account balance is below the request amount".to_owned(),
                        reason: None,
                    }),
                ),
                (false, false) => (
                    common_enums::EligibilityStatus::Ineligible,
                    Some(EligibilityErrorInfo {
                        code: "ACCOUNT_NOT_FOUND".to_owned(),
                        message: "Requested account_id not present for this access token"
                            .to_owned(),
                        reason: None,
                    }),
                ),
            }
        };

        // Balance details are surfaced regardless of verdict — an ineligible
        // result still tells the caller what the accounts hold.
        let payment_method_details = if res.accounts.is_empty() {
            None
        } else {
            Some(PaymentMethodDetails::BankAccount(BankAccountDetails {
                accounts: res
                    .accounts
                    .iter()
                    .map(|acct| {
                        plaid_account_to_bank_account(
                            acct,
                            request_currency,
                            institution_name.clone(),
                        )
                    })
                    .collect(),
            }))
        };

        // One verdict per requested payment method — the balance endpoint is
        // PM-agnostic, so the same result fans out (mirrors Qwikcilver).
        let results = data
            .request
            .payment_method_types
            .iter()
            .map(|payment_method_type| PMEligibility {
                payment_method_type: *payment_method_type,
                eligibility,
                error_info: error_info.clone(),
                payment_method_details: payment_method_details.clone(),
            })
            .collect();

        data.response = Ok(PaymentMethodEligibilityResponse {
            results,
            status_code: u32::from(item.http_code),
        });
        Ok(data)
    }
}

// =============================================================================
// ERROR RESPONSE
// =============================================================================

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidErrorResponse {
    pub error_type: Option<String>,
    pub error_code: Option<String>,
    pub error_message: Option<String>,
    pub display_message: Option<String>,
    pub request_id: Option<String>,
}

impl common_utils::errors::ErrorSwitch<ConnectorError> for PlaidErrorResponse {
    fn switch(&self) -> ConnectorError {
        ConnectorError::ResponseHandlingFailed {
            context: domain_types::errors::ResponseTransformationErrorContext {
                http_status_code: None,
                additional_context: self.error_message.clone(),
            },
        }
    }
}
