use common_enums::BankType;
use domain_types::{
    connector_types::{
        ClientAuthenticationTokenData, ClientAuthenticationTokenRequestData, GetPaymentMethodData,
        GetPaymentMethodResponseData, PaymentFlowData, PaymentMethodTokenResponse,
        PaymentMethodTokenizationData, PaymentsResponseData, PlaidClientAuthenticationResponse,
    },
    errors::{ConnectorError, IntegrationError, IntegrationErrorContext},
    merchant_authentication_flow_data::MerchantAuthenticationFlowData,
    payment_method_data::{
        BankAccount, BankAccountAchDetails, BankAccountBacsDetails, BankAccountDetails,
        BankAccountRoutingDetails, BankAccountSepaDetails, PaymentMethodDataTypes,
        PaymentMethodDetails,
    },
    router_data::ConnectorSpecificConfig,
    router_data_v2::RouterDataV2,
};
use error_stack::report;
use hyperswitch_masking::{ExposeInterface, PeekInterface, Secret};
use serde::{Deserialize, Serialize};

use crate::types::ResponseRouterData;

// PlaidRouterData is generated by create_all_prerequisites! in the parent plaid.rs module
use super::PlaidRouterData;

// =============================================================================
// AUTH TYPE
// =============================================================================

pub struct PlaidAuthType {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
}

impl TryFrom<&ConnectorSpecificConfig> for PlaidAuthType {
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(config: &ConnectorSpecificConfig) -> Result<Self, Self::Error> {
        match config {
            ConnectorSpecificConfig::Plaid {
                client_id, secret, ..
            } => Ok(Self {
                client_id: client_id.clone(),
                secret: secret.clone(),
            }),
            _ => Err(report!(IntegrationError::FailedToObtainAuthType {
                context: IntegrationErrorContext {
                    additional_context: Some("Expected ConnectorSpecificConfig::Plaid".to_owned(),),
                    ..Default::default()
                }
            })),
        }
    }
}

// =============================================================================
// FLOW 1: /link/token/create
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidLinkTokenRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub client_name: String,
    pub user: PlaidUser,
    pub products: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub country_codes: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redirect_uri: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct PlaidUser {
    pub client_user_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::ClientAuthenticationToken,
                MerchantAuthenticationFlowData,
                ClientAuthenticationTokenRequestData,
                PaymentsResponseData,
            >,
            T,
        >,
    > for PlaidLinkTokenRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::ClientAuthenticationToken,
                MerchantAuthenticationFlowData,
                ClientAuthenticationTokenRequestData,
                PaymentsResponseData,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;
        let req = &item.router_data.request;

        // client_name comes from connector_feature_data["client_name"] or a default
        let client_name = item
            .router_data
            .resource_common_data
            .connector_feature_data
            .as_ref()
            .and_then(|v| {
                v.peek()
                    .as_object()
                    .and_then(|o| o.get("client_name"))
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_owned())
            })
            .unwrap_or_else(|| "Hyperswitch".to_owned());

        let user = PlaidUser {
            client_user_id: req
                .customer_id
                .as_ref()
                .map(|id| id.get_string_repr().to_owned())
                .unwrap_or_else(|| {
                    item.router_data
                        .resource_common_data
                        .connector_request_reference_id
                        .clone()
                }),
            legal_name: req.customer_name.as_ref().map(|n| n.peek().to_owned()),
            email_address: req.email.as_ref().map(|e| e.peek().to_owned()),
            phone_number: None,
        };

        let country_codes = req
            .country_codes
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>();

        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            client_name,
            user,
            products: vec!["auth".to_owned()],
            country_codes,
            language: req.locale.clone(),
            redirect_uri: item.router_data.resource_common_data.return_url.clone(),
            webhook: req.webhook_url.clone(),
        })
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidLinkTokenResponse {
    pub link_token: Secret<String>,
    pub expiration: Option<String>,
    pub hosted_link_url: Option<String>,
    pub request_id: String,
}

impl
    TryFrom<
        ResponseRouterData<
            PlaidLinkTokenResponse,
            RouterDataV2<
                domain_types::connector_flow::ClientAuthenticationToken,
                MerchantAuthenticationFlowData,
                ClientAuthenticationTokenRequestData,
                PaymentsResponseData,
            >,
        >,
    >
    for RouterDataV2<
        domain_types::connector_flow::ClientAuthenticationToken,
        MerchantAuthenticationFlowData,
        ClientAuthenticationTokenRequestData,
        PaymentsResponseData,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(
        item: ResponseRouterData<
            PlaidLinkTokenResponse,
            Self,
        >,
    ) -> Result<Self, Self::Error> {
        let res = item.response;

        let expires_in_seconds: Option<i64> = res.expiration.as_deref().and_then(|exp| {
            time::OffsetDateTime::parse(exp, &time::format_description::well_known::Rfc3339)
                .ok()
                .map(|expiry_time| {
                    let now = time::OffsetDateTime::now_utc();
                    (expiry_time - now).whole_seconds()
                })
        });

        let plaid_auth_response = PlaidClientAuthenticationResponse {
            link_token: res.link_token,
            expires_in_seconds,
            hosted_link_url: res.hosted_link_url,
        };

        let session_data = ClientAuthenticationTokenData::Plaid(Box::new(plaid_auth_response));

        Ok(Self {
            response: Ok(PaymentsResponseData::ClientAuthenticationTokenResponse {
                session_data,
                status_code: item.http_code,
            }),
            ..item.router_data
        })
    }
}

// =============================================================================
// FLOW 2: /item/public_token/exchange
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidPublicTokenExchangeRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub public_token: Secret<String>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodToken,
                PaymentFlowData,
                PaymentMethodTokenizationData<T>,
                PaymentMethodTokenResponse,
            >,
            T,
        >,
    > for PlaidPublicTokenExchangeRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodToken,
                PaymentFlowData,
                PaymentMethodTokenizationData<T>,
                PaymentMethodTokenResponse,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;

        let public_token = item.router_data.request.metadata.ok_or_else(|| {
            report!(IntegrationError::MissingRequiredField {
                field_name: "metadata (public_token)",
                context: IntegrationErrorContext {
                    additional_context: Some(
                        "Plaid token exchange requires the public_token in the metadata field"
                            .to_owned(),
                    ),
                    ..Default::default()
                },
            })
        })?;

        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            public_token,
        })
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidPublicTokenExchangeResponse {
    pub access_token: Secret<String>,
    pub item_id: String,
    pub request_id: String,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static>
    TryFrom<
        ResponseRouterData<
            PlaidPublicTokenExchangeResponse,
            RouterDataV2<
                domain_types::connector_flow::PaymentMethodToken,
                PaymentFlowData,
                PaymentMethodTokenizationData<T>,
                PaymentMethodTokenResponse,
            >,
        >,
    >
    for RouterDataV2<
        domain_types::connector_flow::PaymentMethodToken,
        PaymentFlowData,
        PaymentMethodTokenizationData<T>,
        PaymentMethodTokenResponse,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(
        item: ResponseRouterData<
            PlaidPublicTokenExchangeResponse,
            Self,
        >,
    ) -> Result<Self, Self::Error> {
        let res = item.response;
        Ok(Self {
            response: Ok(PaymentMethodTokenResponse {
                token: res.access_token.expose(),
                connector_payment_method_id: Some(res.item_id),
            }),
            ..item.router_data
        })
    }
}

// =============================================================================
// FLOW 3: /auth/get
// =============================================================================

#[derive(Debug, Serialize)]
pub struct PlaidAuthGetRequest {
    pub client_id: Secret<String>,
    pub secret: Secret<String>,
    pub access_token: Secret<String>,
}

impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
    TryFrom<
        PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::GetPaymentMethod,
                PaymentFlowData,
                GetPaymentMethodData,
                GetPaymentMethodResponseData,
            >,
            T,
        >,
    > for PlaidAuthGetRequest
{
    type Error = error_stack::Report<IntegrationError>;

    fn try_from(
        item: PlaidRouterData<
            RouterDataV2<
                domain_types::connector_flow::GetPaymentMethod,
                PaymentFlowData,
                GetPaymentMethodData,
                GetPaymentMethodResponseData,
            >,
            T,
        >,
    ) -> Result<Self, Self::Error> {
        let auth = PlaidAuthType::try_from(&item.router_data.connector_config)?;

        let access_token = item
            .router_data
            .request
            .payment_method_token
            .ok_or_else(|| {
                report!(IntegrationError::MissingRequiredField {
                    field_name: "payment_method_token (access_token)",
                    context: IntegrationErrorContext {
                        additional_context: Some(
                            "Plaid /auth/get requires the access_token as payment_method_token"
                                .to_owned(),
                        ),
                        ..Default::default()
                    },
                })
            })?;

        Ok(Self {
            client_id: auth.client_id,
            secret: auth.secret,
            access_token,
        })
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidAuthGetResponse {
    pub accounts: Vec<PlaidAccount>,
    pub numbers: PlaidNumbers,
    pub request_id: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidAccount {
    pub account_id: String,
    pub name: String,
    pub subtype: Option<String>,
    pub balances: PlaidBalances,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidBalances {
    pub current: Option<f64>,
    pub available: Option<f64>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidNumbers {
    #[serde(default)]
    pub ach: Vec<PlaidAchNumbers>,
    #[serde(default)]
    pub bacs: Vec<PlaidBacsNumbers>,
    #[serde(default)]
    pub international: Vec<PlaidSepaNumbers>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidAchNumbers {
    pub account_id: String,
    pub account: Secret<String>,
    pub routing: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidBacsNumbers {
    pub account_id: String,
    pub account: Secret<String>,
    pub sort_code: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidSepaNumbers {
    pub account_id: String,
    pub iban: Secret<String>,
    pub bic: Option<Secret<String>>,
}

impl
    TryFrom<
        ResponseRouterData<
            PlaidAuthGetResponse,
            RouterDataV2<
                domain_types::connector_flow::GetPaymentMethod,
                PaymentFlowData,
                GetPaymentMethodData,
                GetPaymentMethodResponseData,
            >,
        >,
    >
    for RouterDataV2<
        domain_types::connector_flow::GetPaymentMethod,
        PaymentFlowData,
        GetPaymentMethodData,
        GetPaymentMethodResponseData,
    >
{
    type Error = error_stack::Report<ConnectorError>;

    fn try_from(
        item: ResponseRouterData<
            PlaidAuthGetResponse,
            Self,
        >,
    ) -> Result<Self, Self::Error> {
        let res = item.response;

        // Build lookup maps from account_id → routing details
        let ach_map: std::collections::HashMap<_, _> = res
            .numbers
            .ach
            .into_iter()
            .map(|n| (n.account_id.clone(), n))
            .collect();
        let bacs_map: std::collections::HashMap<_, _> = res
            .numbers
            .bacs
            .into_iter()
            .map(|n| (n.account_id.clone(), n))
            .collect();
        let sepa_map: std::collections::HashMap<_, _> = res
            .numbers
            .international
            .into_iter()
            .map(|n| (n.account_id.clone(), n))
            .collect();

        let accounts: Vec<BankAccount> = res
            .accounts
            .into_iter()
            .map(|acct| {
                let bank_type = acct.subtype.as_deref().and_then(plaid_subtype_to_bank_type);

                let balance = acct.balances.current.map(|amt| common_utils::types::Money {
                    amount: common_utils::types::MinorUnit::new(
                        f64::round(amt * 100.0) as i64,
                    ),
                    currency: common_enums::Currency::USD,
                });
                let available_balance =
                    acct.balances
                        .available
                        .map(|amt| common_utils::types::Money {
                            amount: common_utils::types::MinorUnit::new(
                                f64::round(amt * 100.0) as i64,
                            ),
                            currency: common_enums::Currency::USD,
                        });

                // Prefer ACH → BACS → SEPA in that order
                let account_details = if let Some(ach) = ach_map.get(&acct.account_id) {
                    Some(BankAccountRoutingDetails::Ach(BankAccountAchDetails {
                        account_number: ach.account.clone(),
                        routing_number: Secret::new(ach.routing.clone()),
                    }))
                } else if let Some(bacs) = bacs_map.get(&acct.account_id) {
                    Some(BankAccountRoutingDetails::Bacs(BankAccountBacsDetails {
                        account_number: bacs.account.clone(),
                        sort_code: Secret::new(bacs.sort_code.clone()),
                    }))
                } else {
                    sepa_map.get(&acct.account_id).map(|sepa| {
                        BankAccountRoutingDetails::Sepa(BankAccountSepaDetails {
                            iban: sepa.iban.clone(),
                            bic: sepa.bic.clone(),
                        })
                    })
                };

                BankAccount {
                    account_name: acct.name,
                    account_id: Secret::new(acct.account_id),
                    bank_type,
                    bank_holder_type: None,
                    balance,
                    available_balance,
                    account_details,
                }
            })
            .collect();

        Ok(Self {
            response: Ok(GetPaymentMethodResponseData {
                merchant_payment_method_id: None,
                connector_payment_method_id: None,
                customer: None,
                payment_method_details: Some(PaymentMethodDetails::BankAccount(
                    BankAccountDetails { accounts },
                )),
                status_code: item.http_code,
            }),
            ..item.router_data
        })
    }
}

/// Map Plaid account subtype strings to the domain `BankType` enum.
fn plaid_subtype_to_bank_type(subtype: &str) -> Option<BankType> {
    match subtype {
        "checking" => Some(BankType::Checking),
        "savings" => Some(BankType::Savings),
        _ => None,
    }
}

// =============================================================================
// ERROR RESPONSE
// =============================================================================

#[derive(Debug, Deserialize, Serialize)]
pub struct PlaidErrorResponse {
    pub error_type: Option<String>,
    pub error_code: Option<String>,
    pub error_message: Option<String>,
    pub display_message: Option<String>,
    pub request_id: Option<String>,
}

impl common_utils::errors::ErrorSwitch<ConnectorError> for PlaidErrorResponse {
    fn switch(&self) -> ConnectorError {
        ConnectorError::ResponseHandlingFailed {
            context: domain_types::errors::ResponseTransformationErrorContext {
                http_status_code: None,
                additional_context: self.error_message.clone(),
            },
        }
    }
}
