pub mod transformers;

use std::fmt::Debug;

use common_enums::CurrencyUnit;
use common_utils::{
    errors::CustomResult, events, ext_traits::ByteSliceExt, types::StringMajorUnit,
};
use domain_types::{
    connector_flow::{
        Authorize, Capture, CreateConnectorCustomer, CreateOrder, PSync, PostAuthenticate,
        PreAuthenticate, RSync, Refund, RepeatPayment, ServerAuthenticationToken, SetupMandate,
        Void,
    },
    connector_types::{
        ConnectorCustomerData, ConnectorCustomerResponse, PaymentCreateOrderData,
        PaymentCreateOrderResponse, PaymentFlowData, PaymentVoidData, PaymentsAuthorizeData,
        PaymentsCaptureData, PaymentsPostAuthenticateData, PaymentsPreAuthenticateData,
        PaymentsResponseData, PaymentsSyncData, RefundFlowData, RefundSyncData, RefundsData,
        RefundsResponseData, RepeatPaymentData, ResponseId, ServerAuthenticationTokenRequestData,
        ServerAuthenticationTokenResponseData, SetupMandateRequestData,
    },
    merchant_authentication_flow_data::MerchantAuthenticationFlowData,
    payment_method_data::PaymentMethodDataTypes,
    router_data::{ConnectorSpecificConfig, ErrorResponse},
    router_data_v2::RouterDataV2,
    router_response_types::Response,
    types::Connectors,
};
use error_stack::ResultExt;
use hyperswitch_masking::{ExposeInterface, Maskable, PeekInterface};
use interfaces::{
    api::ConnectorCommon, connector_integration_v2::ConnectorIntegrationV2, connector_types,
    decode::BodyDecoding, verification::SourceVerification,
};
use serde::Serialize;
use transformers::{
    self as airwallex, AirwallexAccessTokenRequest, AirwallexAccessTokenResponse,
    AirwallexAuthorizeRequest, AirwallexCaptureRequest, AirwallexCaptureResponse,
    AirwallexCustomerRequest, AirwallexCustomerResponse, AirwallexIntentRequest,
    AirwallexIntentResponse, AirwallexPaymentsResponse, AirwallexPostAuthenticateResponse,
    AirwallexPreAuthenticateRequest, AirwallexPreAuthenticateResponse, AirwallexRefundRequest,
    AirwallexRefundResponse, AirwallexRefundSyncResponse, AirwallexRepeatPaymentRequest,
    AirwallexRepeatPaymentResponse, AirwallexSetupMandateRequest, AirwallexSetupMandateResponse,
    AirwallexSyncResponse, AirwallexVoidRequest, AirwallexVoidResponse,
};

use super::macros;
use crate::types::ResponseRouterData;
use crate::with_error_response_body;
use domain_types::errors::ConnectorError;
use domain_types::errors::IntegrationError;

pub(crate) mod headers {
    pub(crate) const CONTENT_TYPE: &str = "Content-Type";
    pub(crate) const AUTHORIZATION: &str = "Authorization";
    pub(crate) const X_API_VERSION: &str = "x-api-version";
}

/// The Airwallex API version every `/pa/*` call is pinned to.
///
/// Airwallex documents `x-api-version` as per-call and, when it is absent, applies "your version
/// … stored in your account". That makes the wire contract a property of the merchant's account
/// settings rather than of this code: two merchants on the same UCS build can get two different
/// request shapes, and neither is observable from here. Pinning removes that entire class of
/// "works in our sandbox, 400s in production" failure.
///
/// `2024-06-14` is the earliest version whose 3DS behaviour is the modern one — a single
/// Airwallex-hosted `redirect_iframe` that performs the 3DS method call and the ACS challenge,
/// with no `confirm_continue` round trip — and it is stable through `2026-06-29`. The only later
/// change that touches this connector is `2026-06-30`, which moves
/// `payment_method.card.three_ds.return_url` to a top-level `return_url`; raising the pin past
/// that date means moving exactly one field.
pub(crate) const AIRWALLEX_API_VERSION: &str = "2024-06-14";

// Airwallex struct will be generated by create_all_prerequisites! macro

// ===== CONNECTOR SERVICE TRAIT IMPLEMENTATIONS =====
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ConnectorServiceTrait<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentAuthorizeV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentSyncV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentVoidV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentCapture for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RefundV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RefundSyncV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::SetupMandateV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RepeatPaymentV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ServerAuthentication for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentPreAuthenticateV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentPostAuthenticateV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentOrderCreate for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::IncomingWebhook for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::VerifyRedirectResponse for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> SourceVerification
    for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> BodyDecoding
    for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ValidationTrait for Airwallex<T>
{
    fn should_do_access_token(&self, _payment_method: Option<common_enums::PaymentMethod>) -> bool {
        true
    }

    fn should_do_order_create(&self) -> bool {
        true // Enable 2-step flow: ServerAuthenticationToken → CreateOrder → Authorize
    }

    /// Drives the composite authorize loop through Airwallex's two-call 3DS journey for
    /// card + ThreeDs: `PreAuthenticate` (`POST .../confirm`) → Airwallex-hosted redirect →
    /// `PostAuthenticate` (`GET .../{id}`) → `Authorize` (which, having a `redirect_response`, is
    /// itself a `GET` retrieve — see `transformers::is_card_three_ds_continue`).
    ///
    /// **No arm returns [`AuthenticationStep::Authenticate`], and that is deliberate.** On the
    /// pinned API version Airwallex runs the 3DS method call and the ACS challenge inside its own
    /// hosted page; there is no merchant-issued call between `confirm` and the browser's return.
    /// `PaymentAuthenticateV2` is therefore not implemented and `Authenticate` stays in
    /// `not_implemented`. Because Airwallex's `confirm` *is* the authorization, any arm that led
    /// to a second `confirm` would be a double charge.
    ///
    /// Termination: `PreAuthenticate` breaks the loop itself when it returns a redirect, and both
    /// `Some(PreAuthenticate)` and `Some(PostAuthenticate)` resolve to `Authorize`, which is the
    /// loop's unconditional exit. `PostAuthenticate` never breaks on its own, so the
    /// `Some(PostAuthenticate) => Authorize` arm is mandatory.
    ///
    /// [`AuthenticationStep::Authenticate`]: connector_types::AuthenticationStep::Authenticate
    fn next_authentication_step(
        &self,
        auth_type: common_enums::AuthenticationType,
        payment_method: common_enums::PaymentMethod,
        redirect_state: connector_types::RedirectState,
        completed_step: Option<connector_types::AuthenticationStep>,
    ) -> connector_types::AuthenticationStep {
        use connector_types::{AuthenticationStep, RedirectState};

        if auth_type != common_enums::AuthenticationType::ThreeDs
            || payment_method != common_enums::PaymentMethod::Card
        {
            return AuthenticationStep::Authorize;
        }

        match (redirect_state, completed_step) {
            (RedirectState::InitialRequest, None) => AuthenticationStep::PreAuthenticate,
            // Frictionless / not enrolled / SKIP_3DS: the confirm came back terminal with no
            // next_action, so there is nothing to authenticate and nothing to retrieve.
            (RedirectState::InitialRequest, Some(AuthenticationStep::PreAuthenticate)) => {
                AuthenticationStep::Authorize
            }
            // The shopper has returned from the Airwallex-hosted page. Retrieve the intent — the
            // return-URL query string is advisory, the retrieved intent is the authority.
            (RedirectState::RedirectWithParams | RedirectState::RedirectWithoutParams, None) => {
                AuthenticationStep::PostAuthenticate
            }
            (
                RedirectState::RedirectWithParams | RedirectState::RedirectWithoutParams,
                Some(AuthenticationStep::PostAuthenticate),
            ) => AuthenticationStep::Authorize,
            _ => AuthenticationStep::Authorize,
        }
    }
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::CreateConnectorCustomer for Airwallex<T>
{
}

// ===== MACRO-BASED IMPLEMENTATION =====

macros::create_all_prerequisites!(
    connector_name: Airwallex,
    generic_type: T,
    api: [
        (
            flow: Authorize,
            request_body: AirwallexAuthorizeRequest,
            response_body: AirwallexPaymentsResponse,
            router_data: RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ),
        (
            flow: PSync,
            response_body: AirwallexSyncResponse,
            router_data: RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ),
        (
            flow: Capture,
            request_body: AirwallexCaptureRequest,
            response_body: AirwallexCaptureResponse,
            router_data: RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ),
        (
            flow: Refund,
            request_body: AirwallexRefundRequest,
            response_body: AirwallexRefundResponse,
            router_data: RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ),
        (
            flow: RSync,
            response_body: AirwallexRefundSyncResponse,
            router_data: RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ),
        (
            flow: Void,
            request_body: AirwallexVoidRequest,
            response_body: AirwallexVoidResponse,
            router_data: RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ),
        (
            flow: ServerAuthenticationToken,
            request_body: AirwallexAccessTokenRequest,
            response_body: AirwallexAccessTokenResponse,
            router_data: RouterDataV2<ServerAuthenticationToken, MerchantAuthenticationFlowData, ServerAuthenticationTokenRequestData, ServerAuthenticationTokenResponseData>,
        ),
        (
            flow: CreateOrder,
            request_body: AirwallexIntentRequest,
            response_body: AirwallexIntentResponse,
            router_data: RouterDataV2<CreateOrder, PaymentFlowData, PaymentCreateOrderData, PaymentCreateOrderResponse>,
        ),
        (
            flow: SetupMandate,
            request_body: AirwallexSetupMandateRequest,
            response_body: AirwallexSetupMandateResponse,
            router_data: RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ),
        (
            flow: RepeatPayment,
            request_body: AirwallexRepeatPaymentRequest,
            response_body: AirwallexRepeatPaymentResponse,
            router_data: RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ),
        (
            flow: CreateConnectorCustomer,
            request_body: AirwallexCustomerRequest,
            response_body: AirwallexCustomerResponse,
            router_data: RouterDataV2<CreateConnectorCustomer, PaymentFlowData, ConnectorCustomerData, ConnectorCustomerResponse>,
        ),
        (
            flow: PreAuthenticate,
            request_body: AirwallexPreAuthenticateRequest,
            response_body: AirwallexPreAuthenticateResponse,
            router_data: RouterDataV2<PreAuthenticate, PaymentFlowData, PaymentsPreAuthenticateData<T>, PaymentsResponseData>,
        ),
        (
            flow: PostAuthenticate,
            response_body: AirwallexPostAuthenticateResponse,
            router_data: RouterDataV2<PostAuthenticate, PaymentFlowData, PaymentsPostAuthenticateData<T>, PaymentsResponseData>,
        )
    ],
    amount_converters: [
        amount_converter: StringMajorUnit
    ],
    member_functions: {
        /// Build headers with OAuth Bearer token - works for all flow types.
        ///
        /// `x-api-version` is pinned on every call; see [`AIRWALLEX_API_VERSION`] for why sending
        /// no version header is itself the bug.
        pub fn build_headers(
            &self,
            access_token: &str,
        ) -> Vec<(String, Maskable<String>)> {
            vec![
                (
                    headers::CONTENT_TYPE.to_string(),
                    self.common_get_content_type().to_string().into(),
                ),
                (
                    headers::AUTHORIZATION.to_string(),
                    format!("Bearer {access_token}").into(),
                ),
                (
                    headers::X_API_VERSION.to_string(),
                    AIRWALLEX_API_VERSION.to_string().into(),
                ),
            ]
        }
    }
);

macros::macro_connector_payout_implementation!(
    connector: Airwallex,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize]
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexAuthorizeRequest),
    curl_response: AirwallexPaymentsResponse,
    flow_name: Authorize,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsAuthorizeData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // 2-step flow: Authorize confirms the payment intent created by CreateOrder.
            // Get order_id from reference_id (stored after CreateOrder via set_order_reference_id).
            let order_id = req.resource_common_data.connector_order_id
                .as_ref()
                .ok_or(IntegrationError::MissingRequiredField { field_name: "connector_order_id", context: Default::default() })?;
            let base_url = &req.resource_common_data.connectors.airwallex.base_url;
            // When HS re-invokes Authorize after a card 3DS redirect, the payment has ALREADY been
            // authorized by the first `confirm` — on the pinned API version Airwallex's own guide
            // says to "Retrieve PaymentIntent to confirm status". So the return leg is a bodyless
            // retrieve, not a second confirm and not the removed `confirm_continue`. Same gate as
            // `build_request_v2` below, so the URL and the HTTP method cannot disagree.
            if transformers::is_card_three_ds_continue(&req.request) {
                Ok(format!("{base_url}/pa/payment_intents/{order_id}"))
            } else {
                Ok(format!("{base_url}/pa/payment_intents/{order_id}/confirm"))
            }
        }
        /// `get_http_method` only sees `&self`, so the 3DS return leg's `GET` has to be chosen
        /// here: it is a retrieve of the intent the first `confirm` already authorized, and it
        /// carries no body. Everything else keeps the macro-generated `POST` + JSON body.
        fn build_request_v2(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<Option<common_utils::request::Request>, IntegrationError> {
            use common_utils::request::{Method, RequestBuilder};

            let is_three_ds_return_leg = transformers::is_card_three_ds_continue(&req.request);

            let builder = RequestBuilder::new()
                .method(if is_three_ds_return_leg { Method::Get } else { Method::Post })
                .url(self.get_url(req)?.as_str())
                .attach_default_headers()
                .headers(self.get_headers(req)?);

            let builder = if is_three_ds_return_leg {
                builder
            } else {
                let request_data = self.get_request_body(req)?;
                let (body, typed_request_value) = match request_data {
                    Some(data) => (Some(data.content), data.typed_request.map(|msv| msv.inner().clone())),
                    None => (None, None),
                };
                builder
                    .set_optional_body(body)
                    .set_typed_connector_request(typed_request_value)
            };

            Ok(Some(builder.build()))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_response: AirwallexSyncResponse,
    flow_name: PSync,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsSyncData,
    flow_response: PaymentsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let payment_id = req.request.get_connector_transaction_id()?;
            Ok(format!("{}/pa/payment_intents/{}", req.resource_common_data.connectors.airwallex.base_url, payment_id))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexCaptureRequest),
    curl_response: AirwallexCaptureResponse,
    flow_name: Capture,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsCaptureData,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let payment_id = match &req.request.connector_transaction_id {
                ResponseId::ConnectorTransactionId(id) => id,
                _ => return Err(IntegrationError::MissingConnectorTransactionID { context: Default::default() }.into())
};
            Ok(format!("{}/pa/payment_intents/{}/capture", req.resource_common_data.connectors.airwallex.base_url, payment_id))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexRefundRequest),
    curl_response: AirwallexRefundResponse,
    flow_name: Refund,
    resource_common_data: RefundFlowData,
    flow_request: RefundsData,
    flow_response: RefundsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!("{}/pa/refunds/create", req.resource_common_data.connectors.airwallex.base_url))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_response: AirwallexRefundSyncResponse,
    flow_name: RSync,
    resource_common_data: RefundFlowData,
    flow_request: RefundSyncData,
    flow_response: RefundsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let refund_id = req.request.connector_refund_id.clone();
            Ok(format!("{}/pa/refunds/{}", req.resource_common_data.connectors.airwallex.base_url, refund_id))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexAccessTokenRequest),
    curl_response: AirwallexAccessTokenResponse,
    flow_name: ServerAuthenticationToken,
    resource_common_data: MerchantAuthenticationFlowData,
    flow_request: ServerAuthenticationTokenRequestData,
    flow_response: ServerAuthenticationTokenResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<ServerAuthenticationToken, MerchantAuthenticationFlowData, ServerAuthenticationTokenRequestData, ServerAuthenticationTokenResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let auth = airwallex::AirwallexAuthType::try_from(&req.connector_config)
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(vec![
                (
                    headers::CONTENT_TYPE.to_string(),
                    "application/json".to_string().into(),
                ),
                (
                    "x-api-key".to_string(),
                    auth.api_key.expose().to_string().into(),
                ),
                (
                    "x-client-id".to_string(),
                    auth.client_id.expose().to_string().into(),
                ),
            ])
        }
        fn get_url(
            &self,
            req: &RouterDataV2<ServerAuthenticationToken, MerchantAuthenticationFlowData, ServerAuthenticationTokenRequestData, ServerAuthenticationTokenResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!("{}/authentication/login", req.resource_common_data.connectors.airwallex.base_url))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexIntentRequest),
    curl_response: AirwallexIntentResponse,
    flow_name: CreateOrder,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentCreateOrderData,
    flow_response: PaymentCreateOrderResponse,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<CreateOrder, PaymentFlowData, PaymentCreateOrderData, PaymentCreateOrderResponse>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<CreateOrder, PaymentFlowData, PaymentCreateOrderData, PaymentCreateOrderResponse>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!("{}/pa/payment_intents/create", req.resource_common_data.connectors.airwallex.base_url))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexSetupMandateRequest),
    curl_response: AirwallexSetupMandateResponse,
    flow_name: SetupMandate,
    resource_common_data: PaymentFlowData,
    flow_request: SetupMandateRequestData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // SetupMandate confirms the payment intent created by CreateOrder (auto-chained via should_do_order_create).
            let order_id = req.resource_common_data.connector_order_id
                .as_ref()
                .ok_or(IntegrationError::MissingRequiredField { field_name: "connector_order_id", context: Default::default() })?;
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexRepeatPaymentRequest),
    curl_response: AirwallexRepeatPaymentResponse,
    flow_name: RepeatPayment,
    resource_common_data: PaymentFlowData,
    flow_request: RepeatPaymentData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // Airwallex MIT requires a fresh PaymentIntent; the caller must run CreateOrder
            // first. See `transformers::get_connector_order_id` for where the id is read from.
            let order_id = transformers::get_connector_order_id(&req.resource_common_data)?;
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

// ===== EMPTY IMPLEMENTATIONS FOR OTHER FLOWS =====
// These will be implemented separately as needed

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexVoidRequest),
    curl_response: AirwallexVoidResponse,
    flow_name: Void,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentVoidData,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let payment_id = req.request.connector_transaction_id.clone();
            Ok(format!("{}/pa/payment_intents/{}/cancel", req.resource_common_data.connectors.airwallex.base_url, payment_id))
        }
    }
);

// Payment Void Post Capture

// ClientAuthenticationToken - Empty implementation (Airwallex doesn't support SDK session tokens)

// Payment Capture - implemented using macro above

// Refund - implemented using macro above

// Refund Sync - implemented using macro above

// Setup Mandate - implemented via macro below

// ServerAuthenticationToken - Airwallex Authentication Flow - will be implemented using macro

// Repeat Payment - implemented using macro below

// Order Create - implemented using macro above

// Session Token

// Dispute Accept

// Dispute Defend

// Submit Evidence

// Payment Token (required by PaymentTokenV2 trait)

// Access Token implementation is above - removing duplicate

// ===== AUTHENTICATION FLOW CONNECTOR INTEGRATIONS =====
//
// Airwallex's 3DS journey is two network calls, not three: PreAuthenticate confirms the intent
// and PostAuthenticate retrieves it. There is intentionally NO `Authenticate` implementation —
// Airwallex performs the 3DS method call and the ACS challenge inside its own hosted
// `redirect_iframe` page, so there is no merchant-issued call to make in between. See
// `Airwallex::next_authentication_step`, which never returns `AuthenticationStep::Authenticate`,
// and the `not_implemented:` list at the bottom of this file, which still carries `Authenticate`.

// Pre Authentication — POST /pa/payment_intents/{id}/confirm
macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexPreAuthenticateRequest),
    curl_response: AirwallexPreAuthenticateResponse,
    flow_name: PreAuthenticate,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsPreAuthenticateData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PreAuthenticate, PaymentFlowData, PaymentsPreAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<PreAuthenticate, PaymentFlowData, PaymentsPreAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // Airwallex authenticates by confirming an existing PaymentIntent, so CreateOrder
            // must have run first. See `transformers::get_connector_order_id`.
            let order_id = transformers::get_connector_order_id(&req.resource_common_data)?;
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

// Authentication — deliberately not implemented; see the block comment above.

// Post Authentication — GET /pa/payment_intents/{id}
macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_response: AirwallexPostAuthenticateResponse,
    flow_name: PostAuthenticate,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsPostAuthenticateData<T>,
    flow_response: PaymentsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PostAuthenticate, PaymentFlowData, PaymentsPostAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<PostAuthenticate, PaymentFlowData, PaymentsPostAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let intent_id = transformers::get_post_authenticate_intent_id(&req.request)?;
            Ok(format!(
                "{}/pa/payment_intents/{}",
                req.resource_common_data.connectors.airwallex.base_url,
                intent_id
            ))
        }
    }
);

// ===== CONNECTOR CUSTOMER CONNECTOR INTEGRATIONS =====
// Create Connector Customer — POST /api/v1/pa/customers/create.
//
// Airwallex requires a Bearer access token (from ServerAuthenticationToken).
// CustomerServiceCreateRequest has no `state` field in the proto, so the access
// token is passed manually via `connector_feature_data` as JSON of the shape
// `{"access_token": "<token>"}`. This mirrors the existing RepeatPayment fallback
// pattern for `connector_order_id`.
macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexCustomerRequest),
    curl_response: AirwallexCustomerResponse,
    flow_name: CreateConnectorCustomer,
    resource_common_data: PaymentFlowData,
    flow_request: ConnectorCustomerData,
    flow_response: ConnectorCustomerResponse,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<CreateConnectorCustomer, PaymentFlowData, ConnectorCustomerData, ConnectorCustomerResponse>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req
                .resource_common_data
                .get_access_token()
                .ok()
                .or_else(|| {
                    req.resource_common_data
                        .connector_feature_data
                        .as_ref()
                        .and_then(|v| {
                            v.peek()
                                .get("access_token")
                                .and_then(|tok| tok.as_str().map(|s| s.to_string()))
                        })
                })
                .ok_or(IntegrationError::FailedToObtainAuthType {
                    context: Default::default(),
                })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<CreateConnectorCustomer, PaymentFlowData, ConnectorCustomerData, ConnectorCustomerResponse>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!(
                "{}/pa/customers/create",
                req.resource_common_data.connectors.airwallex.base_url
            ))
        }
    }
);

// Incremental Authorization

// ===== CONNECTOR COMMON IMPLEMENTATION =====
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> ConnectorCommon
    for Airwallex<T>
{
    fn id(&self) -> &'static str {
        "airwallex"
    }

    fn get_currency_unit(&self) -> CurrencyUnit {
        CurrencyUnit::Base
    }

    fn common_get_content_type(&self) -> &'static str {
        "application/json"
    }

    fn base_url<'a>(&self, connectors: &'a Connectors) -> &'a str {
        connectors.airwallex.base_url.as_ref()
    }

    fn get_auth_header(
        &self,
        auth_type: &ConnectorSpecificConfig,
    ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
        // Note: This method should not be used for OAuth-based connectors like Airwallex
        // Use build_payment_headers or build_refund_headers instead for OAuth flows
        // This method is only used for ServerAuthenticationToken flow
        let auth = airwallex::AirwallexAuthType::try_from(auth_type).change_context(
            IntegrationError::FailedToObtainAuthType {
                context: Default::default(),
            },
        )?;
        Ok(vec![
            (
                "x-api-key".to_string(),
                auth.api_key.expose().to_string().into(),
            ),
            (
                "x-client-id".to_string(),
                auth.client_id.expose().to_string().into(),
            ),
        ])
    }

    fn build_error_response(
        &self,
        res: Response,
        event_builder: Option<&mut events::Event>,
        _connector_config: &ConnectorSpecificConfig,
    ) -> CustomResult<ErrorResponse, ConnectorError> {
        let response: airwallex::AirwallexErrorResponse = res
            .response
            .parse_struct("AirwallexErrorResponse")
            .change_context(
                crate::utils::response_deserialization_fail(
                    res.status_code,
                "airwallex: response body did not match the expected format; confirm API version and connector documentation."),
            )?;

        with_error_response_body!(event_builder, response);
        let typed =
            macros::serialize_typed_connector_payload(&response, "typed_connector_response");

        let error_message = match response.source {
            Some(ref source) => format!("{}; {}", response.message, source),
            None => response.message.clone(),
        };

        Ok(ErrorResponse {
            status_code: res.status_code,
            code: response.code,
            message: error_message.clone(),
            reason: Some(error_message),
            attempt_status: None,
            connector_transaction_id: None,
            network_decline_code: None,
            network_advice_code: None,
            network_error_message: None,
            typed_connector_response: typed,
            raw_connector_response: None,
            raw_connector_request: None,
            typed_connector_request: None,
        })
    }
}

macros::macro_connector_flow_status_impls!(
    connector: Airwallex,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    not_implemented: [
        GetConnectorCustomer,
        ClientAuthenticationToken,
        MandateRevoke,
        ServerSessionAuthenticationToken,
        Accept,
        DefendDispute,
        SubmitEvidence,
        PaymentMethodToken,
        // Airwallex has no counterpart for `Authenticate` on the pinned API version: the 3DS
        // method call and the ACS challenge both happen inside the hosted redirect page, so
        // there is nothing for this leg to call. `next_authentication_step` never selects it.
        Authenticate,
        IncrementalAuthorization,
    ],
    not_supported: [
        VoidPostRefund,
        VoidPC,
    ],
);

#[cfg(test)]
mod tests {
    use common_enums::{AuthenticationType, PaymentMethod};
    use domain_types::payment_method_data::DefaultPCIHolder;
    use interfaces::connector_types::{AuthenticationStep, RedirectState, ValidationTrait};

    use super::Airwallex;

    /// Every `(RedirectState, Option<AuthenticationStep>)` pair the composite authorize loop can
    /// present. `Some(Authenticate)` is included precisely to prove that even if some other
    /// component fabricated it, Airwallex still refuses to run an authenticate leg.
    fn all_states() -> Vec<(RedirectState, Option<AuthenticationStep>)> {
        let redirect_states = [
            RedirectState::InitialRequest,
            RedirectState::RedirectWithParams,
            RedirectState::RedirectWithoutParams,
        ];
        let completed_steps = [
            None,
            Some(AuthenticationStep::PreAuthenticate),
            Some(AuthenticationStep::Authenticate),
            Some(AuthenticationStep::PostAuthenticate),
        ];
        redirect_states
            .into_iter()
            .flat_map(|redirect_state| {
                completed_steps
                    .into_iter()
                    .map(move |completed_step| (redirect_state, completed_step))
            })
            .collect()
    }

    /// Airwallex has no `Authenticate` counterpart on the pinned API version, and
    /// `PaymentAuthenticateV2` is not implemented. If any arm returned `Authenticate` the
    /// composite loop would call a flow that is still in `not_implemented:`.
    #[test]
    fn next_authentication_step_never_selects_authenticate() {
        let connector = Airwallex::<DefaultPCIHolder>::new();
        for (redirect_state, completed_step) in all_states() {
            let next = connector.next_authentication_step(
                AuthenticationType::ThreeDs,
                PaymentMethod::Card,
                redirect_state,
                completed_step,
            );
            assert_ne!(
                next,
                AuthenticationStep::Authenticate,
                "arm ({redirect_state:?}, {completed_step:?}) selected Authenticate"
            );
        }
    }

    /// `PostAuthenticate` never breaks the loop by itself, so the only way out is an arm that
    /// returns `Authorize`. Walking the machine from every starting state must reach it.
    #[test]
    fn next_authentication_step_always_terminates_at_authorize() {
        let connector = Airwallex::<DefaultPCIHolder>::new();
        for (redirect_state, initial_step) in all_states() {
            let mut completed_step = initial_step;
            let mut reached_authorize = false;
            // Four legs is already more than the state space; anything longer is a cycle.
            for _ in 0..4 {
                match connector.next_authentication_step(
                    AuthenticationType::ThreeDs,
                    PaymentMethod::Card,
                    redirect_state,
                    completed_step,
                ) {
                    AuthenticationStep::Authorize => {
                        reached_authorize = true;
                        break;
                    }
                    step => completed_step = Some(step),
                }
            }
            assert!(
                reached_authorize,
                "arm ({redirect_state:?}, {initial_step:?}) never terminated at Authorize"
            );
        }
    }

    /// The 3DS journey the spec describes: confirm, hosted redirect, retrieve, then the
    /// read-only Authorize.
    #[test]
    fn next_authentication_step_drives_the_two_call_three_ds_journey() {
        let connector = Airwallex::<DefaultPCIHolder>::new();
        let step = |redirect_state, completed_step| {
            connector.next_authentication_step(
                AuthenticationType::ThreeDs,
                PaymentMethod::Card,
                redirect_state,
                completed_step,
            )
        };

        assert_eq!(
            step(RedirectState::InitialRequest, None),
            AuthenticationStep::PreAuthenticate
        );
        // Frictionless: the confirm came back terminal, so go straight to the read.
        assert_eq!(
            step(
                RedirectState::InitialRequest,
                Some(AuthenticationStep::PreAuthenticate)
            ),
            AuthenticationStep::Authorize
        );
        // Challenge: the shopper is back from the hosted page — retrieve the intent.
        for redirect_state in [
            RedirectState::RedirectWithParams,
            RedirectState::RedirectWithoutParams,
        ] {
            assert_eq!(
                step(redirect_state, None),
                AuthenticationStep::PostAuthenticate
            );
            assert_eq!(
                step(redirect_state, Some(AuthenticationStep::PostAuthenticate)),
                AuthenticationStep::Authorize
            );
        }
    }

    /// The trio is opt-in: anything that is not a 3DS card payment keeps the inline Authorize
    /// path, so a bug in the trio cannot take non-3DS payments down.
    #[test]
    fn next_authentication_step_is_gated_on_three_ds_card() {
        let connector = Airwallex::<DefaultPCIHolder>::new();
        assert_eq!(
            connector.next_authentication_step(
                AuthenticationType::NoThreeDs,
                PaymentMethod::Card,
                RedirectState::InitialRequest,
                None,
            ),
            AuthenticationStep::Authorize
        );
        assert_eq!(
            connector.next_authentication_step(
                AuthenticationType::ThreeDs,
                PaymentMethod::Wallet,
                RedirectState::InitialRequest,
                None,
            ),
            AuthenticationStep::Authorize
        );
    }
}
