pub mod transformers;

use std::fmt::Debug;

use common_enums::CurrencyUnit;
use common_utils::{
    crypto::VerifySignature, errors::CustomResult, events, ext_traits::ByteSliceExt,
    types::StringMajorUnit,
};
use domain_types::{
    connector_flow::{
        Authorize, Capture, CreateConnectorCustomer, CreateOrder, PSync, PostAuthenticate,
        PreAuthenticate, RSync, Refund, RepeatPayment, ServerAuthenticationToken, SetupMandate,
        Void,
    },
    connector_types::{
        ConnectorCustomerData, ConnectorCustomerResponse, ConnectorWebhookSecrets,
        DisputeWebhookDetailsResponse, DisputeWebhookReference, EventContext, EventType,
        PaymentCreateOrderData, PaymentCreateOrderResponse, PaymentFlowData, PaymentVoidData,
        PaymentWebhookReference, PaymentsAuthorizeData, PaymentsCaptureData,
        PaymentsPostAuthenticateData, PaymentsPreAuthenticateData, PaymentsResponseData,
        PaymentsSyncData, RefundFlowData, RefundSyncData, RefundWebhookDetailsResponse,
        RefundWebhookReference, RefundsData, RefundsResponseData, RepeatPaymentData,
        RequestDetails, ResponseId, ServerAuthenticationTokenRequestData,
        ServerAuthenticationTokenResponseData, SetupMandateRequestData, WebhookDetailsResponse,
        WebhookResourceReference,
    },
    merchant_authentication_flow_data::MerchantAuthenticationFlowData,
    payment_method_data::PaymentMethodDataTypes,
    router_data::{ConnectorSpecificConfig, ErrorResponse},
    router_data_v2::RouterDataV2,
    router_response_types::Response,
    types::Connectors,
};
use error_stack::{report, Report, ResultExt};
use hyperswitch_masking::{ExposeInterface, Maskable, PeekInterface};
use interfaces::{
    api::ConnectorCommon, connector_integration_v2::ConnectorIntegrationV2, connector_types,
    decode::BodyDecoding, verification::SourceVerification,
};
use serde::Serialize;
use transformers::{
    self as airwallex, AirwallexAccessTokenRequest, AirwallexAccessTokenResponse,
    AirwallexAuthorizeRequest, AirwallexCaptureRequest, AirwallexCaptureResponse,
    AirwallexCustomerRequest, AirwallexCustomerResponse, AirwallexIntentRequest,
    AirwallexIntentResponse, AirwallexPaymentsResponse, AirwallexPostAuthenticateRequest,
    AirwallexPostAuthenticateResponse, AirwallexPreAuthenticateRequest,
    AirwallexPreAuthenticateResponse, AirwallexRefundRequest, AirwallexRefundResponse,
    AirwallexRefundSyncResponse, AirwallexRepeatPaymentRequest, AirwallexRepeatPaymentResponse,
    AirwallexSetupMandateRequest, AirwallexSetupMandateResponse, AirwallexSyncResponse,
    AirwallexVoidRequest, AirwallexVoidResponse, AIRWALLEX_API_VERSION,
};

use super::macros;
use crate::types::ResponseRouterData;
use crate::with_error_response_body;
use domain_types::errors::ConnectorError;
use domain_types::errors::IntegrationError;
use domain_types::errors::WebhookError;

pub(crate) mod headers {
    pub(crate) const CONTENT_TYPE: &str = "Content-Type";
    pub(crate) const AUTHORIZATION: &str = "Authorization";
    pub(crate) const X_API_VERSION: &str = "x-api-version";
}

// Airwallex struct will be generated by create_all_prerequisites! macro

// ===== CONNECTOR SERVICE TRAIT IMPLEMENTATIONS =====
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ConnectorServiceTrait<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentAuthorizeV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentSyncV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentVoidV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentCapture for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RefundV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RefundSyncV2 for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::SetupMandateV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RepeatPaymentV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ServerAuthentication for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentOrderCreate for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::IncomingWebhook for Airwallex<T>
{
    /// Airwallex's signature (spec §15.3): the `x-signature` header IS the signature,
    /// lowercase-hex of HMAC-SHA256. `hex::decode` produces exactly the 32-byte digest the
    /// verifier compares — never a base64 attempt, never a re-case (a case-insensitive compare
    /// would accept a signature the connector never sent).
    fn get_webhook_source_verification_signature(
        &self,
        request: &RequestDetails,
        _connector_webhook_secret: &ConnectorWebhookSecrets,
    ) -> Result<Vec<u8>, Report<WebhookError>> {
        let signature = request
            .headers
            .get("x-signature")
            .ok_or_else(|| report!(WebhookError::WebhookSignatureNotFound))
            .attach_printable("Airwallex webhook: missing x-signature header")?;

        hex::decode(signature.trim()).change_context(WebhookError::WebhookSignatureNotFound)
    }

    /// The bytes Airwallex signs: x-timestamp header bytes ++ the UNPARSED raw request body —
    /// no separator, no re-serialisation (a serde parse-and-print of the body would reorder
    /// keys/whitespace and waste no one's HMAC).
    fn get_webhook_source_verification_message(
        &self,
        request: &RequestDetails,
        _connector_webhook_secret: &ConnectorWebhookSecrets,
    ) -> Result<Vec<u8>, Report<WebhookError>> {
        let timestamp = request.headers.get("x-timestamp").ok_or_else(|| {
            report!(WebhookError::WebhookMissingRequiredField {
                field: "x-timestamp header",
            })
        })?;

        let mut message = Vec::with_capacity(timestamp.len() + request.body.len());
        message.extend_from_slice(timestamp.as_bytes());
        message.extend_from_slice(&request.body);
        Ok(message)
    }

    /// Constant-time compare of received vs computed signature. No secrets ⇒ refuse: a webhook
    /// verified against nothing has no security meaning, and Airwallex never sends an unsigned
    /// notification on a configured URL (spec §15.3). A malformed signature surfaces as a
    /// verification failure, never a panic.
    fn verify_webhook_source(
        &self,
        request: RequestDetails,
        connector_webhook_secret: Option<ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
    ) -> Result<bool, Report<WebhookError>> {
        let connector_webhook_secrets = match connector_webhook_secret {
            Some(secrets) => secrets,
            None => {
                return Err(report!(WebhookError::WebhookVerificationSecretNotFound));
            }
        };

        let algorithm = common_utils::crypto::HmacSha256;
        let signature =
            self.get_webhook_source_verification_signature(&request, &connector_webhook_secrets)?;
        let message =
            self.get_webhook_source_verification_message(&request, &connector_webhook_secrets)?;

        algorithm
            .verify_signature(&connector_webhook_secrets.secret, &signature, &message)
            .change_context(WebhookError::WebhookSourceVerificationFailed)
            .attach_printable("Airwallex webhook: HMAC-SHA256 x-signature mismatch")
    }

    /// The stateless event pass: parse ONLY the envelope (never `data.object`), report the
    /// event name. An event name Airwallex added after this mapping shipped lands on
    /// `IncomingWebhookEventUnspecified` — never an error: the contract is recognition, not
    /// completeness.
    fn get_event_type(&self, request: RequestDetails) -> Result<EventType, Report<WebhookError>> {
        let envelope: airwallex::AirwallexWebhookEnvelope = request
            .body
            .parse_struct("AirwallexWebhookEnvelope")
            .change_context(WebhookError::WebhookEventTypeNotFound)?;

        Ok(airwallex::map_webhook_event_type(&envelope.name))
    }

    /// The stateless reference pass: `data.object` binds by FAMILY only after `name` is
    /// known — an untagged parse of an attempt silently binds as an intent since the two share
    /// id/amount/currency/status keys. The attempt family's connector_transaction_id is the
    /// INTENT id (`payment_intent_id`), never the `att_…` object id (G-incomingwebhook-03@Card);
    /// a refund's merchant id is recovered from the `request_id` echo this connector wrote as
    /// `refund_{reference}` (never from the refund id — the two name different resources).
    fn get_webhook_event_reference(
        &self,
        request: RequestDetails,
    ) -> Result<Option<WebhookResourceReference>, Report<WebhookError>> {
        let envelope: airwallex::AirwallexWebhookEnvelope = request
            .body
            .parse_struct("AirwallexWebhookEnvelope")
            .change_context(WebhookError::WebhookReferenceIdNotFound)?;

        let reference = match envelope.name {
            airwallex::AirwallexWebhookEvent::PaymentIntentCreated
            | airwallex::AirwallexWebhookEvent::PaymentIntentRequiresPaymentMethod
            | airwallex::AirwallexWebhookEvent::PaymentIntentUpdated
            | airwallex::AirwallexWebhookEvent::PaymentIntentRequiresCustomerAction
            | airwallex::AirwallexWebhookEvent::PaymentIntentRequiresCapture
            | airwallex::AirwallexWebhookEvent::PaymentIntentPending
            | airwallex::AirwallexWebhookEvent::PaymentIntentPendingReview
            | airwallex::AirwallexWebhookEvent::PaymentIntentSucceeded
            | airwallex::AirwallexWebhookEvent::PaymentIntentCancelled
            | airwallex::AirwallexWebhookEvent::PaymentIntentPaymentFailed => {
                let intent: airwallex::AirwallexIntentWebhookObject =
                    serde_json::from_value(envelope.data.object.clone())
                        .change_context(WebhookError::WebhookReferenceIdNotFound)?;
                Some(WebhookResourceReference::Payment(PaymentWebhookReference {
                    connector_transaction_id: Some(intent.id),
                    merchant_transaction_id: intent.merchant_order_id,
                }))
            }

            airwallex::AirwallexWebhookEvent::PaymentAttemptReceived
            | airwallex::AirwallexWebhookEvent::PaymentAttemptAuthenticationRedirected
            | airwallex::AirwallexWebhookEvent::PaymentAttemptAuthenticationFailed
            | airwallex::AirwallexWebhookEvent::PaymentAttemptPendingAuthorization
            | airwallex::AirwallexWebhookEvent::PaymentAttemptAuthorized
            | airwallex::AirwallexWebhookEvent::PaymentAttemptAuthorizationFailed
            | airwallex::AirwallexWebhookEvent::PaymentAttemptCaptureRequested
            | airwallex::AirwallexWebhookEvent::PaymentAttemptCaptureFailed
            | airwallex::AirwallexWebhookEvent::PaymentAttemptSettled
            | airwallex::AirwallexWebhookEvent::PaymentAttemptPaid
            | airwallex::AirwallexWebhookEvent::PaymentAttemptCancelled
            | airwallex::AirwallexWebhookEvent::PaymentAttemptExpired
            | airwallex::AirwallexWebhookEvent::PaymentAttemptRiskDeclined
            | airwallex::AirwallexWebhookEvent::PaymentAttemptFailedToProcess => {
                let attempt: airwallex::AirwallexAttemptWebhookObject =
                    serde_json::from_value(envelope.data.object.clone())
                        .change_context(WebhookError::WebhookReferenceIdNotFound)?;
                Some(WebhookResourceReference::Payment(PaymentWebhookReference {
                    // The one documented trap: never the attempt's own id. UCS tracks the
                    // payment by its intent id; the att_ id names a retry of it.
                    connector_transaction_id: attempt.payment_intent_id,
                    merchant_transaction_id: attempt.merchant_order_id,
                }))
            }

            airwallex::AirwallexWebhookEvent::RefundReceived
            | airwallex::AirwallexWebhookEvent::RefundAccepted
            | airwallex::AirwallexWebhookEvent::RefundSettled
            | airwallex::AirwallexWebhookEvent::RefundFailed => {
                let refund: airwallex::AirwallexRefundWebhookObject =
                    serde_json::from_value(envelope.data.object.clone())
                        .change_context(WebhookError::WebhookReferenceIdNotFound)?;
                Some(WebhookResourceReference::Refund(RefundWebhookReference {
                    connector_refund_id: Some(refund.id),
                    merchant_refund_id: airwallex::resolve_refund_merchant_id(
                        refund.request_id.as_deref(),
                    ),
                    connector_transaction_id: refund.payment_intent_id,
                    merchant_transaction_id: None,
                }))
            }

            airwallex::AirwallexWebhookEvent::PaymentDisputeRequiresResponse
            | airwallex::AirwallexWebhookEvent::PaymentDisputeChallenged
            | airwallex::AirwallexWebhookEvent::PaymentDisputeAccepted
            | airwallex::AirwallexWebhookEvent::PaymentDisputeExpired
            | airwallex::AirwallexWebhookEvent::PaymentDisputePendingClosure
            | airwallex::AirwallexWebhookEvent::PaymentDisputePendingDecision
            | airwallex::AirwallexWebhookEvent::PaymentDisputeWon
            | airwallex::AirwallexWebhookEvent::PaymentDisputeLost
            | airwallex::AirwallexWebhookEvent::PaymentDisputeReversed => {
                let dispute: airwallex::AirwallexDisputeObject =
                    serde_json::from_value(envelope.data.object.clone())
                        .change_context(WebhookError::WebhookReferenceIdNotFound)?;
                Some(WebhookResourceReference::Dispute(DisputeWebhookReference {
                    connector_dispute_id: Some(dispute.id),
                    // The one real published sample carries no payment_intent_id; the field is
                    // documented but optional on the wire, so the reference tolerates its
                    // absence (never the dispute id as a stand-in).
                    connector_transaction_id: dispute.payment_intent_id,
                }))
            }

            airwallex::AirwallexWebhookEvent::PaymentConsentCreated
            | airwallex::AirwallexWebhookEvent::PaymentConsentUpdated
            | airwallex::AirwallexWebhookEvent::PaymentConsentPending
            | airwallex::AirwallexWebhookEvent::PaymentConsentVerified
            | airwallex::AirwallexWebhookEvent::PaymentConsentDisabled
            | airwallex::AirwallexWebhookEvent::PaymentConsentPaused
            | airwallex::AirwallexWebhookEvent::PaymentConsentRequiresPaymentMethod
            | airwallex::AirwallexWebhookEvent::PaymentConsentRequiresCustomerAction
            | airwallex::AirwallexWebhookEvent::PaymentConsentVerificationFailed => {
                // TODO(mandate-webhooks): bind a MandateWebhookReference once the consent
                // lifecycle wires into the SetupMandate flow. Returning None here (not an
                // error) keeps acknowledgement 200-and-none-breaker: an onboarded merchant
                // gets a verified no-op, never a ParseEvent 400.
                None
            }

            // Every other family (customer/payment_method/payment_link/fraud/funds_split/pos)
            // and the forward-compat `Unknown`: a webhook we verified but do not model. None
            // means the caller acks and drops it — never a hard error.
            _ => None,
        };

        Ok(reference)
    }

    fn process_payment_webhook(
        &self,
        request: RequestDetails,
        _connector_webhook_secret: Option<ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
        _event_context: Option<EventContext>,
    ) -> Result<WebhookDetailsResponse, Report<WebhookError>> {
        let envelope: airwallex::AirwallexWebhookEnvelope = request
            .body
            .parse_struct("AirwallexWebhookEnvelope")
            .change_context(WebhookError::WebhookBodyDecodingFailed)?;

        airwallex::build_webhook_payment_response(&envelope, envelope.name, &request.body)
    }

    fn process_refund_webhook(
        &self,
        request: RequestDetails,
        _connector_webhook_secret: Option<ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
    ) -> Result<RefundWebhookDetailsResponse, Report<WebhookError>> {
        let envelope: airwallex::AirwallexWebhookEnvelope = request
            .body
            .parse_struct("AirwallexWebhookEnvelope")
            .change_context(WebhookError::WebhookBodyDecodingFailed)?;

        airwallex::build_webhook_refund_response(&envelope, &request.body)
    }

    fn process_dispute_webhook(
        &self,
        request: RequestDetails,
        _connector_webhook_secret: Option<ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
    ) -> Result<DisputeWebhookDetailsResponse, Report<WebhookError>> {
        let envelope: airwallex::AirwallexWebhookEnvelope = request
            .body
            .parse_struct("AirwallexWebhookEnvelope")
            .change_context(WebhookError::WebhookBodyDecodingFailed)?;

        airwallex::build_webhook_dispute_response(&envelope, &request.body)
    }

    /// The family-agnostic resource pass: hand back `data.object` as received — the caller
    /// inspects it typed (the per-family structs re-serialise lossy), while the raw Value
    /// keeps every field the connector put on the wire.
    fn get_webhook_resource_object(
        &self,
        request: RequestDetails,
    ) -> Result<Box<dyn hyperswitch_masking::ErasedMaskSerialize>, Report<WebhookError>> {
        let envelope: airwallex::AirwallexWebhookEnvelope = request
            .body
            .parse_struct("AirwallexWebhookEnvelope")
            .change_context(WebhookError::WebhookResourceObjectNotFound)?;

        Ok(Box::new(envelope.data.object))
    }

    /// A minimal-but-real `payment_intent.succeeded` envelope for the field-probe — NOT a
    /// fabricated document: name/id/data.object.id carry structurally valid Airwallex shapes,
    /// created_at is a timestamp string (never an epoch round-trip).
    fn sample_webhook_body(&self) -> &'static [u8] {
        br#"{"id":"evt_100_24e503a6-a5cf-4247-8dc3-8d9a4f8bbf7a","name":"payment_intent.succeeded","account_id":"acst_1a2b3c4d5e6f7788","org_id":"org_prod_AUD_emh5hvn0tbljdi6qt","data":{"object":{"id":"int_1a2b3c4d5e6f7788","merchant_order_id":"order_1234","status":"SUCCEEDED","amount":49.12,"currency":"HKD","captured_amount":49.12}},"created_at":"2024-05-06T07:31:29.226+0000"}"#
    }
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::VerifyRedirectResponse for Airwallex<T>
{
}

// Standalone 3DS trio markers (mechanism A). Airwallex fuses authentication and authorization:
// `POST /confirm` charges, so the trio carries exactly two legs — PreAuthenticate (the confirm)
// and PostAuthenticate (the GET retrieve). `Authenticate` has no counterpart on the pinned
// 2024-06-14 contract: it is intentionally NOT implemented (an unreachable impl would invite a
// second confirm, which double-charges), and `next_authentication_step` below never returns it.
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentPreAuthenticateV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentPostAuthenticateV2<T> for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> SourceVerification
    for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> BodyDecoding
    for Airwallex<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ValidationTrait for Airwallex<T>
{
    fn should_do_access_token(&self, _payment_method: Option<common_enums::PaymentMethod>) -> bool {
        true
    }

    fn should_do_order_create(&self) -> bool {
        true // Enable 2-step flow: ServerAuthenticationToken → CreateOrder → Authorize
    }

    // Sequence the composite authorize's authentication steps for (ThreeDs, Card). The default
    // returns `Authorize`, which would skip the trio entirely and produce a non-3DS payment.
    // Airwallex performs DDC/challenge inside its hosted page between confirm (PreAuthenticate)
    // and the browser return, so this table has NO Authenticate arm; and because the composite
    // loop never breaks after PostAuthenticate, the
    // `(Redirect*, Some(PostAuthenticate)) => Authorize` arm is what terminates the loop — it
    // is mandatory, not decorative.
    fn next_authentication_step(
        &self,
        auth_type: common_enums::AuthenticationType,
        payment_method: common_enums::PaymentMethod,
        redirect_state: connector_types::RedirectState,
        completed_step: Option<connector_types::AuthenticationStep>,
    ) -> connector_types::AuthenticationStep {
        use connector_types::{AuthenticationStep, RedirectState};
        if auth_type == common_enums::AuthenticationType::ThreeDs
            && payment_method == common_enums::PaymentMethod::Card
        {
            match (redirect_state, completed_step) {
                // Nothing done yet: the confirm (PreAuthenticate) is the first and only
                // charging leg of the trio.
                (RedirectState::InitialRequest, None) => AuthenticationStep::PreAuthenticate,

                // PreAuthenticate completed without the loop breaking — only reachable when its
                // response carried no redirect. Airwallex's PreAuthenticate always emits one
                // (challenge URL, or the return-url fallback for a frictionless-settled /
                // declined intent), so the loop breaks first; this arm keeps the dispatch total.
                (RedirectState::InitialRequest, Some(AuthenticationStep::PreAuthenticate)) => {
                    AuthenticationStep::Authorize
                }

                // The browser returned from Airwallex's hosted page with query params:
                // retrieve the settled intent.
                (RedirectState::RedirectWithParams, None) => AuthenticationStep::PostAuthenticate,

                // The browser returned with no query params: still the same retrieve —
                // the order reference identifies the intent, and the G-threeds-05@Card
                // correlation check in the response mapping decides what can be trusted.
                (RedirectState::RedirectWithoutParams, None) => {
                    AuthenticationStep::PostAuthenticate
                }

                // The composite loop breaks on Authorize only; after the retrieve there is
                // nothing left to do but the (read-only, GET-repaired) Authorize re-entry.
                (RedirectState::RedirectWithParams, Some(AuthenticationStep::PostAuthenticate)) => {
                    AuthenticationStep::Authorize
                }
                (
                    RedirectState::RedirectWithoutParams,
                    Some(AuthenticationStep::PostAuthenticate),
                ) => AuthenticationStep::Authorize,

                _ => AuthenticationStep::Authorize,
            }
        } else {
            AuthenticationStep::Authorize
        }
    }
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::CreateConnectorCustomer for Airwallex<T>
{
}

// ===== MACRO-BASED IMPLEMENTATION =====

macros::create_all_prerequisites!(
    connector_name: Airwallex,
    generic_type: T,
    api: [
        (
            flow: Authorize,
            request_body: AirwallexAuthorizeRequest,
            response_body: AirwallexPaymentsResponse,
            router_data: RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ),
        (
            flow: PSync,
            response_body: AirwallexSyncResponse,
            router_data: RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ),
        (
            flow: Capture,
            request_body: AirwallexCaptureRequest,
            response_body: AirwallexCaptureResponse,
            router_data: RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ),
        (
            flow: Refund,
            request_body: AirwallexRefundRequest,
            response_body: AirwallexRefundResponse,
            router_data: RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ),
        (
            flow: RSync,
            response_body: AirwallexRefundSyncResponse,
            router_data: RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ),
        (
            flow: Void,
            request_body: AirwallexVoidRequest,
            response_body: AirwallexVoidResponse,
            router_data: RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ),
        (
            flow: ServerAuthenticationToken,
            request_body: AirwallexAccessTokenRequest,
            response_body: AirwallexAccessTokenResponse,
            router_data: RouterDataV2<ServerAuthenticationToken, MerchantAuthenticationFlowData, ServerAuthenticationTokenRequestData, ServerAuthenticationTokenResponseData>,
        ),
        (
            flow: CreateOrder,
            request_body: AirwallexIntentRequest,
            response_body: AirwallexIntentResponse,
            router_data: RouterDataV2<CreateOrder, PaymentFlowData, PaymentCreateOrderData, PaymentCreateOrderResponse>,
        ),
        (
            flow: SetupMandate,
            request_body: AirwallexSetupMandateRequest,
            response_body: AirwallexSetupMandateResponse,
            router_data: RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ),
        (
            flow: RepeatPayment,
            request_body: AirwallexRepeatPaymentRequest,
            response_body: AirwallexRepeatPaymentResponse,
            router_data: RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ),
        (
            flow: PreAuthenticate,
            request_body: AirwallexPreAuthenticateRequest,
            response_body: AirwallexPreAuthenticateResponse,
            router_data: RouterDataV2<PreAuthenticate, PaymentFlowData, PaymentsPreAuthenticateData<T>, PaymentsResponseData>,
        ),
        (
            flow: PostAuthenticate,
            request_body: AirwallexPostAuthenticateRequest,
            response_body: AirwallexPostAuthenticateResponse,
            router_data: RouterDataV2<PostAuthenticate, PaymentFlowData, PaymentsPostAuthenticateData<T>, PaymentsResponseData>,
        ),
        (
            flow: CreateConnectorCustomer,
            request_body: AirwallexCustomerRequest,
            response_body: AirwallexCustomerResponse,
            router_data: RouterDataV2<CreateConnectorCustomer, PaymentFlowData, ConnectorCustomerData, ConnectorCustomerResponse>,
        )
    ],
    amount_converters: [
        amount_converter: StringMajorUnit
    ],
    member_functions: {
        /// Build headers with OAuth Bearer token - works for all flow types
        pub fn build_headers(
            &self,
            access_token: &str,
        ) -> Vec<(String, Maskable<String>)> {
            vec![
                (
                    headers::CONTENT_TYPE.to_string(),
                    self.common_get_content_type().to_string().into(),
                ),
                (
                    headers::AUTHORIZATION.to_string(),
                    format!("Bearer {access_token}").into(),
                ),
                // Pin every call to the 2024-06-14 contract (see AIRWALLEX_API_VERSION in
                // transformers.rs): without the header the account default governs, and the
                // fused confirm/3DS semantics this connector encodes only hold on the pin.
                (
                    headers::X_API_VERSION.to_string(),
                    AIRWALLEX_API_VERSION.to_string().into(),
                ),
            ]
        }
    }
);

macros::macro_connector_payout_implementation!(
    connector: Airwallex,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize]
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexAuthorizeRequest),
    curl_response: AirwallexPaymentsResponse,
    flow_name: Authorize,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsAuthorizeData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        // Request-conditional method (the `ConnectorIntegrationV2::get_http_method` hook takes
        // no request — the macro-generated constant is shadowed here, where the request is in
        // scope). The 3DS return leg is a READ, not a charge: on the pinned 2024-06-14 contract
        // money has already moved at the confirm (the trio's PreAuthenticate, or invocation 1
        // of the inline path), so the Authorize re-entry retrieves the settled intent. A POST
        // here would re-drive the confirm — a double-charge the gateway rejects only
        // opportunistically.
        fn build_request_v2(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<Option<common_utils::request::Request>, IntegrationError> {
            // Same gate as get_url, so method and URL cannot disagree.
            let (method, request_data) = if transformers::is_card_three_ds_continue(&req.request)
            {
                // The GET repair branch deliberately skips get_request_body: no body is sent.
                (common_utils::request::Method::Get, None)
            } else {
                (
                    ConnectorIntegrationV2::<
                        Authorize,
                        PaymentFlowData,
                        PaymentsAuthorizeData<T>,
                        PaymentsResponseData,
                    >::get_http_method(self),
                    ConnectorIntegrationV2::<
                        Authorize,
                        PaymentFlowData,
                        PaymentsAuthorizeData<T>,
                        PaymentsResponseData,
                    >::get_request_body(self, req)?,
                )
            };
            let (body, typed_request_value) = match request_data {
                Some(data) => (
                    Some(data.content),
                    data.typed_request.map(|msv| msv.inner().clone()),
                ),
                None => (None, None),
            };
            let request = common_utils::request::RequestBuilder::new()
                .method(method)
                .url(self.get_url(req)?.as_str())
                .attach_default_headers()
                .headers(self.get_headers(req)?)
                .set_optional_body(body)
                .set_typed_connector_request(typed_request_value)
                .add_certificate(self.get_certificate(req)?)
                .add_certificate_key(self.get_certificate_key(req)?)
                .add_ca_certificate_pem(self.get_ca_certificate(req)?)
                .build();
            Ok(Some(request))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // 2-step flow: Authorize confirms the payment intent created by CreateOrder.
            // Get order_id from reference_id (stored after CreateOrder via set_order_reference_id).
            let order_id = req.resource_common_data.connector_order_id
                .as_ref()
                .ok_or(IntegrationError::MissingRequiredField { field_name: "connector_order_id", context: Default::default() })?;
            // The trio runs the card 3DS return through PostAuthenticate (a GET retrieve) and
            // then re-enters Authorize with redirect_response populated. On the pinned
            // contract that re-entry must read the settled intent — no suffix — rather than
            // POST any confirm variant: the money moved at the confirm leg already.
            if transformers::is_card_three_ds_continue(&req.request) {
                return Ok(format!(
                    "{}/pa/payment_intents/{}",
                    req.resource_common_data.connectors.airwallex.base_url,
                    order_id
                ));
            }
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexPreAuthenticateRequest),
    curl_response: AirwallexPreAuthenticateResponse,
    flow_name: PreAuthenticate,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsPreAuthenticateData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PreAuthenticate, PaymentFlowData, PaymentsPreAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<PreAuthenticate, PaymentFlowData, PaymentsPreAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // G-threeds-02@Card: the confirm rides the same intent CreateOrder created; a
            // PreAuthenticate without it has no payment to authenticate.
            let order_id = req.resource_common_data.connector_order_id
                .as_ref()
                .ok_or(IntegrationError::MissingRequiredField { field_name: "connector_order_id", context: Default::default() })?;
            // The trio's charging leg: POST /confirm IS the authorization. Same URL the
            // Authorize confirm leg uses — the two legs send the same call with different
            // marker data.
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexPostAuthenticateRequest),
    curl_response: AirwallexPostAuthenticateResponse,
    flow_name: PostAuthenticate,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsPostAuthenticateData<T>,
    flow_response: PaymentsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PostAuthenticate, PaymentFlowData, PaymentsPostAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<PostAuthenticate, PaymentFlowData, PaymentsPostAuthenticateData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // G-threeds-02@Card: PostAuthenticate reads the intent the browser-leg just
            // settled; with no order id there is nothing to retrieve.
            let order_id = req.resource_common_data.connector_order_id
                .as_ref()
                .ok_or(IntegrationError::MissingRequiredField { field_name: "connector_order_id", context: Default::default() })?;
            // A read, never a charge: the intent is already terminal by the time the browser
            // returns. This is the ONLY call PostAuthenticate makes.
            Ok(format!(
                "{}/pa/payment_intents/{}",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_response: AirwallexSyncResponse,
    flow_name: PSync,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsSyncData,
    flow_response: PaymentsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let payment_id = req.request.get_connector_transaction_id()?;
            Ok(format!("{}/pa/payment_intents/{}", req.resource_common_data.connectors.airwallex.base_url, payment_id))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexCaptureRequest),
    curl_response: AirwallexCaptureResponse,
    flow_name: Capture,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsCaptureData,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let payment_id = match &req.request.connector_transaction_id {
                ResponseId::ConnectorTransactionId(id) => id,
                _ => return Err(IntegrationError::MissingConnectorTransactionID { context: Default::default() }.into())
};
            Ok(format!("{}/pa/payment_intents/{}/capture", req.resource_common_data.connectors.airwallex.base_url, payment_id))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexRefundRequest),
    curl_response: AirwallexRefundResponse,
    flow_name: Refund,
    resource_common_data: RefundFlowData,
    flow_request: RefundsData,
    flow_response: RefundsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!("{}/pa/refunds/create", req.resource_common_data.connectors.airwallex.base_url))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_response: AirwallexRefundSyncResponse,
    flow_name: RSync,
    resource_common_data: RefundFlowData,
    flow_request: RefundSyncData,
    flow_response: RefundsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let refund_id = req.request.connector_refund_id.clone();
            Ok(format!("{}/pa/refunds/{}", req.resource_common_data.connectors.airwallex.base_url, refund_id))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexAccessTokenRequest),
    curl_response: AirwallexAccessTokenResponse,
    flow_name: ServerAuthenticationToken,
    resource_common_data: MerchantAuthenticationFlowData,
    flow_request: ServerAuthenticationTokenRequestData,
    flow_response: ServerAuthenticationTokenResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<ServerAuthenticationToken, MerchantAuthenticationFlowData, ServerAuthenticationTokenRequestData, ServerAuthenticationTokenResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let auth = airwallex::AirwallexAuthType::try_from(&req.connector_config)
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(vec![
                (
                    headers::CONTENT_TYPE.to_string(),
                    "application/json".to_string().into(),
                ),
                (
                    "x-api-key".to_string(),
                    auth.api_key.expose().to_string().into(),
                ),
                (
                    "x-client-id".to_string(),
                    auth.client_id.expose().to_string().into(),
                ),
            ])
        }
        fn get_url(
            &self,
            req: &RouterDataV2<ServerAuthenticationToken, MerchantAuthenticationFlowData, ServerAuthenticationTokenRequestData, ServerAuthenticationTokenResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!("{}/authentication/login", req.resource_common_data.connectors.airwallex.base_url))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexIntentRequest),
    curl_response: AirwallexIntentResponse,
    flow_name: CreateOrder,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentCreateOrderData,
    flow_response: PaymentCreateOrderResponse,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<CreateOrder, PaymentFlowData, PaymentCreateOrderData, PaymentCreateOrderResponse>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<CreateOrder, PaymentFlowData, PaymentCreateOrderData, PaymentCreateOrderResponse>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!("{}/pa/payment_intents/create", req.resource_common_data.connectors.airwallex.base_url))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexSetupMandateRequest),
    curl_response: AirwallexSetupMandateResponse,
    flow_name: SetupMandate,
    resource_common_data: PaymentFlowData,
    flow_request: SetupMandateRequestData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // SetupMandate confirms the payment intent created by CreateOrder (auto-chained via should_do_order_create).
            let order_id = req.resource_common_data.connector_order_id
                .as_ref()
                .ok_or(IntegrationError::MissingRequiredField { field_name: "connector_order_id", context: Default::default() })?;
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexRepeatPaymentRequest),
    curl_response: AirwallexRepeatPaymentResponse,
    flow_name: RepeatPayment,
    resource_common_data: PaymentFlowData,
    flow_request: RepeatPaymentData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // Airwallex MIT requires a fresh PaymentIntent; caller must run CreateOrder
            // first and pass connector_order_id via PaymentFlowData.connector_order_id,
            // or (fallback) via connector_feature_data JSON: {"connector_order_id":"..."}.
            // The fallback is required because RecurringPaymentServiceChargeRequest (proto)
            // has no top-level `order_id` field, and its ForeignTryFrom for PaymentFlowData
            // leaves `connector_order_id = None`.
            let order_id = req
                .resource_common_data
                .connector_order_id
                .clone()
                .or_else(|| {
                    req.resource_common_data
                        .connector_feature_data
                        .as_ref()
                        .and_then(|v| v.peek().get("connector_order_id").and_then(|id| id.as_str().map(|s| s.to_string())))
                })
                .ok_or(IntegrationError::MissingRequiredField {
                    field_name: "connector_order_id",
                    context: Default::default(),
                })?;
            Ok(format!(
                "{}/pa/payment_intents/{}/confirm",
                req.resource_common_data.connectors.airwallex.base_url,
                order_id
            ))
        }
    }
);

// ===== EMPTY IMPLEMENTATIONS FOR OTHER FLOWS =====
// These will be implemented separately as needed

macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexVoidRequest),
    curl_response: AirwallexVoidResponse,
    flow_name: Void,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentVoidData,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req.resource_common_data.get_access_token()
                .change_context(IntegrationError::FailedToObtainAuthType { context: Default::default() })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            let payment_id = req.request.connector_transaction_id.clone();
            Ok(format!("{}/pa/payment_intents/{}/cancel", req.resource_common_data.connectors.airwallex.base_url, payment_id))
        }
    }
);

// Payment Void Post Capture

// ClientAuthenticationToken - Empty implementation (Airwallex doesn't support SDK session tokens)

// Payment Capture - implemented using macro above

// Refund - implemented using macro above

// Refund Sync - implemented using macro above

// Setup Mandate - implemented via macro below

// ServerAuthenticationToken - Airwallex Authentication Flow - will be implemented using macro

// Repeat Payment - implemented using macro below

// Order Create - implemented using macro above

// Session Token

// Dispute Accept

// Dispute Defend

// Submit Evidence

// Payment Token (required by PaymentTokenV2 trait)

// Access Token implementation is above - removing duplicate

// ===== AUTHENTICATION FLOW CONNECTOR INTEGRATIONS =====
// Pre Authentication

// Authentication

// Post Authentication

// ===== CONNECTOR CUSTOMER CONNECTOR INTEGRATIONS =====
// Create Connector Customer — POST /api/v1/pa/customers/create.
//
// Airwallex requires a Bearer access token (from ServerAuthenticationToken).
// CustomerServiceCreateRequest has no `state` field in the proto, so the access
// token is passed manually via `connector_feature_data` as JSON of the shape
// `{"access_token": "<token>"}`. This mirrors the existing RepeatPayment fallback
// pattern for `connector_order_id`.
macros::macro_connector_implementation!(
    connector_default_implementations: [get_content_type, get_error_response_v2],
    connector: Airwallex,
    curl_request: Json(AirwallexCustomerRequest),
    curl_response: AirwallexCustomerResponse,
    flow_name: CreateConnectorCustomer,
    resource_common_data: PaymentFlowData,
    flow_request: ConnectorCustomerData,
    flow_response: ConnectorCustomerResponse,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<CreateConnectorCustomer, PaymentFlowData, ConnectorCustomerData, ConnectorCustomerResponse>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let access_token = req
                .resource_common_data
                .get_access_token()
                .ok()
                .or_else(|| {
                    req.resource_common_data
                        .connector_feature_data
                        .as_ref()
                        .and_then(|v| {
                            v.peek()
                                .get("access_token")
                                .and_then(|tok| tok.as_str().map(|s| s.to_string()))
                        })
                })
                .ok_or(IntegrationError::FailedToObtainAuthType {
                    context: Default::default(),
                })?;
            Ok(self.build_headers(&access_token))
        }
        fn get_url(
            &self,
            req: &RouterDataV2<CreateConnectorCustomer, PaymentFlowData, ConnectorCustomerData, ConnectorCustomerResponse>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!(
                "{}/pa/customers/create",
                req.resource_common_data.connectors.airwallex.base_url
            ))
        }
    }
);

// Incremental Authorization

// ===== CONNECTOR COMMON IMPLEMENTATION =====
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> ConnectorCommon
    for Airwallex<T>
{
    fn id(&self) -> &'static str {
        "airwallex"
    }

    fn get_currency_unit(&self) -> CurrencyUnit {
        CurrencyUnit::Base
    }

    fn common_get_content_type(&self) -> &'static str {
        "application/json"
    }

    fn base_url<'a>(&self, connectors: &'a Connectors) -> &'a str {
        connectors.airwallex.base_url.as_ref()
    }

    fn get_auth_header(
        &self,
        auth_type: &ConnectorSpecificConfig,
    ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
        // Note: This method should not be used for OAuth-based connectors like Airwallex
        // Use build_payment_headers or build_refund_headers instead for OAuth flows
        // This method is only used for ServerAuthenticationToken flow
        let auth = airwallex::AirwallexAuthType::try_from(auth_type).change_context(
            IntegrationError::FailedToObtainAuthType {
                context: Default::default(),
            },
        )?;
        Ok(vec![
            (
                "x-api-key".to_string(),
                auth.api_key.expose().to_string().into(),
            ),
            (
                "x-client-id".to_string(),
                auth.client_id.expose().to_string().into(),
            ),
        ])
    }

    fn build_error_response(
        &self,
        res: Response,
        event_builder: Option<&mut events::Event>,
        _connector_config: &ConnectorSpecificConfig,
    ) -> CustomResult<ErrorResponse, ConnectorError> {
        let response: airwallex::AirwallexErrorResponse = res
            .response
            .parse_struct("AirwallexErrorResponse")
            .change_context(
                crate::utils::response_deserialization_fail(
                    res.status_code,
                "airwallex: response body did not match the expected format; confirm API version and connector documentation."),
            )?;

        with_error_response_body!(event_builder, response);
        let typed =
            macros::serialize_typed_connector_payload(&response, "typed_connector_response");

        let error_message = match response.source {
            Some(ref source) => format!("{}; {}", response.message, source),
            None => response.message.clone(),
        };

        Ok(ErrorResponse {
            status_code: res.status_code,
            code: response.code,
            message: error_message.clone(),
            reason: Some(error_message),
            attempt_status: None,
            connector_transaction_id: None,
            network_decline_code: None,
            network_advice_code: None,
            network_error_message: None,
            typed_connector_response: typed,
            raw_connector_response: None,
            raw_connector_request: None,
            typed_connector_request: None,
        })
    }
}

macros::macro_connector_flow_status_impls!(
    connector: Airwallex,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    not_implemented: [
        GetConnectorCustomer,
        ClientAuthenticationToken,
        MandateRevoke,
        ServerSessionAuthenticationToken,
        Accept,
        DefendDispute,
        SubmitEvidence,
        PaymentMethodToken,
        // `Authenticate` stays permanently: on the pinned 2024-06-14 contract there is no
        // merchant-side call between confirm and the browser return. Leaving the marker
        // unimplemented (rather than wiring an unreachable impl) keeps a future maintainer
        // from dispatching a second confirm, which would double-charge.
        Authenticate,
        IncrementalAuthorization,
    ],
    not_supported: [
        VoidPostRefund,
        VoidPC,
    ],
);
