pub mod transformers;

use std::fmt::Debug;

use common_enums::{CurrencyUnit, PaymentMethod, PaymentMethodType};

use common_utils::{
    consts::{NO_ERROR_CODE, NO_ERROR_MESSAGE},
    errors::CustomResult,
    events,
    ext_traits::ByteSliceExt,
    request::Method,
    types::StringMajorUnit,
};
use domain_types::{
    connector_flow::{
        Authorize, Capture, PSync, PaymentMethodToken, RSync, Refund, RepeatPayment, SetupMandate,
        Void,
    },
    connector_types::{
        PaymentFlowData, PaymentMethodTokenResponse, PaymentMethodTokenizationData,
        PaymentVoidData, PaymentsAuthorizeData, PaymentsCaptureData, PaymentsResponseData,
        PaymentsSyncData, RefundFlowData, RefundSyncData, RefundsData, RefundsResponseData,
        RepeatPaymentData, SetupMandateRequestData,
    },
    payment_method_data::PaymentMethodDataTypes,
    router_data::{ConnectorSpecificConfig, ErrorResponse},
    router_data_v2::RouterDataV2,
    router_response_types::Response,
    types::Connectors,
};
use error_stack::ResultExt;
use hyperswitch_masking::{ExposeInterface, Mask, Maskable};
use interfaces::{
    api::ConnectorCommon, connector_integration_v2::ConnectorIntegrationV2, connector_types,
    decode::BodyDecoding, verification::SourceVerification,
};
use serde::Serialize;
use transformers::{
    self as hipay, HipayAuthorizeResponse, HipayCaptureRequest, HipayCaptureResponse,
    HipayPSyncResponse, HipayPaymentsRequest, HipayRSyncResponse, HipayRefundRequest,
    HipayRefundResponse, HipayRepeatPaymentRequest, HipayRepeatPaymentResponse,
    HipaySetupMandateRequest, HipaySetupMandateResponse, HipayTokenRequest, HipayTokenResponse,
    HipayVoidRequest, HipayVoidResponse,
};

use super::macros;
use crate::{finalize_connector_response, types::ResponseRouterData, with_error_response_body};
/// The webhook half of `domain_types::connector_types`, aliased so the `IncomingWebhook` impl
/// below never reads as if these types came from `interfaces::connector_types` (the trait's own
/// module), which is what the bare `connector_types::` path in this file means.
use domain_types::connector_types as connector_types_webhook;
use domain_types::errors::{ConnectorError, IntegrationError, WebhookError};

pub(crate) mod headers {
    pub(crate) const CONTENT_TYPE: &str = "Content-Type";
    pub(crate) const AUTHORIZATION: &str = "Authorization";
    pub(crate) const ACCEPT: &str = "Accept";
}

pub(crate) mod constants {
    pub(crate) const JSON_CONTENT_TYPE: &str = "application/json";
    pub(crate) const FORM_URLENCODED_CONTENT_TYPE: &str = "application/x-www-form-urlencoded";
}

/// G-Payments-03 — HiPay's maintenance and V3 consultation endpoints take the transaction
/// reference as a **path segment**, so an absent or blank reference would address the
/// collection URL rather than the transaction.
/// spec:#### 2. Maintenance (Capture / Refund / Void); spec:#### 3. Transaction Lookup
pub(crate) fn non_empty_transaction_reference(
    transaction_reference: Option<String>,
) -> CustomResult<String, IntegrationError> {
    transaction_reference
        .filter(|reference| !reference.trim().is_empty())
        .ok_or_else(|| {
            error_stack::Report::new(IntegrationError::MissingConnectorTransactionID {
                context: domain_types::errors::IntegrationErrorContext {
                    suggested_action: Some(
                        "Send the transactionReference HiPay returned on the authorize call."
                            .to_string(),
                    ),
                    doc_url: None,
                    additional_context: Some(
                        "HiPay addresses a transaction by reference in the URL path; an empty                          value would request the collection endpoint."
                            .to_string(),
                    ),
                },
            })
        })
}

// Struct definition and helper functions will be generated by create_all_prerequisites! macro below

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ConnectorServiceTrait<T> for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentAuthorizeV2<T> for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentSyncV2 for Hipay<T>
{
}

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentVoidV2 for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RefundSyncV2 for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RefundV2 for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentCapture for Hipay<T>
{
}
// Mandates: HiPay has no mandate service — both markers are `POST /v1/order`.
// spec:### Mandates (M2, M4)
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::SetupMandateV2<T> for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::RepeatPaymentV2<T> for Hipay<T>
{
}
macros::macro_connector_payout_implementation!(
    connector: Hipay,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize]
);
/// The header HiPay carries the notification signature in (`HTTP_X_ALLOPASS_SIGNATURE` in PHP).
/// HTTP header names are case-insensitive and the gRPC caller forwards whatever casing the
/// notification arrived with, so the lookup below folds case rather than matching this literal.
/// spec:### Webhook Authentication & Signature Verification
pub(crate) const HIPAY_WEBHOOK_SIGNATURE_HEADER: &str = "x-allopass-signature";

/// The notification signature, case-insensitively by header name and lowercased for comparison.
///
/// Returns `None` for an absent or blank header, a non-hex value, or a digest whose length is not
/// one of HiPay's three configurable algorithms — every one of which is a fail-closed refusal in
/// [`verify_webhook_source`] (G-IncomingWebhook-01 / G-IncomingWebhook-02). The value itself is
/// never logged.
fn hipay_signature_hex(request: &connector_types_webhook::RequestDetails) -> Option<String> {
    let received = request
        .headers
        .iter()
        .find(|(name, _)| name.eq_ignore_ascii_case(HIPAY_WEBHOOK_SIGNATURE_HEADER))
        .map(|(_, value)| value.trim().to_ascii_lowercase())?;
    if received.is_empty() || !received.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    Some(received)
}

/// `HASH(raw POST body ‖ secret passphrase)` as lowercase hex, with the algorithm selected from
/// the length of the digest HiPay sent.
///
/// HiPay's back office lets the merchant pick SHA-256 (the documented default), SHA-1 or SHA-512
/// and exposes **no API to discover which is in force**, so the algorithm cannot be a constant and
/// cannot be configured without a new credential field (UD-02 rejected that). The received digest
/// length is the only deterministic signal: 40 hex characters is SHA-1, 64 is SHA-256, 128 is
/// SHA-512. Anything else returns `None`, which is a refusal — never a guess and never a pass.
///
/// `common_utils::crypto` provides the SHA-256 and SHA-512 digests; it has no SHA-1, so that one
/// leg calls the same `ring` primitive `common_utils::crypto` itself wraps rather than
/// hand-rolling a hash.
/// spec:## 10. Signature / MAC (HMAC) rules #### A. Server-to-server notifications (webhooks)
fn hipay_expected_signature_hex(preimage: &[u8], received_hex_len: usize) -> Option<String> {
    use common_utils::crypto::{GenerateDigest, Sha256, Sha512};
    let digest = match received_hex_len {
        40 => ring::digest::digest(&ring::digest::SHA1_FOR_LEGACY_USE_ONLY, preimage)
            .as_ref()
            .to_vec(),
        64 => Sha256.generate_digest(preimage).ok()?,
        128 => Sha512.generate_digest(preimage).ok()?,
        _ => return None,
    };
    Some(hex::encode(digest))
}

/// Compare two digests without an early exit on the first differing byte.
///
/// Both operands here are lowercase hex of the same length, so this folds every byte before it
/// answers. It is a byte comparison, not a hash: the digests themselves come from
/// `common_utils::crypto` / `ring`. `ring::constant_time::verify_slices_are_equal` is deprecated
/// in the pinned `ring` and fails `-D warnings`, and the workspace has no `subtle` dependency.
fn fixed_time_eq(left: &[u8], right: &[u8]) -> bool {
    left.len() == right.len()
        && left
            .iter()
            .zip(right.iter())
            .fold(0u8, |acc, (l, r)| acc | (l ^ r))
            == 0
}

/// Parse the raw notification bytes as HiPay's XML notification.
///
/// `quick_xml::de` deserializes the document element into the struct without matching its name,
/// which is what makes the undocumented root element a non-problem. Every failure is a checked
/// error: this parser reads untrusted, externally supplied bytes, so nothing here may panic. The
/// raw body is deliberately absent from the error context — it carries a masked PAN, a cardholder
/// name and a customer email.
/// spec:### IncomingWebhook > DOCUMENTATION GAP — Content-Type and XML root
fn hipay_notification_from_body(
    body: &[u8],
) -> Result<hipay::HipayWebhookNotification, error_stack::Report<WebhookError>> {
    use common_utils::ext_traits::XmlExt;
    let document = std::str::from_utf8(body)
        .map_err(|_| error_stack::report!(WebhookError::WebhookBodyDecodingFailed))
        .attach_printable(
            "HiPay notification body is not valid UTF-8; HiPay POSTs an XML document to the \
             merchant notify_url",
        )?;
    document
        .parse_xml::<hipay::HipayWebhookNotification>()
        .map_err(|error| {
            error_stack::report!(WebhookError::WebhookBodyDecodingFailed).attach_printable(format!(
                "Failed to parse the HiPay XML notification ({error}); `state`, `status` and \
                 `transaction_reference` are required elements. The body is not reproduced here \
                 because it carries card and personal data."
            ))
        })
}

/// The transaction reference a notification is keyed on.
///
/// This is `transaction_reference`, the value Authorize returned as `connector_transaction_id` —
/// **not** `order[id]`, which is the merchant's own `orderid` and would resolve against no stored
/// payment. A blank reference is refused rather than passed on as an empty string.
/// spec:### IncomingWebhook (Phase 1); hs:crates/hyperswitch_connectors/src/connectors/hipay/transformers.rs:186
fn hipay_webhook_reference(
    notification: &hipay::HipayWebhookNotification,
) -> Result<String, error_stack::Report<WebhookError>> {
    notification
        .non_empty_transaction_reference()
        .map(str::to_owned)
        .ok_or_else(|| {
            error_stack::report!(WebhookError::WebhookReferenceIdNotFound).attach_printable(
                "HiPay notification carries a blank `transaction_reference`; it is the only \
                 element that resolves the notification to a stored payment",
            )
        })
}

/// `(error_code, error_message, error_reason)` for a notification whose event type is a failure.
///
/// The decline detail comes from the `reason` object through the shared `40xxxxx`-band rule, so
/// the notification path reports the acquirer / issuer code exactly as the synchronous paths do.
/// A failure with no `reason` object still reports an explicit code and message rather than an
/// empty string (INV-07 / INV-17): `WebhookDetailsResponse` and `RefundWebhookDetailsResponse`
/// carry no `network_decline_code` / `network_error_message` pair, so `error_code` and
/// `error_message` are where those values land.
/// spec:### Transaction-level decline detail (reason object); spec:## 9. Error / decline reason codes
fn hipay_webhook_error_fields(
    notification: &hipay::HipayWebhookNotification,
    is_failure: bool,
) -> (Option<String>, Option<String>, Option<String>) {
    if !is_failure {
        return (None, None, None);
    }
    let (network_decline_code, network_error_message) = notification.network_fields();
    let message = notification
        .message
        .as_ref()
        .map(|message| message.trim().to_owned())
        .filter(|message| !message.is_empty());
    (
        Some(network_decline_code.unwrap_or_else(|| NO_ERROR_CODE.to_string())),
        Some(
            network_error_message
                .or_else(|| message.clone())
                .unwrap_or_else(|| NO_ERROR_MESSAGE.to_string()),
        ),
        message,
    )
}

/// HiPay server-to-server notifications.
///
/// Not a `ConnectorIntegrationV2` flow: no `connector_flow` marker, no macro. Two RPCs, two
/// phases — `EventService.ParseEvent` is stateless (`get_event_type` +
/// `get_webhook_event_reference`) and `EventService.HandleEvent` is the one that sees secrets
/// (`verify_webhook_source`, then `process_*_webhook`).
/// spec:### IncomingWebhook
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::IncomingWebhook for Hipay<T>
{
    /// **G-IncomingWebhook-01 / G-IncomingWebhook-02 — fail closed.**
    ///
    /// HiPay's only inbound authentication is `x-allopass-signature` =
    /// `HASH(raw POST body ‖ secret passphrase)`. The preimage is order-sensitive and is taken
    /// over the **raw** bytes: nothing is decoded, re-serialised or normalised first.
    ///
    /// `Ok(false)` — never `Ok(true)`, never an error that a caller might read as "unverifiable,
    /// carry on" — is returned when the header is absent, blank or not hex; when no webhook
    /// secret reached the request; or when the digest length is not one of HiPay's three
    /// configurable algorithms. Nothing about the body, the signature or the passphrase is logged.
    ///
    /// The redirect-page `hash` parameter is a **different** scheme (a hash over alphabetically
    /// sorted parameters) and is deliberately not reachable from here.
    /// spec:## 10. Signature / MAC (HMAC) rules #### A; spec:### Webhook Authentication & Signature Verification
    fn verify_webhook_source(
        &self,
        request: connector_types_webhook::RequestDetails,
        connector_webhook_secret: Option<connector_types_webhook::ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
    ) -> Result<bool, error_stack::Report<WebhookError>> {
        // G-IncomingWebhook-01a — no passphrase, no verification.
        let Some(secrets) = connector_webhook_secret.filter(|s| !s.secret.is_empty()) else {
            tracing::warn!(
                target: "hipay_webhook",
                "HiPay notification rejected: no webhook secret reached verify_webhook_source. \
                 The back-office notification passphrase (TPP > Integration > Security Settings) \
                 must be supplied as WebhookSecrets.secret on EventService.HandleEvent."
            );
            return Ok(false);
        };

        // G-IncomingWebhook-01b — no signature header, no verification.
        let Some(received) = hipay_signature_hex(&request) else {
            tracing::warn!(
                target: "hipay_webhook",
                header = HIPAY_WEBHOOK_SIGNATURE_HEADER,
                "HiPay notification rejected: the signature header is absent, blank or not \
                 hexadecimal. It is the only carrier of the notification signature."
            );
            return Ok(false);
        };

        let mut preimage = Vec::with_capacity(request.body.len() + secrets.secret.len());
        preimage.extend_from_slice(&request.body);
        preimage.extend_from_slice(&secrets.secret);

        // G-IncomingWebhook-02 — an unrecognised digest length means the algorithm cannot be
        // selected, so the digest cannot be reproduced and the notification cannot be trusted.
        let Some(expected) = hipay_expected_signature_hex(&preimage, received.len()) else {
            tracing::warn!(
                target: "hipay_webhook",
                digest_hex_length = received.len(),
                "HiPay notification rejected: the signature digest length matches none of the \
                 three algorithms HiPay's back office can be configured with (40 = SHA-1, \
                 64 = SHA-256, 128 = SHA-512)."
            );
            return Ok(false);
        };

        Ok(fixed_time_eq(expected.as_bytes(), received.as_bytes()))
    }

    /// A minimal, structurally valid HiPay notification, for the field probe.
    fn sample_webhook_body(&self) -> &'static [u8] {
        br#"<?xml version="1.0" encoding="UTF-8"?><operation><state>completed</state><status>118</status><message>Captured</message><transaction_reference>800000000001</transaction_reference><currency>EUR</currency><captured_amount>1.00</captured_amount><order><id>probe_order_001</id></order></operation>"#
    }

    /// **Phase 1 — `EventService.ParseEvent`.** Stateless: the event class is decided by the
    /// numeric `status` alone, because HiPay has no event-type field and **no separate dispute
    /// webhook** — a chargeback is an ordinary transaction notification carrying 180 / 181 / 134.
    /// spec:### IncomingWebhook (Phase 1); spec:## Status Mappings ### Notified statuses
    fn get_event_type(
        &self,
        request: connector_types_webhook::RequestDetails,
    ) -> Result<connector_types_webhook::EventType, error_stack::Report<WebhookError>> {
        let notification = hipay_notification_from_body(&request.body)?;
        Ok(hipay::hipay_webhook_event_type(&notification))
    }

    /// **Phase 1 — `EventService.ParseEvent`.** The event reference is `transaction_reference`,
    /// the value the payment side stores as `connector_transaction_id`. `order[id]` is the
    /// merchant's own `orderid` and travels as the merchant-side reference, never as the event
    /// reference — keying on it is the trap the scout recorded for this connector.
    /// spec:### IncomingWebhook (Phase 1); spec:### Refunds > DOCUMENTATION GAP — no refund-level identifier
    fn get_webhook_event_reference(
        &self,
        request: connector_types_webhook::RequestDetails,
    ) -> Result<
        Option<connector_types_webhook::WebhookResourceReference>,
        error_stack::Report<WebhookError>,
    > {
        let notification = hipay_notification_from_body(&request.body)?;
        let reference = hipay_webhook_reference(&notification)?;
        let merchant_reference = notification.order_reference();

        Ok(Some(match notification.status.event_class() {
            hipay::HipayWebhookEventClass::Payment => {
                connector_types_webhook::WebhookResourceReference::Payment(
                    connector_types_webhook::PaymentWebhookReference {
                        connector_transaction_id: Some(reference),
                        merchant_transaction_id: merchant_reference,
                    },
                )
            }
            // HiPay issues no refund-level identifier: the refund is addressed by the ORIGINAL
            // transaction reference, and `operation[id]` — the merchant `operation_id` echoed
            // back — is the only thing that says which refund this is.
            hipay::HipayWebhookEventClass::Refund => {
                connector_types_webhook::WebhookResourceReference::Refund(
                    connector_types_webhook::RefundWebhookReference {
                        connector_refund_id: Some(reference.clone()),
                        merchant_refund_id: notification.operation_reference(),
                        connector_transaction_id: Some(reference),
                        merchant_transaction_id: merchant_reference,
                    },
                )
            }
            // There is no HiPay dispute id, so the disputed payment's reference identifies the
            // case on both sides.
            hipay::HipayWebhookEventClass::Dispute => {
                connector_types_webhook::WebhookResourceReference::Dispute(
                    connector_types_webhook::DisputeWebhookReference {
                        connector_dispute_id: Some(reference.clone()),
                        connector_transaction_id: Some(reference),
                    },
                )
            }
        }))
    }

    /// **Phase 2 Step B — payment notification.** The status is mapped through the *same*
    /// `HipayPaymentStatus` -> `AttemptStatus` table the Authorize, Capture, Void and PSync paths
    /// use, so no status can mean one thing on the sync path and another here.
    /// spec:### IncomingWebhook (Phase 2 Step B); spec:## Status Mappings ### Notified statuses
    fn process_payment_webhook(
        &self,
        request: connector_types_webhook::RequestDetails,
        _connector_webhook_secret: Option<connector_types_webhook::ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
        _event_context: Option<connector_types_webhook::EventContext>,
    ) -> Result<connector_types_webhook::WebhookDetailsResponse, error_stack::Report<WebhookError>>
    {
        let notification = hipay_notification_from_body(&request.body)?;
        let reference = hipay_webhook_reference(&notification)?;
        let status = common_enums::AttemptStatus::from(notification.status.payment_status());
        let is_failure = matches!(
            hipay::hipay_webhook_event_type(&notification),
            connector_types_webhook::EventType::PaymentIntentFailure
                | connector_types_webhook::EventType::PaymentIntentAuthorizationFailure
                | connector_types_webhook::EventType::PaymentIntentCaptureFailure
                | connector_types_webhook::EventType::PaymentIntentCancelFailure
        );
        let (error_code, error_message, error_reason) =
            hipay_webhook_error_fields(&notification, is_failure);
        let minor_amount_captured = notification.captured_amount_minor();

        Ok(connector_types_webhook::WebhookDetailsResponse {
            resource_id: Some(
                domain_types::connector_types::ResponseId::ConnectorTransactionId(reference),
            ),
            status,
            // `order[id]` — the merchant's own reference, echoed back.
            connector_response_reference_id: notification.order_reference(),
            connector_request_reference_id: None,
            // The reusable vault token, inside a `SecretSerdeValue`, exactly as the Mandates legs
            // carry it.
            mandate_reference: notification.mandate_reference(),
            error_code,
            error_message,
            error_reason,
            // Deliberately not the raw body: the notification carries a masked PAN, a cardholder
            // name and a customer email, and this field is not masked downstream.
            raw_connector_response: None,
            status_code: 200,
            response_headers: None,
            amount_captured: minor_amount_captured.map(|amount| amount.get_amount_as_i64()),
            minor_amount_captured,
            // HiPay's scheme reference data / TLID appear only on the V3 `debitAgreement` object,
            // never on a notification.
            network_txn_id: None,
            // `payment_method[*]` -> the framework's own card-detail update.
            payment_method_update: notification.card_detail_update(),
            sender_payment_instrument_id: None,
            connector_returned_payment_method_details: None,
        })
    }

    /// **Phase 2 Step B — refund notification.** The same notification shape, read through the
    /// `HipayRefundStatus` table the Refund and RSync paths use (124/125/126/165 plus the RDR
    /// refunds 182/183). `operation[id]` is the only correlator for an individual partial refund,
    /// because HiPay issues no refund-level identifier.
    /// spec:### IncomingWebhook (Refund webhooks); spec:### Refunds > DOCUMENTATION GAP
    fn process_refund_webhook(
        &self,
        request: connector_types_webhook::RequestDetails,
        _connector_webhook_secret: Option<connector_types_webhook::ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
    ) -> Result<
        connector_types_webhook::RefundWebhookDetailsResponse,
        error_stack::Report<WebhookError>,
    > {
        let notification = hipay_notification_from_body(&request.body)?;
        let reference = hipay_webhook_reference(&notification)?;
        let status = common_enums::RefundStatus::from(notification.status.refund_status());
        let (error_code, error_message, _) = hipay_webhook_error_fields(
            &notification,
            matches!(status, common_enums::RefundStatus::Failure),
        );

        Ok(connector_types_webhook::RefundWebhookDetailsResponse {
            // The ORIGINAL transaction reference — the same value the Refund and RSync paths
            // write as `connector_refund_id` (UD-04).
            connector_refund_id: Some(reference),
            merchant_transaction_id: notification.order_reference(),
            status,
            // The merchant `operation_id` HiPay echoes back, when the maintenance call sent one.
            connector_response_reference_id: notification.operation_reference(),
            error_code,
            error_message,
            raw_connector_response: None,
            status_code: 200,
            response_headers: None,
        })
    }

    /// **Phase 2 Step B — chargeback notification.** HiPay has no separate dispute webhook: 181
    /// Chargeback and 180 Partially Chargeback arrive as ordinary transaction notifications and
    /// open a dispute, 134 Dispute Lost closes it against the merchant. There is **no "dispute
    /// won" status in HiPay's vocabulary**, and none is invented here.
    /// spec:### IncomingWebhook (Dispute webhooks); spec:### IncomingWebhook > DOCUMENTATION GAP — dispute lifecycle
    fn process_dispute_webhook(
        &self,
        request: connector_types_webhook::RequestDetails,
        _connector_webhook_secret: Option<connector_types_webhook::ConnectorWebhookSecrets>,
        _connector_account_details: Option<ConnectorSpecificConfig>,
    ) -> Result<
        connector_types_webhook::DisputeWebhookDetailsResponse,
        error_stack::Report<WebhookError>,
    > {
        let notification = hipay_notification_from_body(&request.body)?;
        let reference = hipay_webhook_reference(&notification)?;
        let (minor_amount, currency) = notification.disputed_amount_minor().ok_or_else(|| {
            error_stack::report!(WebhookError::WebhookProcessingFailed).attach_printable(
                "HiPay chargeback notification carries no amount/currency pair; a dispute is \
                 reported with the amount that moved, so `currency` plus one of \
                 `refunded_amount` / `captured_amount` / `authorized_amount` is required",
            )
        })?;
        let (network_decline_code, _) = notification.network_fields();

        Ok(connector_types_webhook::DisputeWebhookDetailsResponse {
            amount: domain_types::utils::convert_amount_for_webhook(
                &common_utils::types::StringMinorUnitForConnector,
                minor_amount,
                currency,
            )?,
            currency,
            // HiPay issues no dispute identifier — the disputed payment's reference is the only
            // handle the notification carries.
            dispute_id: reference,
            status: common_enums::DisputeStatus::from(notification.status.dispute_status()),
            stage: common_enums::DisputeStage::Dispute,
            connector_response_reference_id: notification.order_reference(),
            dispute_message: notification
                .message
                .as_ref()
                .map(|message| message.trim().to_owned())
                .filter(|message| !message.is_empty()),
            raw_connector_response: None,
            status_code: 200,
            response_headers: None,
            connector_reason_code: network_decline_code,
        })
    }
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::VerifyRedirectResponse for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> SourceVerification
    for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> BodyDecoding
    for Hipay<T>
{
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::ValidationTrait for Hipay<T>
{
    fn should_do_payment_method_token(
        &self,
        _payment_method: PaymentMethod,
        _payment_method_type: Option<PaymentMethodType>,
        _is_wallet_decrypted_network_token: bool,
    ) -> bool {
        true
    }
}
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    connector_types::PaymentTokenV2<T> for Hipay<T>
{
}

// Authentication trait implementations

// Create connector struct with all flow prerequisites
macros::create_all_prerequisites!(
    connector_name: Hipay,
    generic_type: T,
    api: [
        (
            flow: PaymentMethodToken,
            request_body: HipayTokenRequest<T>,
            response_body: HipayTokenResponse,
            router_data: RouterDataV2<PaymentMethodToken, PaymentFlowData, PaymentMethodTokenizationData<T>, PaymentMethodTokenResponse>,
        ),
        (
            flow: Authorize,
            request_body: HipayPaymentsRequest,
            response_body: HipayAuthorizeResponse,
            router_data: RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ),
        (
            flow: PSync,
            response_body: HipayPSyncResponse,
            router_data: RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ),
        (
            flow: Capture,
            request_body: HipayCaptureRequest,
            response_body: HipayCaptureResponse,
            router_data: RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ),
        (
            flow: Void,
            request_body: HipayVoidRequest,
            response_body: HipayVoidResponse,
            router_data: RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ),
        (
            flow: Refund,
            request_body: HipayRefundRequest,
            response_body: HipayRefundResponse,
            router_data: RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ),
        (
            flow: SetupMandate,
            request_body: HipaySetupMandateRequest,
            response_body: HipaySetupMandateResponse,
            router_data: RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ),
        (
            flow: RepeatPayment,
            request_body: HipayRepeatPaymentRequest,
            response_body: HipayRepeatPaymentResponse,
            router_data: RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        )
    ],
    amount_converters: [
        amount_converter: StringMajorUnit
    ],
    member_functions: {
        pub fn get_tokenization_base_url<F, Req, Res>(
            &self,
            req: &RouterDataV2<F, PaymentFlowData, Req, Res>,
        ) -> CustomResult<String, IntegrationError> {
            // Use secondary_base_url from config for tokenization endpoint
            req.resource_common_data
                .connectors
                .hipay
                .secondary_base_url
                .as_ref()
                .cloned()
                .ok_or_else(|| error_stack::Report::new(IntegrationError::InvalidConnectorConfig {
                    config: "secondary_base_url",
                    context: domain_types::errors::IntegrationErrorContext {
                        suggested_action: Some(
                            "Set hipay.secondary_base_url in config/{development,sandbox,production}.toml."
                                .to_string(),
                        ),
                        doc_url: None,
                        additional_context: Some(
                            "HiPay's Secure Vault tokenization endpoint lives on its own host."
                                .to_string(),
                        ),
                    },
                }))
        }

        pub fn get_sync_base_url<F, Req, Res>(
            &self,
            req: &RouterDataV2<F, PaymentFlowData, Req, Res>,
        ) -> CustomResult<String, IntegrationError> {
            // Use third_base_url from config for sync operations (PSync)
            req.resource_common_data
                .connectors
                .hipay
                .third_base_url
                .as_ref()
                .cloned()
                .ok_or_else(|| error_stack::Report::new(IntegrationError::InvalidConnectorConfig {
                    config: "third_base_url",
                    context: domain_types::errors::IntegrationErrorContext {
                        suggested_action: Some(
                            "Set hipay.third_base_url in config/{development,sandbox,production}.toml."
                                .to_string(),
                        ),
                        doc_url: None,
                        additional_context: Some(
                            "HiPay's V3 transaction consultation host lives on its own host."
                                .to_string(),
                        ),
                    },
                }))
        }

        pub fn get_refund_sync_base_url<Req, Res>(
            &self,
            req: &RouterDataV2<RSync, RefundFlowData, Req, Res>,
        ) -> CustomResult<String, IntegrationError> {
            // Use third_base_url from config for refund sync operations
            req.resource_common_data
                .connectors
                .hipay
                .third_base_url
                .as_ref()
                .cloned()
                .ok_or_else(|| error_stack::Report::new(IntegrationError::InvalidConnectorConfig {
                    config: "third_base_url",
                    context: domain_types::errors::IntegrationErrorContext {
                        suggested_action: Some(
                            "Set hipay.third_base_url in config/{development,sandbox,production}.toml."
                                .to_string(),
                        ),
                        doc_url: None,
                        additional_context: Some(
                            "HiPay's V3 transaction consultation host lives on its own host."
                                .to_string(),
                        ),
                    },
                }))
        }

        pub fn build_headers<F, FCD, Req, Res>(
            &self,
            req: &RouterDataV2<F, FCD, Req, Res>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError>
        where
            Self: ConnectorIntegrationV2<F, FCD, Req, Res>,
        {
            let mut header = vec![
                (
                    headers::CONTENT_TYPE.to_string(),
                    self.common_get_content_type().to_string().into(),
                ),
                (
                    headers::ACCEPT.to_string(),
                    constants::JSON_CONTENT_TYPE.to_string().into(),
                ),
            ];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        pub fn connector_base_url_payments<'a, F, Req, Res>(
            &self,
            req: &'a RouterDataV2<F, PaymentFlowData, Req, Res>,
        ) -> &'a str {
            &req.resource_common_data.connectors.hipay.base_url
        }

        /// `build_error_response` is shared by every flow, so the flow-specific attempt status
        /// is applied by the flow that owns it rather than hardcoded once for all of them.
        pub fn error_response_with_status(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
            attempt_status: domain_types::router_data::FlowStatus,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            let mut error_response = self.build_error_response(res, event_builder, connector_config)?;
            error_response.attempt_status = Some(attempt_status);
            Ok(error_response)
        }

        pub fn connector_base_url_refunds<'a, F, Req, Res>(
            &self,
            req: &'a RouterDataV2<F, RefundFlowData, Req, Res>,
        ) -> &'a str {
            &req.resource_common_data.connectors.hipay.base_url
        }
    }
);

impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize> ConnectorCommon
    for Hipay<T>
{
    fn id(&self) -> &'static str {
        "hipay"
    }

    fn get_currency_unit(&self) -> CurrencyUnit {
        CurrencyUnit::Base
    }

    fn base_url<'a>(&self, connectors: &'a Connectors) -> &'a str {
        connectors.hipay.base_url.as_ref()
    }

    fn get_auth_header(
        &self,
        auth_type: &ConnectorSpecificConfig,
    ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
        let auth = hipay::HipayAuthType::try_from(auth_type).change_context(
            IntegrationError::FailedToObtainAuthType {
                context: domain_types::errors::IntegrationErrorContext {
                    suggested_action: Some(
                        "Configure the HiPay connector with its API username (api_key) and \
                         password (api_secret)."
                            .to_string(),
                    ),
                    doc_url: None,
                    additional_context: Some(
                        "HiPay authenticates every call with HTTP Basic credentials from the \
                         merchant's back office."
                            .to_string(),
                    ),
                },
            },
        )?;

        // Use HTTP Basic Auth for HiPay
        use base64::Engine;
        let credentials = format!("{}:{}", auth.api_key.expose(), auth.api_secret.expose());
        let base64_credentials = base64::engine::general_purpose::STANDARD.encode(credentials);
        let auth_value = format!("Basic {base64_credentials}");

        // `.into_masked()` (not a bare `.into()`): the event serialiser in
        // `crates/common/common_utils/src/events.rs` prints `Maskable::Normal` verbatim and only
        // redacts `Maskable::Masked`, so a bare `.into()` here writes
        // `base64(api_key:api_secret)` in clear into every request log line and echoes it in
        // `rawConnectorRequest` on the API response.
        Ok(vec![(
            headers::AUTHORIZATION.to_string(),
            auth_value.into_masked(),
        )])
    }

    fn build_error_response(
        &self,
        res: Response,
        event_builder: Option<&mut events::Event>,
        _connector_config: &ConnectorSpecificConfig,
    ) -> CustomResult<ErrorResponse, ConnectorError> {
        let error_response: hipay::HipayErrorResponse = res
            .response
            .parse_struct("HipayErrorResponse")
            .unwrap_or_else(|_| {
                let raw_response = String::from_utf8_lossy(&res.response);
                let message = if raw_response.trim().is_empty() {
                    "Unknown error from HiPay".to_string()
                } else if raw_response.len() > 200 {
                    format!("{}...", &raw_response[..200])
                } else {
                    raw_response.to_string()
                };

                hipay::HipayErrorResponse {
                    code: hipay::HipayErrorCode::Numeric(i64::from(res.status_code)),
                    message,
                    description: None,
                }
            });

        with_error_response_body!(event_builder, error_response);

        let typed =
            macros::serialize_typed_connector_payload(&error_response, "typed_connector_response");
        Ok(ErrorResponse {
            status_code: res.status_code,
            code: error_response.code.to_string(),
            message: error_response.message.clone(),
            // `description` carries HiPay's actionable detail; fall back to `message` only when
            // the envelope did not include one.
            reason: error_response
                .description
                .clone()
                .or_else(|| Some(error_response.message.clone())),
            // Left unset on the transport-error path: the flow-specific `handle_response_v2`
            // conversions own the attempt status, and a 4xx/5xx here says nothing about the
            // attempt beyond what the caller already knows.
            attempt_status: None,
            connector_transaction_id: None,
            network_decline_code: None,
            network_advice_code: None,
            network_error_message: None,
            typed_connector_response: typed,
            raw_connector_response: None,
            raw_connector_request: None,
            typed_connector_request: None,
        })
    }
}

// ========================================================================================
// MACRO-BASED FLOW IMPLEMENTATIONS
// ========================================================================================

// PaymentMethodToken flow - application/x-www-form-urlencoded, uses secondary_base_url.
// UD-01: the Secure Vault answers the equivalent multipart POST with an Apache-level 400 page
// ("Your browser sent a request that this server could not understand"), i.e. it is rejected
// before HiPay's application layer, while a form-urlencoded POST to the same URL with the same
// credentials returns 201 with the Token object.
macros::macro_connector_implementation!(
    connector_default_implementations: [get_error_response_v2],
    connector: Hipay,
    curl_request: FormUrlEncoded(HipayTokenRequest<T>),
    curl_response: HipayTokenResponse,
    flow_name: PaymentMethodToken,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentMethodTokenizationData<T>,
    flow_response: PaymentMethodTokenResponse,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PaymentMethodToken, PaymentFlowData, PaymentMethodTokenizationData<T>, PaymentMethodTokenResponse>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            // The vault needs an explicit form-urlencoded Content-Type, and an explicit Accept:
            // application/json — without one it answers XML.
            let mut header = vec![
                (
                    headers::CONTENT_TYPE.to_string(),
                    constants::FORM_URLENCODED_CONTENT_TYPE.to_string().into(),
                ),
                (
                    headers::ACCEPT.to_string(),
                    constants::JSON_CONTENT_TYPE.to_string().into(),
                ),
            ];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<PaymentMethodToken, PaymentFlowData, PaymentMethodTokenizationData<T>, PaymentMethodTokenResponse>,
        ) -> CustomResult<String, IntegrationError> {
            let base_url = self.get_tokenization_base_url(req)?;
            Ok(format!("{}/create", base_url.trim_end_matches('/')))
        }
    }
);

// Authorize flow - FormData (multipart/form-data), uses base_url
macros::macro_connector_implementation!(
    connector_default_implementations: [],
    connector: Hipay,
    curl_request: FormData(HipayPaymentsRequest),
    curl_response: HipayAuthorizeResponse,
    flow_name: Authorize,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsAuthorizeData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            // Do NOT set Content-Type header manually for FormData - reqwest sets it with boundary
            let mut header = vec![(
                headers::ACCEPT.to_string(),
                constants::JSON_CONTENT_TYPE.to_string().into(),
            )];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!(
                "{}/v1/order",
                self.connector_base_url_payments(req).trim_end_matches('/')
            ))
        }

        fn get_error_response_v2(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            // A transport-level rejection of the order call leaves the attempt failed.
            self.error_response_with_status(
                res,
                event_builder,
                connector_config,
                domain_types::router_data::FlowStatus::Payment(common_enums::AttemptStatus::Failure),
            )
        }
    }
);

// PSync flow - GET, no request body, JSON response, uses third_base_url
macros::macro_connector_implementation!(
    connector_default_implementations: [get_error_response_v2],
    connector: Hipay,
    curl_response: HipayPSyncResponse,
    flow_name: PSync,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsSyncData,
    flow_response: PaymentsResponseData,
    http_method: Get,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            self.build_headers(req)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<PSync, PaymentFlowData, PaymentsSyncData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // G-Payments-03: the transaction reference is a path segment on the V3
            // consultation URL too; an empty value would request the collection.
            let transaction_reference = non_empty_transaction_reference(
                req.request
                    .connector_transaction_id
                    .get_connector_transaction_id()
                    .ok(),
            )?;

            let base_url = self.get_sync_base_url(req)?;
            Ok(format!(
                "{}/v3/transaction/{}",
                base_url.trim_end_matches('/'),
                transaction_reference
            ))
        }
    }
);

// Capture flow - FormData (multipart/form-data), uses base_url
macros::macro_connector_implementation!(
    connector_default_implementations: [],
    connector: Hipay,
    curl_request: FormData(HipayCaptureRequest),
    curl_response: HipayCaptureResponse,
    flow_name: Capture,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentsCaptureData,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            // Do NOT set Content-Type header manually for FormData - reqwest sets it with boundary
            let mut header = vec![(
                headers::ACCEPT.to_string(),
                constants::JSON_CONTENT_TYPE.to_string().into(),
            )];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // G-Payments-03: the transaction reference is a path segment, so an empty value
            // would address the collection URL instead of the transaction.
            let transaction_reference = non_empty_transaction_reference(
                req.request
                    .connector_transaction_id
                    .get_connector_transaction_id()
                    .ok(),
            )?;

            Ok(format!(
                "{}/v1/maintenance/transaction/{}",
                self.connector_base_url_payments(req).trim_end_matches('/'),
                transaction_reference
            ))
        }

        fn get_error_response_v2(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            // A transport-level rejection of the maintenance call is a failed capture, not a
            // failed payment.
            self.error_response_with_status(
                res,
                event_builder,
                connector_config,
                domain_types::router_data::FlowStatus::Payment(common_enums::AttemptStatus::CaptureFailed),
            )
        }
    }
);

// Void flow - FormData (multipart/form-data), uses base_url
macros::macro_connector_implementation!(
    connector_default_implementations: [],
    connector: Hipay,
    curl_request: FormData(HipayVoidRequest),
    curl_response: HipayVoidResponse,
    flow_name: Void,
    resource_common_data: PaymentFlowData,
    flow_request: PaymentVoidData,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            // Do NOT set Content-Type header manually for FormData - reqwest sets it with boundary
            let mut header = vec![(
                headers::ACCEPT.to_string(),
                constants::JSON_CONTENT_TYPE.to_string().into(),
            )];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<Void, PaymentFlowData, PaymentVoidData, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // G-Void-01: HiPay's maintenance endpoint takes the transaction reference as a
            // path segment, so an empty value would POST to the collection URL instead of the
            // transaction. spec:### Void; spec:#### 2. Maintenance (Capture / Refund / Void)
            let transaction_reference = non_empty_transaction_reference(Some(
                req.request.connector_transaction_id.clone(),
            ))?;

            Ok(format!(
                "{}/v1/maintenance/transaction/{}",
                self.connector_base_url_payments(req).trim_end_matches('/'),
                transaction_reference
            ))
        }

        fn get_error_response_v2(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            // P-Void-03: HiPay's own error envelope is parsed on the Void HTTP-error path too
            // (HS defines no get_error_response on Void at all, so the envelope is lost there),
            // and a transport-level rejection of the cancel is a failed void — never a failed
            // payment. spec:### Void > Hyperswitch reference — defect to avoid
            self.error_response_with_status(
                res,
                event_builder,
                connector_config,
                domain_types::router_data::FlowStatus::Payment(common_enums::AttemptStatus::VoidFailed),
            )
        }
    }
);

// Refund flow - FormData (multipart/form-data), uses base_url
macros::macro_connector_implementation!(
    connector_default_implementations: [],
    connector: Hipay,
    curl_request: FormData(HipayRefundRequest),
    curl_response: HipayRefundResponse,
    flow_name: Refund,
    resource_common_data: RefundFlowData,
    flow_request: RefundsData,
    flow_response: RefundsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            // Do NOT set Content-Type header manually for FormData - reqwest sets it with boundary
            let mut header = vec![(
                headers::ACCEPT.to_string(),
                constants::JSON_CONTENT_TYPE.to_string().into(),
            )];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            // G-Payments-03: the transaction reference is a path segment, so a blank value would
            // POST the refund to the collection URL instead of the transaction. A refund is
            // addressed by the ORIGINAL transaction reference — HiPay has no refund-level id.
            // spec:### Refunds; spec:#### 2. Maintenance (Capture / Refund / Void)
            let transaction_reference = non_empty_transaction_reference(Some(
                req.request.connector_transaction_id.clone(),
            ))?;

            Ok(format!(
                "{}/v1/maintenance/transaction/{}",
                self.connector_base_url_refunds(req).trim_end_matches('/'),
                transaction_reference
            ))
        }

        fn get_error_response_v2(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            // P-Refunds-03: HiPay's own error envelope is parsed on the refund HTTP-error path
            // too, and the flow status it carries is refund-specific — a rejected maintenance
            // call is a failed refund, never a failed payment.
            // spec:## HTTP Codes and Errors ### Error Response Body Format
            self.error_response_with_status(
                res,
                event_builder,
                connector_config,
                domain_types::router_data::FlowStatus::Refund(common_enums::RefundStatus::Failure),
            )
        }
    }
);

// RSync flow - Manual implementation with custom handle_response_v2
// Uses JSON deserialization from v3 API (same as PSync)
impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
    ConnectorIntegrationV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>
    for Hipay<T>
{
    fn get_http_method(&self) -> Method {
        Method::Get
    }

    fn get_headers(
        &self,
        req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
    ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
        let mut header = vec![(
            headers::CONTENT_TYPE.to_string(),
            self.common_get_content_type().to_string().into(),
        )];
        let mut auth_header = self.get_auth_header(&req.connector_config)?;
        header.append(&mut auth_header);
        Ok(header)
    }

    fn get_url(
        &self,
        req: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
    ) -> CustomResult<String, IntegrationError> {
        // P-Refunds-05 / UD-04: the refund is addressed by the ORIGINAL transaction reference —
        // the value Execute wrote as `connector_refund_id`, because HiPay issues no refund-level
        // identifier. The V1 lookup endpoints are deprecated, so this is the same V3 consultation
        // PSync uses, on the third host.
        // spec:### Refunds > RSync endpoint; spec:#### 3. Transaction Lookup (PSync / RSync)
        let transaction_reference =
            non_empty_transaction_reference(Some(req.request.connector_refund_id.clone()))?;

        let base_url = self.get_refund_sync_base_url(req)?;
        Ok(format!(
            "{}/v3/transaction/{}",
            base_url.trim_end_matches('/'),
            transaction_reference
        ))
    }

    fn handle_response_v2(
        &self,
        data: &RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        event_builder: Option<&mut events::Event>,
        res: Response,
    ) -> CustomResult<
        RouterDataV2<RSync, RefundFlowData, RefundSyncData, RefundsResponseData>,
        ConnectorError,
    > {
        // HiPay RSync returns JSON from v3 API (same as PSync)
        let response: HipayRSyncResponse = res
            .response
            .parse_struct("HipayRSyncResponse")
            .change_context(crate::utils::response_handling_fail_for_connector(
                res.status_code,
                "hipay",
            ))?;

        finalize_connector_response!(event_builder, response, data, res.status_code)
    }

    fn get_error_response_v2(
        &self,
        res: Response,
        event_builder: Option<&mut events::Event>,
        connector_config: &ConnectorSpecificConfig,
    ) -> CustomResult<ErrorResponse, ConnectorError> {
        // P-Refunds-04 / TH-07: a request-level failure of the V3 consultation (bad reference,
        // service unavailable) says nothing about the refund, so it must not terminally fail one.
        // `RefundStatus::Unknown` is the unspecified variant — the caller keeps the status the
        // refund already had and syncs again. spec:#### 3. Transaction Lookup (PSync / RSync)
        self.error_response_with_status(
            res,
            event_builder,
            connector_config,
            domain_types::router_data::FlowStatus::Refund(common_enums::RefundStatus::Unknown),
        )
    }

    fn get_5xx_error_response(
        &self,
        res: Response,
        event_builder: Option<&mut events::Event>,
        connector_config: &ConnectorSpecificConfig,
    ) -> CustomResult<ErrorResponse, ConnectorError> {
        // A 5xx from the consultation host is even less of a statement about the refund.
        self.error_response_with_status(
            res,
            event_builder,
            connector_config,
            domain_types::router_data::FlowStatus::Refund(common_enums::RefundStatus::Unknown),
        )
    }
}

// SetupMandate flow — the initial card-on-file CIT. Same POST {base_url}/v1/order call and the
// same multipart form as Authorize: HiPay publishes no mandate, subscription or verification
// endpoint, and no zero-amount authorization, so the agreement is opened by a real charge marked
// eci=7 / recurring_payment=1 (UD-03).
// spec:### Mandates (M2); spec:### API Call Sequences ### Mandates (a) Step 2
macros::macro_connector_implementation!(
    connector_default_implementations: [],
    connector: Hipay,
    curl_request: FormData(HipaySetupMandateRequest),
    curl_response: HipaySetupMandateResponse,
    flow_name: SetupMandate,
    resource_common_data: PaymentFlowData,
    flow_request: SetupMandateRequestData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            // Do NOT set Content-Type manually for FormData - reqwest sets it with the boundary.
            let mut header = vec![(
                headers::ACCEPT.to_string(),
                constants::JSON_CONTENT_TYPE.to_string().into(),
            )];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<SetupMandate, PaymentFlowData, SetupMandateRequestData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!(
                "{}/v1/order",
                self.connector_base_url_payments(req).trim_end_matches('/')
            ))
        }

        fn get_error_response_v2(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            // A transport-level rejection of the CIT leaves the setup attempt failed; there is no
            // agreement and nothing to retry against.
            self.error_response_with_status(
                res,
                event_builder,
                connector_config,
                domain_types::router_data::FlowStatus::Payment(common_enums::AttemptStatus::Failure),
            )
        }
    }
);

// RepeatPayment flow — the merchant-initiated charge. Same endpoint again, distinguished by
// eci=9 plus the agreement handle (debit_agreement_id, or the multi-use cardtoken).
// spec:### Mandates (M4); spec:### API Call Sequences ### Mandates (c)
macros::macro_connector_implementation!(
    connector_default_implementations: [],
    connector: Hipay,
    curl_request: FormData(HipayRepeatPaymentRequest),
    curl_response: HipayRepeatPaymentResponse,
    flow_name: RepeatPayment,
    resource_common_data: PaymentFlowData,
    flow_request: RepeatPaymentData<T>,
    flow_response: PaymentsResponseData,
    http_method: Post,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    other_functions: {
        fn get_headers(
            &self,
            req: &RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
            let mut header = vec![(
                headers::ACCEPT.to_string(),
                constants::JSON_CONTENT_TYPE.to_string().into(),
            )];
            let mut auth_header = self.get_auth_header(&req.connector_config)?;
            header.append(&mut auth_header);
            Ok(header)
        }

        fn get_url(
            &self,
            req: &RouterDataV2<RepeatPayment, PaymentFlowData, RepeatPaymentData<T>, PaymentsResponseData>,
        ) -> CustomResult<String, IntegrationError> {
            Ok(format!(
                "{}/v1/order",
                self.connector_base_url_payments(req).trim_end_matches('/')
            ))
        }

        fn get_error_response_v2(
            &self,
            res: Response,
            event_builder: Option<&mut events::Event>,
            connector_config: &ConnectorSpecificConfig,
        ) -> CustomResult<ErrorResponse, ConnectorError> {
            // A transport-level rejection of the MIT leaves this charge failed; the agreement
            // itself is unaffected.
            self.error_response_with_status(
                res,
                event_builder,
                connector_config,
                domain_types::router_data::FlowStatus::Payment(common_enums::AttemptStatus::Failure),
            )
        }
    }
);

macros::macro_connector_flow_status_impls!(
    connector: Hipay,
    generic_type: T,
    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
    not_implemented: [
        CreateOrder,
        Accept,
    ],
    not_supported: [
        VoidPostRefund,
        IncrementalAuthorization,
        PreAuthenticate,
        VoidPC,
        ServerSessionAuthenticationToken,
        ClientAuthenticationToken,
        MandateRevoke,
        DefendDispute,
        SubmitEvidence,
        ServerAuthenticationToken,
        Authenticate,
        PostAuthenticate,
        CreateConnectorCustomer,
        GetConnectorCustomer,
    ],
);
