import fs from "node:fs";
import path from "node:path";

/**
 * On-disk state for the PR Resolver. Single JSON file, mirrors the Python
 * service's shape so the two can read each other's state if you ever run
 * them side-by-side during migration. Schema is intentionally flat and
 * documented inline — promote to SQLite later if cross-query becomes
 * useful.
 */

export type ProcessedThreadStatus = "fixed" | "failed" | "build_blocked";

export interface ProcessedThreadEntry {
  pr_number: number;
  processed_at: string;
  status: ProcessedThreadStatus;
  commit_sha?: string;
  path?: string;
  instruction_preview?: string;
  resolution_summary?: string;
  error?: string;
}

export interface BuildFailureEntry {
  branch: string;
  head_sha: string;
  failed_at: string;
  error: string;
}

/**
 * Per-PR state machine. Drives the new flow that holds local commits on the
 * worktree until the user approves them via the dashboard (or auto-mode
 * skips the wait). One row per PR currently in flight or terminal.
 */
export type PrMachineStatus =
  | "noticed"
  | "preparing"
  | "resolving"
  | "verifying"
  | "awaiting_approval"
  | "committing"
  | "pushed"
  | "rejected"
  | "failed";

export interface GrpcTestResultRecord {
  command: string;
  ok: boolean;
  exitCode: number | null;
  stdout: string;
  stderr: string;
  durationMs: number;
  timedOut: boolean;
}

export interface PrMachine {
  prNumber: number;
  branch: string;
  status: PrMachineStatus;
  threadIds: string[];
  connectors: string[];
  /** origin/<branch> SHA at the moment the resolver picked the PR up. */
  remoteSha?: string;
  /** Local HEAD after our commits — what we'd push if approved. */
  localSha?: string;
  /** `git diff origin/<branch>..HEAD` snapshot for the approval view. Capped. */
  diffPreview?: string;
  /** Resolver's final summary for the PR (concat of per-connector summaries). */
  summary?: string;
  /** Reason if rejected/failed. */
  reason?: string;
  /** Phase B: grpcurl commands either extracted from the PR body or generated by Claude. */
  testCommands?: string[];
  /** Phase B: per-command results from the gRPC verification step. */
  testResults?: GrpcTestResultRecord[];
  /** Phase B: whether the commands were extracted or generated. */
  testCommandsSource?: "extracted" | "generated" | "none";
  startedAt: string;
  updatedAt: string;
}

export interface PrResolverState {
  version: 1;
  processed_threads: Record<string, ProcessedThreadEntry>;
  build_failures: Record<string, BuildFailureEntry>;
  pr_machines: Record<string, PrMachine>;
  last_poll: string | null;
}

function freshState(): PrResolverState {
  return {
    version: 1,
    processed_threads: {},
    build_failures: {},
    pr_machines: {},
    last_poll: null,
  };
}

export class PrResolverStateManager {
  private state: PrResolverState = freshState();

  constructor(private readonly stateFile: string) {}

  // ─── Persistence ─────────────────────────────────────────────────────

  load(): PrResolverState {
    if (!fs.existsSync(this.stateFile)) {
      fs.mkdirSync(path.dirname(this.stateFile), { recursive: true });
      this.state = freshState();
      this.save();
      return this.state;
    }
    try {
      const raw = fs.readFileSync(this.stateFile, "utf-8");
      const parsed = JSON.parse(raw) as Partial<PrResolverState>;
      this.state = {
        version: 1,
        processed_threads: parsed.processed_threads ?? {},
        build_failures: parsed.build_failures ?? {},
        pr_machines: parsed.pr_machines ?? {},
        last_poll: parsed.last_poll ?? null,
      };
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn(
        `[pr-resolver:state] Failed to load ${this.stateFile}: ${err instanceof Error ? err.message : String(err)} — starting fresh`
      );
      this.state = freshState();
      this.save();
    }
    return this.state;
  }

  save(): void {
    fs.mkdirSync(path.dirname(this.stateFile), { recursive: true });
    fs.writeFileSync(
      this.stateFile,
      JSON.stringify(this.state, null, 2),
      "utf-8"
    );
  }

  snapshot(): PrResolverState {
    // Deep clone so consumers can't mutate our state via the returned object.
    return JSON.parse(JSON.stringify(this.state)) as PrResolverState;
  }

  // ─── Queries ─────────────────────────────────────────────────────────

  isProcessed(threadId: string): boolean {
    return threadId in this.state.processed_threads;
  }

  /**
   * Thread IDs the poll loop should skip. Excludes `build_blocked` — those
   * need to be re-evaluated each cycle because the build may have been
   * fixed by a new commit (see {@link shouldSkipBuild}).
   */
  getProcessedIds(): Set<string> {
    const out = new Set<string>();
    for (const [tid, entry] of Object.entries(this.state.processed_threads)) {
      if (entry.status !== "build_blocked") out.add(tid);
    }
    return out;
  }

  getProcessedThreads(): Record<string, ProcessedThreadEntry> {
    return this.state.processed_threads;
  }

  getBuildFailures(): Record<string, BuildFailureEntry> {
    return this.state.build_failures;
  }

  /**
   * Forget a cached baseline-build-failure for `prNumber`. The next cycle
   * will re-run the build instead of short-circuiting on the stale SHA.
   * Used by `retryPr` so manual retries genuinely retry.
   */
  clearBuildFailure(prNumber: number): boolean {
    if (this.state.build_failures[String(prNumber)]) {
      delete this.state.build_failures[String(prNumber)];
      this.save();
      return true;
    }
    return false;
  }

  getLastPoll(): string | null {
    return this.state.last_poll;
  }

  // ─── Mutations ───────────────────────────────────────────────────────

  retry(threadId: string): boolean {
    if (threadId in this.state.processed_threads) {
      delete this.state.processed_threads[threadId];
      this.save();
      return true;
    }
    return false;
  }

  retryAllFailed(): number {
    let removed = 0;
    for (const [tid, entry] of Object.entries(this.state.processed_threads)) {
      if (entry.status === "failed") {
        delete this.state.processed_threads[tid];
        removed++;
      }
    }
    if (removed > 0) this.save();
    return removed;
  }

  markFixed(input: {
    threadId: string;
    prNumber: number;
    commitSha: string;
    path: string;
    instruction: string;
    resolutionSummary?: string;
  }): void {
    this.state.processed_threads[input.threadId] = {
      pr_number: input.prNumber,
      processed_at: new Date().toISOString(),
      status: "fixed",
      commit_sha: input.commitSha,
      path: input.path,
      instruction_preview: input.instruction.slice(0, 200),
      resolution_summary: (input.resolutionSummary ?? "").slice(0, 500),
    };
    this.save();
  }

  markFailed(threadId: string, prNumber: number, error: string): void {
    this.state.processed_threads[threadId] = {
      pr_number: prNumber,
      processed_at: new Date().toISOString(),
      status: "failed",
      error: error.slice(0, 3000),
    };
    this.save();
  }

  updateLastPoll(): void {
    this.state.last_poll = new Date().toISOString();
    this.save();
  }

  /**
   * Record a baseline build failure for `prNumber@headSha`. Affected
   * threads are marked `build_blocked` so they show up in the dashboard
   * but auto-clear on the next cycle if a new commit arrives.
   */
  markBuildFailed(input: {
    prNumber: number;
    branch: string;
    headSha: string;
    error: string;
    threadIds?: string[];
  }): void {
    this.state.build_failures[String(input.prNumber)] = {
      branch: input.branch,
      head_sha: input.headSha,
      failed_at: new Date().toISOString(),
      error: input.error.slice(0, 3000),
    };
    if (input.threadIds) {
      for (const tid of input.threadIds) {
        this.state.processed_threads[tid] = {
          pr_number: input.prNumber,
          processed_at: new Date().toISOString(),
          status: "build_blocked",
          error:
            "Branch build broken — will auto-retry when new commits are pushed",
        };
      }
    }
    this.save();
  }

  /**
   * Returns true if `prNumber` has a recorded build failure at exactly
   * `currentSha`. When the SHA differs the failure is cleared (and any
   * blocked threads unblocked) so the cycle retries on the new commit.
   */
  shouldSkipBuild(prNumber: number, currentSha: string): boolean {
    const entry = this.state.build_failures[String(prNumber)];
    if (!entry) return false;
    if (entry.head_sha !== currentSha) {
      delete this.state.build_failures[String(prNumber)];
      for (const [tid, t] of Object.entries(this.state.processed_threads)) {
        if (t.pr_number === prNumber && t.status === "build_blocked") {
          delete this.state.processed_threads[tid];
        }
      }
      this.save();
      return false;
    }
    return true;
  }

  // ─── PR machines ─────────────────────────────────────────────────────

  getPrMachine(prNumber: number): PrMachine | null {
    return this.state.pr_machines[String(prNumber)] ?? null;
  }

  listPrMachines(): PrMachine[] {
    return Object.values(this.state.pr_machines);
  }

  listPrMachinesByStatus(status: PrMachineStatus): PrMachine[] {
    return this.listPrMachines().filter((m) => m.status === status);
  }

  upsertPrMachine(
    input: Partial<PrMachine> & { prNumber: number; branch?: string; status?: PrMachineStatus }
  ): PrMachine {
    const key = String(input.prNumber);
    const existing = this.state.pr_machines[key];
    const now = new Date().toISOString();
    const next: PrMachine = {
      prNumber: input.prNumber,
      branch: input.branch ?? existing?.branch ?? "",
      status: input.status ?? existing?.status ?? "noticed",
      threadIds: input.threadIds ?? existing?.threadIds ?? [],
      connectors: input.connectors ?? existing?.connectors ?? [],
      remoteSha: input.remoteSha ?? existing?.remoteSha,
      localSha: input.localSha ?? existing?.localSha,
      diffPreview: input.diffPreview ?? existing?.diffPreview,
      summary: input.summary ?? existing?.summary,
      reason: input.reason ?? existing?.reason,
      testCommands: input.testCommands ?? existing?.testCommands,
      testResults: input.testResults ?? existing?.testResults,
      testCommandsSource: input.testCommandsSource ?? existing?.testCommandsSource,
      startedAt: existing?.startedAt ?? now,
      updatedAt: now,
    };
    this.state.pr_machines[key] = next;
    this.save();
    return next;
  }

  removePrMachine(prNumber: number): void {
    if (delete this.state.pr_machines[String(prNumber)]) {
      this.save();
    }
  }

  cleanupOldEntries(maxAgeDays = 30): number {
    const cutoff = Date.now() - maxAgeDays * 24 * 60 * 60 * 1000;
    let removed = 0;
    for (const [tid, entry] of Object.entries(this.state.processed_threads)) {
      const ts = Date.parse(entry.processed_at);
      if (!Number.isNaN(ts) && ts < cutoff) {
        delete this.state.processed_threads[tid];
        removed++;
      }
    }
    if (removed > 0) this.save();
    return removed;
  }
}
