//! Country-specific state/province name to ISO 3166-2 subdivision code lookup.
//!
//! Generated from Hyperswitch `common_enums::*StatesAbbreviation` and
//! `hyperswitch_connectors::utils` `ForeignTryFrom<String>` impls so that UCS
//! produces the same state codes as Hyperswitch. US and CA are handled by
//! `convert_us_state_to_code` / `convert_canada_state_to_code`.

use std::sync::LazyLock;

use regex::Regex;
use unicode_normalization::UnicodeNormalization;

/// NFKD-normalize, lowercase and strip everything except `[a-z0-9]`.
fn normalize_state_name(value: &str) -> String {
    static NON_ALPHANUMERIC: LazyLock<Option<Regex>> =
        LazyLock::new(|| Regex::new(r"[^a-z0-9]").ok());
    let lowercase_value = value.nfkd().collect::<String>().to_lowercase();
    match NON_ALPHANUMERIC.as_ref() {
        Some(regex) => regex.replace_all(&lowercase_value, "").to_string(),
        None => lowercase_value,
    }
}

/// Convert a state/province name to its subdivision code for `country`.
///
/// Returns `None` when the country is not covered or the name is unknown, in
/// which case callers should fall back to the state as received.
pub fn convert_state_to_code(
    country: common_enums::CountryAlpha2,
    state: &str,
) -> Option<&'static str> {
    match country {
        common_enums::CountryAlpha2::AL => albania_state_code(state),
        common_enums::CountryAlpha2::AD => andorra_state_code(state),
        common_enums::CountryAlpha2::AT => austria_state_code(state),
        common_enums::CountryAlpha2::BY => belarus_state_code(state),
        common_enums::CountryAlpha2::BA => bosniaandherzegovina_state_code(state),
        common_enums::CountryAlpha2::BG => bulgaria_state_code(state),
        common_enums::CountryAlpha2::HR => croatia_state_code(state),
        common_enums::CountryAlpha2::CZ => czechrepublic_state_code(state),
        common_enums::CountryAlpha2::DK => denmark_state_code(state),
        common_enums::CountryAlpha2::FI => finland_state_code(state),
        common_enums::CountryAlpha2::FR => france_state_code(state),
        common_enums::CountryAlpha2::DE => germany_state_code(state),
        common_enums::CountryAlpha2::GR => greece_state_code(state),
        common_enums::CountryAlpha2::HU => hungary_state_code(state),
        common_enums::CountryAlpha2::IS => iceland_state_code(state),
        common_enums::CountryAlpha2::IE => ireland_state_code(state),
        common_enums::CountryAlpha2::LV => latvia_state_code(state),
        common_enums::CountryAlpha2::IT => italy_state_code(state),
        common_enums::CountryAlpha2::JP => japan_state_code(state),
        common_enums::CountryAlpha2::LI => liechtenstein_state_code(state),
        common_enums::CountryAlpha2::LT => lithuania_state_code(state),
        common_enums::CountryAlpha2::MT => malta_state_code(state),
        common_enums::CountryAlpha2::MD => moldova_state_code(state),
        common_enums::CountryAlpha2::MC => monaco_state_code(state),
        common_enums::CountryAlpha2::ME => montenegro_state_code(state),
        common_enums::CountryAlpha2::NL => netherlands_state_code(state),
        common_enums::CountryAlpha2::NZ => newzealand_state_code(state),
        common_enums::CountryAlpha2::MK => northmacedonia_state_code(state),
        common_enums::CountryAlpha2::NO => norway_state_code(state),
        common_enums::CountryAlpha2::PL => poland_state_code(state),
        common_enums::CountryAlpha2::PT => portugal_state_code(state),
        common_enums::CountryAlpha2::ES => spain_state_code(state),
        common_enums::CountryAlpha2::CH => switzerland_state_code(state),
        common_enums::CountryAlpha2::GB => unitedkingdom_state_code(state),
        common_enums::CountryAlpha2::BR => brazil_state_code(state),
        common_enums::CountryAlpha2::AU => australia_state_code(state),
        common_enums::CountryAlpha2::SG => singapore_state_code(state),
        common_enums::CountryAlpha2::TH => thailand_state_code(state),
        common_enums::CountryAlpha2::PH => philippines_state_code(state),
        common_enums::CountryAlpha2::IN => india_state_code(state),
        _ => None,
    }
}

fn albania_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Berat" => Some("01"),
        "Dibër" => Some("09"),
        "Durrës" => Some("02"),
        "Elbasan" => Some("03"),
        "Fier" => Some("04"),
        "Gjirokastër" => Some("05"),
        "Korçë" => Some("06"),
        "Kukës" => Some("07"),
        "Lezhë" => Some("08"),
        "Shkodër" => Some("10"),
        "Tiranë" => Some("11"),
        "Vlorë" => Some("12"),
        _ => None,
    }
}

fn andorra_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Andorra la Vella" => Some("07"),
        "Canillo" => Some("02"),
        "Encamp" => Some("03"),
        "Escaldes-Engordany" => Some("08"),
        "La Massana" => Some("04"),
        "Ordino" => Some("05"),
        "Sant Julià de Lòria" => Some("06"),
        _ => None,
    }
}

fn austria_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Burgenland" => Some("1"),
        "Carinthia" => Some("2"),
        "Lower Austria" => Some("3"),
        "Salzburg" => Some("5"),
        "Styria" => Some("6"),
        "Tyrol" => Some("7"),
        "Upper Austria" => Some("4"),
        "Vienna" => Some("9"),
        "Vorarlberg" => Some("8"),
        _ => None,
    }
}

fn belarus_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Brest Region" => Some("BR"),
        "Gomel Region" => Some("HO"),
        "Grodno Region" => Some("HR"),
        "Minsk" => Some("HM"),
        "Minsk Region" => Some("MI"),
        "Mogilev Region" => Some("MA"),
        "Vitebsk Region" => Some("VI"),
        _ => None,
    }
}

fn bosniaandherzegovina_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Bosnian Podrinje Canton" => Some("05"),
        "Brčko District" => Some("BRC"),
        "Canton 10" => Some("10"),
        "Central Bosnia Canton" => Some("06"),
        "Federation of Bosnia and Herzegovina" => Some("BIH"),
        "Herzegovina-Neretva Canton" => Some("07"),
        "Posavina Canton" => Some("02"),
        "Republika Srpska" => Some("SRP"),
        "Sarajevo Canton" => Some("09"),
        "Tuzla Canton" => Some("03"),
        "Una-Sana Canton" => Some("01"),
        "West Herzegovina Canton" => Some("08"),
        "Zenica-Doboj Canton" => Some("04"),
        _ => None,
    }
}

fn bulgaria_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Blagoevgrad Province" => Some("01"),
        "Burgas Province" => Some("02"),
        "Dobrich Province" => Some("08"),
        "Gabrovo Province" => Some("07"),
        "Haskovo Province" => Some("26"),
        "Kardzhali Province" => Some("09"),
        "Kyustendil Province" => Some("10"),
        "Lovech Province" => Some("11"),
        "Montana Province" => Some("12"),
        "Pazardzhik Province" => Some("13"),
        "Pernik Province" => Some("14"),
        "Pleven Province" => Some("15"),
        "Plovdiv Province" => Some("16"),
        "Razgrad Province" => Some("17"),
        "Ruse Province" => Some("18"),
        "Shumen" => Some("27"),
        "Silistra Province" => Some("19"),
        "Sliven Province" => Some("20"),
        "Smolyan Province" => Some("21"),
        "Sofia City Province" => Some("22"),
        "Sofia Province" => Some("23"),
        "Stara Zagora Province" => Some("24"),
        "Targovishte Provinc" => Some("25"),
        "Varna Province" => Some("03"),
        "Veliko Tarnovo Province" => Some("04"),
        "Vidin Province" => Some("05"),
        "Vratsa Province" => Some("06"),
        "Yambol Province" => Some("28"),
        _ => None,
    }
}

fn croatia_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Bjelovar-Bilogora County" => Some("07"),
        "Brod-Posavina County" => Some("12"),
        "Dubrovnik-Neretva County" => Some("19"),
        "Istria County" => Some("18"),
        "Koprivnica-Križevci County" => Some("06"),
        "Krapina-Zagorje County" => Some("02"),
        "Lika-Senj County" => Some("09"),
        "Međimurje County" => Some("20"),
        "Osijek-Baranja County" => Some("14"),
        "Požega-Slavonia County" => Some("11"),
        "Primorje-Gorski Kotar County" => Some("08"),
        "Sisak-Moslavina County" => Some("03"),
        "Split-Dalmatia County" => Some("17"),
        "Varaždin County" => Some("05"),
        "Virovitica-Podravina County" => Some("10"),
        "Vukovar-Syrmia County" => Some("16"),
        "Zadar County" => Some("13"),
        "Zagreb" => Some("21"),
        "Zagreb County" => Some("01"),
        "Šibenik-Knin County" => Some("15"),
        _ => None,
    }
}

fn czechrepublic_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Benešov District" => Some("201"),
        "Beroun District" => Some("202"),
        "Blansko District" => Some("641"),
        "Brno-City District" => Some("642"),
        "Brno-Country District" => Some("643"),
        "Bruntál District" => Some("801"),
        "Břeclav District" => Some("644"),
        "Central Bohemian Region" => Some("20"),
        "Cheb District" => Some("411"),
        "Chomutov District" => Some("422"),
        "Chrudim District" => Some("531"),
        "Domažlice Distric" => Some("321"),
        "Děčín District" => Some("421"),
        "Frýdek-Místek District" => Some("802"),
        "Havlíčkův Brod District" => Some("631"),
        "Hodonín District" => Some("645"),
        "Horní Počernice" => Some("120"),
        "Hradec Králové District" => Some("521"),
        "Hradec Králové Region" => Some("52"),
        "Jablonec nad Nisou District" => Some("512"),
        "Jeseník District" => Some("711"),
        "Jihlava District" => Some("632"),
        "Jindřichův Hradec District" => Some("313"),
        "Jičín District" => Some("522"),
        "Karlovy Vary District" => Some("412"),
        "Karlovy Vary Region" => Some("41"),
        "Karviná District" => Some("803"),
        "Kladno District" => Some("203"),
        "Klatovy District" => Some("322"),
        "Kolín District" => Some("204"),
        "Kroměříž District" => Some("721"),
        "Liberec District" => Some("513"),
        "Liberec Region" => Some("51"),
        "Litoměřice District" => Some("423"),
        "Louny District" => Some("424"),
        "Mladá Boleslav District" => Some("207"),
        "Moravian-Silesian Region" => Some("80"),
        "Most District" => Some("425"),
        "Mělník District" => Some("206"),
        "Nový Jičín District" => Some("804"),
        "Nymburk District" => Some("208"),
        "Náchod District" => Some("523"),
        "Olomouc District" => Some("712"),
        "Olomouc Region" => Some("71"),
        "Opava District" => Some("805"),
        "Ostrava-City District" => Some("806"),
        "Pardubice District" => Some("532"),
        "Pardubice Region" => Some("53"),
        "Pelhřimov District" => Some("633"),
        "Plzeň Region" => Some("32"),
        "Plzeň-City District" => Some("323"),
        "Plzeň-North District" => Some("325"),
        "Plzeň-South District" => Some("324"),
        "Prachatice District" => Some("315"),
        "Prague" => Some("10"),
        "Prague 1" => Some("101"),
        "Prague 10" => Some("110"),
        "Prague 11" => Some("111"),
        "Prague 12" => Some("112"),
        "Prague 13" => Some("113"),
        "Prague 14" => Some("114"),
        "Prague 15" => Some("115"),
        "Prague 16" => Some("116"),
        "Prague 2" => Some("102"),
        "Prague 21" => Some("121"),
        "Prague 3" => Some("103"),
        "Prague 4" => Some("104"),
        "Prague 5" => Some("105"),
        "Prague 6" => Some("106"),
        "Prague 7" => Some("107"),
        "Prague 8" => Some("108"),
        "Prague 9" => Some("109"),
        "Prague-East District" => Some("209"),
        "Prague-West District" => Some("20A"),
        "Prostějov District" => Some("713"),
        "Písek District" => Some("314"),
        "Přerov District" => Some("714"),
        "Příbram District" => Some("20B"),
        "Rakovník District" => Some("20C"),
        "Rokycany District" => Some("326"),
        "Rychnov nad Kněžnou District" => Some("524"),
        "Semily District" => Some("514"),
        "Sokolov District" => Some("413"),
        "South Bohemian Region" => Some("31"),
        "South Moravian Region" => Some("64"),
        "Strakonice District" => Some("316"),
        "Svitavy District" => Some("533"),
        "Tachov District" => Some("327"),
        "Teplice District" => Some("426"),
        "Trutnov District" => Some("525"),
        "Tábor District" => Some("317"),
        "Třebíč District" => Some("634"),
        "Uherské Hradiště District" => Some("722"),
        "Vsetín District" => Some("723"),
        "Vysočina Region" => Some("63"),
        "Vyškov District" => Some("646"),
        "Zlín District" => Some("724"),
        "Zlín Region" => Some("72"),
        "Znojmo District" => Some("647"),
        "Ústí nad Labem District" => Some("427"),
        "Ústí nad Labem Region" => Some("42"),
        "Ústí nad Orlicí District" => Some("534"),
        "Česká Lípa District" => Some("511"),
        "České Budějovice District" => Some("311"),
        "Český Krumlov District" => Some("312"),
        "Šumperk District" => Some("715"),
        "Žďár nad Sázavou District" => Some("635"),
        _ => None,
    }
}

fn denmark_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Capital Region of Denmark" => Some("84"),
        "Central Denmark Region" => Some("82"),
        "North Denmark Region" => Some("81"),
        "Region Zealand" => Some("85"),
        "Region of Southern Denmark" => Some("83"),
        _ => None,
    }
}

fn finland_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Central Finland" => Some("08"),
        "Central Ostrobothnia" => Some("07"),
        "Eastern Finland Province" => Some("IS"),
        "Finland Proper" => Some("19"),
        "Kainuu" => Some("05"),
        "Kymenlaakso" => Some("09"),
        "Lapland" => Some("LL"),
        "North Karelia" => Some("13"),
        "Northern Ostrobothnia" => Some("14"),
        "Northern Savonia" => Some("15"),
        "Ostrobothnia" => Some("12"),
        "Oulu Province" => Some("OL"),
        "Pirkanmaa" => Some("11"),
        "Päijänne Tavastia" => Some("16"),
        "Satakunta" => Some("17"),
        "South Karelia" => Some("02"),
        "Southern Ostrobothnia" => Some("03"),
        "Southern Savonia" => Some("04"),
        "Tavastia Proper" => Some("06"),
        "Uusimaa" => Some("18"),
        "Åland Islands" => Some("01"),
        _ => None,
    }
}

fn france_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Ain" => Some("01"),
        "Aisne" => Some("02"),
        "Allier" => Some("03"),
        "Alpes-de-Haute-Provence" => Some("04"),
        "Alpes-Maritimes" => Some("06"),
        "Alsace" => Some("6AE"),
        "Ardèche" => Some("07"),
        "Ardennes" => Some("08"),
        "Ariège" => Some("09"),
        "Aube" => Some("10"),
        "Aude" => Some("11"),
        "Auvergne-Rhône-Alpes" => Some("ARA"),
        "Aveyron" => Some("12"),
        "Bas-Rhin" => Some("67"),
        "Bouches-du-Rhône" => Some("13"),
        "Bourgogne-Franche-Comté" => Some("BFC"),
        "Bretagne" => Some("BRE"),
        "Calvados" => Some("14"),
        "Cantal" => Some("15"),
        "Centre-Val de Loire" => Some("CVL"),
        "Charente" => Some("16"),
        "Charente-Maritime" => Some("17"),
        "Cher" => Some("18"),
        "Clipperton" => Some("CP"),
        "Corrèze" => Some("19"),
        "Corse" => Some("20R"),
        "Corse-du-Sud" => Some("2A"),
        "Côte-d'Or" => Some("21"),
        "Côtes-d'Armor" => Some("22"),
        "Creuse" => Some("23"),
        "Deux-Sèvres" => Some("79"),
        "Dordogne" => Some("24"),
        "Doubs" => Some("25"),
        "Drôme" => Some("26"),
        "Essonne" => Some("91"),
        "Eure" => Some("27"),
        "Eure-et-Loir" => Some("28"),
        "Finistère" => Some("29"),
        "French Guiana" => Some("973"),
        "French Polynesia" => Some("PF"),
        "French Southern and Antarctic Lands" => Some("TF"),
        "Gard" => Some("30"),
        "Gers" => Some("32"),
        "Gironde" => Some("33"),
        "Grand-Est" => Some("GES"),
        "Guadeloupe" => Some("971"),
        "Haut-Rhin" => Some("68"),
        "Haute-Corse" => Some("2B"),
        "Haute-Garonne" => Some("31"),
        "Haute-Loire" => Some("43"),
        "Haute-Marne" => Some("52"),
        "Haute-Saône" => Some("70"),
        "Haute-Savoie" => Some("74"),
        "Haute-Vienne" => Some("87"),
        "Hautes-Alpes" => Some("05"),
        "Hautes-Pyrénées" => Some("65"),
        "Hauts-de-France" => Some("HDF"),
        "Hauts-de-Seine" => Some("92"),
        "Hérault" => Some("34"),
        "Île-de-France" => Some("IDF"),
        "Ille-et-Vilaine" => Some("35"),
        "Indre" => Some("36"),
        "Indre-et-Loire" => Some("37"),
        "Isère" => Some("38"),
        "Jura" => Some("39"),
        "La Réunion" => Some("974"),
        "Landes" => Some("40"),
        "Loir-et-Cher" => Some("41"),
        "Loire" => Some("42"),
        "Loire-Atlantique" => Some("44"),
        "Loiret" => Some("45"),
        "Lot" => Some("46"),
        "Lot-et-Garonne" => Some("47"),
        "Lozère" => Some("48"),
        "Maine-et-Loire" => Some("49"),
        "Manche" => Some("50"),
        "Marne" => Some("51"),
        "Martinique" => Some("972"),
        "Mayenne" => Some("53"),
        "Mayotte" => Some("976"),
        "Métropole de Lyon" => Some("69M"),
        "Meurthe-et-Moselle" => Some("54"),
        "Meuse" => Some("55"),
        "Morbihan" => Some("56"),
        "Moselle" => Some("57"),
        "Nièvre" => Some("58"),
        "Nord" => Some("59"),
        "Normandie" => Some("NOR"),
        "Nouvelle-Aquitaine" => Some("NAQ"),
        "Occitanie" => Some("OCC"),
        "Oise" => Some("60"),
        "Orne" => Some("61"),
        "Paris" => Some("75C"),
        "Pas-de-Calais" => Some("62"),
        "Pays-de-la-Loire" => Some("PDL"),
        "Provence-Alpes-Côte-d'Azur" => Some("PAC"),
        "Puy-de-Dôme" => Some("63"),
        "Pyrénées-Atlantiques" => Some("64"),
        "Pyrénées-Orientales" => Some("66"),
        "Rhône" => Some("69"),
        "Saint Pierre and Miquelon" => Some("PM"),
        "Saint-Barthélemy" => Some("BL"),
        "Saint-Martin" => Some("MF"),
        "Saône-et-Loire" => Some("71"),
        "Sarthe" => Some("72"),
        "Savoie" => Some("73"),
        "Seine-et-Marne" => Some("77"),
        "Seine-Maritime" => Some("76"),
        "Seine-Saint-Denis" => Some("93"),
        "Somme" => Some("80"),
        "Tarn" => Some("81"),
        "Tarn-et-Garonne" => Some("82"),
        "Territoire de Belfort" => Some("90"),
        "Val-d'Oise" => Some("95"),
        "Val-de-Marne" => Some("94"),
        "Var" => Some("83"),
        "Vaucluse" => Some("84"),
        "Vendée" => Some("85"),
        "Vienne" => Some("86"),
        "Vosges" => Some("88"),
        "Wallis and Futuna" => Some("WF"),
        "Yonne" => Some("89"),
        "Yvelines" => Some("78"),
        _ => None,
    }
}

fn germany_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Baden-Württemberg" => Some("BW"),
        "Bavaria" => Some("BY"),
        "Berlin" => Some("BE"),
        "Brandenburg" => Some("BB"),
        "Bremen" => Some("HB"),
        "Hamburg" => Some("HH"),
        "Hessen" => Some("HE"),
        "Lower Saxony" => Some("NI"),
        "Mecklenburg-Vorpommern" => Some("MV"),
        "North Rhine-Westphalia" => Some("NW"),
        "Rhineland-Palatinate" => Some("RP"),
        "Saarland" => Some("SL"),
        "Saxony" => Some("SN"),
        "Saxony-Anhalt" => Some("ST"),
        "Schleswig-Holstein" => Some("SH"),
        "Thuringia" => Some("TH"),
        _ => None,
    }
}

fn greece_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Achaea Regional Unit" => Some("13"),
        "Aetolia-Acarnania Regional Unit" => Some("01"),
        "Arcadia Prefecture" => Some("12"),
        "Argolis Regional Unit" => Some("11"),
        "Attica Region" => Some("I"),
        "Boeotia Regional Unit" => Some("03"),
        "Central Greece Region" => Some("H"),
        "Central Macedonia" => Some("B"),
        "Chania Regional Unit" => Some("94"),
        "Corfu Prefecture" => Some("22"),
        "Corinthia Regional Unit" => Some("15"),
        "Crete Region" => Some("M"),
        "Drama Regional Unit" => Some("52"),
        "East Attica Regional Unit" => Some("A2"),
        "East Macedonia and Thrace" => Some("A"),
        "Epirus Region" => Some("D"),
        "Euboea" => Some("04"),
        "Grevena Prefecture" => Some("51"),
        "Imathia Regional Unit" => Some("53"),
        "Ioannina Regional Unit" => Some("33"),
        "Ionian Islands Region" => Some("F"),
        "Karditsa Regional Unit" => Some("41"),
        "Kastoria Regional Unit" => Some("56"),
        "Kefalonia Prefecture" => Some("23"),
        "Kilkis Regional Unit" => Some("57"),
        "Kozani Prefecture" => Some("58"),
        "Laconia" => Some("16"),
        "Larissa Prefecture" => Some("42"),
        "Lefkada Regional Unit" => Some("24"),
        "Pella Regional Unit" => Some("59"),
        "Peloponnese Region" => Some("J"),
        "Phthiotis Prefecture" => Some("06"),
        "Preveza Prefecture" => Some("34"),
        "Serres Prefecture" => Some("62"),
        "South Aegean" => Some("L"),
        "Thessaloniki Regional Unit" => Some("54"),
        "West Greece Region" => Some("G"),
        "West Macedonia Region" => Some("C"),
        _ => None,
    }
}

fn hungary_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Baranya County" => Some("BA"),
        "Borsod-Abaúj-Zemplén County" => Some("BZ"),
        "Budapest" => Some("BU"),
        "Bács-Kiskun County" => Some("BK"),
        "Békés County" => Some("BE"),
        "Békéscsaba" => Some("BC"),
        "Csongrád County" => Some("CS"),
        "Debrecen" => Some("DE"),
        "Dunaújváros" => Some("DU"),
        "Eger" => Some("EG"),
        "Fejér County" => Some("FE"),
        "Győr" => Some("GY"),
        "Győr-Moson-Sopron County" => Some("GS"),
        "Hajdú-Bihar County" => Some("HB"),
        "Heves County" => Some("HE"),
        "Hódmezővásárhely" => Some("HV"),
        "Jász-Nagykun-Szolnok County" => Some("JN"),
        "Kaposvár" => Some("KV"),
        "Kecskemét" => Some("KM"),
        "Miskolc" => Some("MI"),
        "Nagykanizsa" => Some("NK"),
        "Nyíregyháza" => Some("NY"),
        "Nógrád County" => Some("NO"),
        "Pest County" => Some("PE"),
        "Pécs" => Some("PS"),
        "Salgótarján" => Some("ST"),
        "Somogy County" => Some("SO"),
        "Sopron" => Some("SN"),
        "Szabolcs-Szatmár-Bereg County" => Some("SZ"),
        "Szeged" => Some("SD"),
        "Szekszárd" => Some("SS"),
        "Szolnok" => Some("SK"),
        "Szombathely" => Some("SH"),
        "Székesfehérvár" => Some("SF"),
        "Tatabánya" => Some("TB"),
        "Tolna County" => Some("TO"),
        "Vas County" => Some("VA"),
        "Veszprém" => Some("VM"),
        "Veszprém County" => Some("VE"),
        "Zala County" => Some("ZA"),
        "Zalaegerszeg" => Some("ZE"),
        "Érd" => Some("ER"),
        _ => None,
    }
}

fn iceland_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Capital Region" => Some("1"),
        "Eastern Region" => Some("7"),
        "Northeastern Region" => Some("6"),
        "Northwestern Region" => Some("5"),
        "Southern Peninsula Region" => Some("2"),
        "Southern Region" => Some("8"),
        "Western Region" => Some("3"),
        "Westfjords" => Some("4"),
        _ => None,
    }
}

fn ireland_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Connacht" => Some("C"),
        "County Carlow" => Some("CW"),
        "County Cavan" => Some("CN"),
        "County Clare" => Some("CE"),
        "County Cork" => Some("CO"),
        "County Donegal" => Some("DL"),
        "County Dublin" => Some("D"),
        "County Galway" => Some("G"),
        "County Kerry" => Some("KY"),
        "County Kildare" => Some("KE"),
        "County Kilkenny" => Some("KK"),
        "County Laois" => Some("LS"),
        "County Limerick" => Some("LK"),
        "County Longford" => Some("LD"),
        "County Louth" => Some("LH"),
        "County Mayo" => Some("MO"),
        "County Meath" => Some("MH"),
        "County Monaghan" => Some("MN"),
        "County Offaly" => Some("OY"),
        "County Roscommon" => Some("RN"),
        "County Sligo" => Some("SO"),
        "County Tipperary" => Some("TA"),
        "County Waterford" => Some("WD"),
        "County Westmeath" => Some("WH"),
        "County Wexford" => Some("WX"),
        "County Wicklow" => Some("WW"),
        "Leinster" => Some("L"),
        "Munster" => Some("M"),
        "Ulster" => Some("U"),
        _ => None,
    }
}

fn latvia_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Aglona Municipality" => Some("001"),
        "Aizkraukle Municipality" => Some("002"),
        "Aizpute Municipality" => Some("003"),
        "Aknīste Municipality" => Some("004"),
        "Aloja Municipality" => Some("005"),
        "Alsunga Municipality" => Some("006"),
        "Alūksne Municipality" => Some("007"),
        "Amata Municipality" => Some("008"),
        "Ape Municipality" => Some("009"),
        "Auce Municipality" => Some("010"),
        "Babīte Municipality" => Some("012"),
        "Baldone Municipality" => Some("013"),
        "Baltinava Municipality" => Some("014"),
        "Balvi Municipality" => Some("015"),
        "Bauska Municipality" => Some("016"),
        "Beverīna Municipality" => Some("017"),
        "Brocēni Municipality" => Some("018"),
        "Burtnieki Municipality" => Some("019"),
        "Carnikava Municipality" => Some("020"),
        "Cesvaine Municipality" => Some("021"),
        "Cibla Municipality" => Some("023"),
        "Cēsis Municipality" => Some("022"),
        "Dagda Municipality" => Some("024"),
        "Daugavpils" => Some("DGV"),
        "Daugavpils Municipality" => Some("025"),
        "Dobele Municipality" => Some("026"),
        "Dundaga Municipality" => Some("027"),
        "Durbe Municipality" => Some("028"),
        "Engure Municipality" => Some("029"),
        "Garkalne Municipality" => Some("031"),
        "Grobiņa Municipality" => Some("032"),
        "Gulbene Municipality" => Some("033"),
        "Iecava Municipality" => Some("034"),
        "Ikšķile Municipality" => Some("035"),
        "Ilūkste Municipalityy" => Some("036"),
        "Inčukalns Municipality" => Some("037"),
        "Jaunjelgava Municipality" => Some("038"),
        "Jaunpiebalga Municipality" => Some("039"),
        "Jaunpils Municipality" => Some("040"),
        "Jelgava" => Some("JEL"),
        "Jelgava Municipality" => Some("041"),
        "Jēkabpils" => Some("JKB"),
        "Jēkabpils Municipality" => Some("042"),
        "Jūrmala" => Some("JUR"),
        "Kandava Municipality" => Some("043"),
        "Kocēni Municipality" => Some("045"),
        "Koknese Municipality" => Some("046"),
        "Krimulda Municipality" => Some("048"),
        "Krustpils Municipality" => Some("049"),
        "Krāslava Municipality" => Some("047"),
        "Kuldīga Municipality" => Some("050"),
        "Kārsava Municipality" => Some("044"),
        "Lielvārde Municipality" => Some("053"),
        "Liepāja" => Some("LPX"),
        "Limbaži Municipality" => Some("054"),
        "Lubāna Municipality" => Some("057"),
        "Ludza Municipality" => Some("058"),
        "Līgatne Municipality" => Some("055"),
        "Līvāni Municipality" => Some("056"),
        "Madona Municipality" => Some("059"),
        "Mazsalaca Municipality" => Some("060"),
        "Mālpils Municipality" => Some("061"),
        "Mārupe Municipality" => Some("062"),
        "Mērsrags Municipality" => Some("063"),
        "Naukšēni Municipality" => Some("064"),
        "Nereta Municipality" => Some("065"),
        "Nīca Municipality" => Some("066"),
        "Ogre Municipality" => Some("067"),
        "Olaine Municipality" => Some("068"),
        "Ozolnieki Municipality" => Some("069"),
        "Preiļi Municipality" => Some("073"),
        "Priekule Municipality" => Some("074"),
        "Priekuļi Municipality" => Some("075"),
        "Pārgauja Municipality" => Some("070"),
        "Pāvilosta Municipality" => Some("071"),
        "Pļaviņas Municipality" => Some("072"),
        "Rauna Municipality" => Some("076"),
        "Riebiņi Municipality" => Some("078"),
        "Riga" => Some("RIX"),
        "Roja Municipality" => Some("079"),
        "Ropaži Municipality" => Some("080"),
        "Rucava Municipality" => Some("081"),
        "Rugāji Municipality" => Some("082"),
        "Rundāle Municipality" => Some("083"),
        "Rēzekne" => Some("REZ"),
        "Rēzekne Municipality" => Some("077"),
        "Rūjiena Municipality" => Some("084"),
        "Sala Municipality" => Some("085"),
        "Salacgrīva Municipality" => Some("086"),
        "Salaspils Municipality" => Some("087"),
        "Saldus Municipality" => Some("088"),
        "Saulkrasti Municipality" => Some("089"),
        "Sigulda Municipality" => Some("091"),
        "Skrunda Municipality" => Some("093"),
        "Skrīveri Municipality" => Some("092"),
        "Smiltene Municipality" => Some("094"),
        "Stopiņi Municipality" => Some("095"),
        "Strenči Municipality" => Some("096"),
        "Sēja Municipality" => Some("090"),
        _ => None,
    }
}

fn italy_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Abruzzo" => Some("65"),
        "Aosta Valley" => Some("23"),
        "Apulia" => Some("75"),
        "Basilicata" => Some("77"),
        "Benevento Province" => Some("BN"),
        "Calabria" => Some("78"),
        "Campania" => Some("72"),
        "Emilia-Romagna" => Some("45"),
        "Friuli–Venezia Giulia" => Some("36"),
        "Lazio" => Some("62"),
        "Liguria" => Some("42"),
        "Lombardy" => Some("25"),
        "Marche" => Some("57"),
        "Molise" => Some("67"),
        "Piedmont" => Some("21"),
        "Sardinia" => Some("88"),
        "Sicily" => Some("82"),
        "Trentino-South Tyrol" => Some("32"),
        "Tuscany" => Some("52"),
        "Umbria" => Some("55"),
        "Veneto" => Some("34"),
        "Libero consorzio comunale di Agrigento" => Some("AG"),
        "Libero consorzio comunale di Caltanissetta" => Some("CL"),
        "Libero consorzio comunale di Enna" => Some("EN"),
        "Libero consorzio comunale di Ragusa" => Some("RG"),
        "Libero consorzio comunale di Siracusa" => Some("SR"),
        "Libero consorzio comunale di Trapani" => Some("TP"),
        "Metropolitan City of Bari" => Some("BA"),
        "Metropolitan City of Bologna" => Some("BO"),
        "Metropolitan City of Cagliari" => Some("CA"),
        "Metropolitan City of Catania" => Some("CT"),
        "Metropolitan City of Florence" => Some("FI"),
        "Metropolitan City of Genoa" => Some("GE"),
        "Metropolitan City of Messina" => Some("ME"),
        "Metropolitan City of Milan" => Some("MI"),
        "Metropolitan City of Naples" => Some("NA"),
        "Metropolitan City of Palermo" => Some("PA"),
        "Metropolitan City of Reggio Calabria" => Some("RC"),
        "Metropolitan City of Rome" => Some("RM"),
        "Metropolitan City of Turin" => Some("TO"),
        "Metropolitan City of Venice" => Some("VE"),
        _ => None,
    }
}

fn japan_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "aichi" => Some("23"),
        "akita" => Some("05"),
        "aomori" => Some("02"),
        "chiba" => Some("12"),
        "ehime" => Some("38"),
        "fukui" => Some("18"),
        "fukuoka" => Some("40"),
        "fukushima" | "hukusima" => Some("07"),
        "gifu" => Some("21"),
        "gunma" => Some("10"),
        "hiroshima" => Some("34"),
        "hokkaido" => Some("01"),
        "hyogo" => Some("28"),
        "ibaraki" => Some("08"),
        "ishikawa" => Some("17"),
        "iwate" => Some("03"),
        "kagawa" => Some("37"),
        "kagoshima" => Some("46"),
        "kanagawa" => Some("14"),
        "kochi" => Some("39"),
        "kumamoto" => Some("43"),
        "kyoto" => Some("26"),
        "mie" => Some("24"),
        "miyagi" => Some("04"),
        "miyazaki" => Some("45"),
        "nagano" => Some("20"),
        "nagasaki" => Some("42"),
        "nara" => Some("29"),
        "niigata" => Some("15"),
        "oita" => Some("44"),
        "okayama" => Some("33"),
        "okinawa" => Some("47"),
        "osaka" => Some("27"),
        "saga" => Some("41"),
        "saitama" => Some("11"),
        "shiga" => Some("25"),
        "shimane" => Some("32"),
        "shizuoka" => Some("22"),
        "tochigi" => Some("09"),
        "tokushima" | "tokusima" => Some("36"),
        "tokyo" => Some("13"),
        "tottori" => Some("31"),
        "toyama" => Some("16"),
        "wakayama" => Some("30"),
        "yamagata" => Some("06"),
        "yamaguchi" => Some("35"),
        "yamanashi" => Some("19"),
        _ => None,
    }
}

fn liechtenstein_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Balzers" => Some("01"),
        "Eschen" => Some("02"),
        "Gamprin" => Some("03"),
        "Mauren" => Some("04"),
        "Planken" => Some("05"),
        "Ruggell" => Some("06"),
        "Schaan" => Some("07"),
        "Schellenberg" => Some("08"),
        "Triesen" => Some("09"),
        "Triesenberg" => Some("10"),
        "Vaduz" => Some("11"),
        _ => None,
    }
}

fn lithuania_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Akmenė District Municipality" => Some("01"),
        "Alytus City Municipality" => Some("02"),
        "Alytus County" => Some("AL"),
        "Alytus District Municipality" => Some("03"),
        "Birštonas Municipality" => Some("05"),
        "Biržai District Municipality" => Some("06"),
        "Druskininkai municipality" => Some("07"),
        "Elektrėnai municipality" => Some("08"),
        "Ignalina District Municipality" => Some("09"),
        "Jonava District Municipality" => Some("10"),
        "Joniškis District Municipality" => Some("11"),
        "Jurbarkas District Municipality" => Some("12"),
        "Kaišiadorys District Municipality" => Some("13"),
        "Kalvarija municipality" => Some("14"),
        "Kaunas City Municipality" => Some("15"),
        "Kaunas County" => Some("KU"),
        "Kaunas District Municipality" => Some("16"),
        "Kazlų Rūda municipality" => Some("17"),
        "Kelmė District Municipality" => Some("19"),
        "Klaipeda City Municipality" => Some("20"),
        "Klaipėda County" => Some("KL"),
        "Klaipėda District Municipality" => Some("21"),
        "Kretinga District Municipality" => Some("22"),
        "Kupiškis District Municipality" => Some("23"),
        "Kėdainiai District Municipality" => Some("18"),
        "Lazdijai District Municipality" => Some("24"),
        "Marijampolė County" => Some("MR"),
        "Marijampolė Municipality" => Some("25"),
        "Mažeikiai District Municipality" => Some("26"),
        "Molėtai District Municipality" => Some("27"),
        "Neringa Municipality" => Some("28"),
        "Pagėgiai municipality" => Some("29"),
        "Pakruojis District Municipality" => Some("30"),
        "Palanga City Municipality" => Some("31"),
        "Panevėžys City Municipality" => Some("32"),
        "Panevėžys County" => Some("PN"),
        "Panevėžys District Municipality" => Some("33"),
        "Pasvalys District Municipality" => Some("34"),
        "Plungė District Municipality" => Some("35"),
        "Prienai District Municipality" => Some("36"),
        "Radviliškis District Municipality" => Some("37"),
        "Raseiniai District Municipality" => Some("38"),
        "Rietavas municipality" => Some("39"),
        "Rokiškis District Municipality" => Some("40"),
        "Skuodas District Municipality" => Some("48"),
        "Tauragė County" => Some("TA"),
        "Tauragė District Municipality" => Some("50"),
        "Telšiai County" => Some("TE"),
        "Telšiai District Municipality" => Some("51"),
        "Trakai District Municipality" => Some("52"),
        "Ukmergė District Municipality" => Some("53"),
        "Utena County" => Some("UT"),
        "Utena District Municipality" => Some("54"),
        "Varėna District Municipality" => Some("55"),
        "Vilkaviškis District Municipality" => Some("56"),
        "Vilnius City Municipality" => Some("57"),
        "Vilnius County" => Some("VL"),
        "Vilnius District Municipality" => Some("58"),
        "Visaginas Municipality" => Some("59"),
        "Zarasai District Municipality" => Some("60"),
        "Šakiai District Municipality" => Some("41"),
        "Šalčininkai District Municipality" => Some("42"),
        "Šiauliai City Municipality" => Some("43"),
        "Šiauliai County" => Some("SA"),
        "Šiauliai District Municipality" => Some("44"),
        "Šilalė District Municipality" => Some("45"),
        "Šilutė District Municipality" => Some("46"),
        "Širvintos District Municipality" => Some("47"),
        "Švenčionys District Municipality" => Some("49"),
        _ => None,
    }
}

fn malta_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Attard" => Some("01"),
        "Balzan" => Some("02"),
        "Birgu" => Some("03"),
        "Birkirkara" => Some("04"),
        "Birżebbuġa" => Some("05"),
        "Cospicua" => Some("06"),
        "Dingli" => Some("07"),
        "Fgura" => Some("08"),
        "Floriana" => Some("09"),
        "Fontana" => Some("10"),
        "Gudja" => Some("11"),
        "Gżira" => Some("12"),
        "Għajnsielem" => Some("13"),
        "Għarb" => Some("14"),
        "Għargħur" => Some("15"),
        "Għasri" => Some("16"),
        "Għaxaq" => Some("17"),
        "Ħamrun" => Some("18"),
        "Iklin" => Some("19"),
        "Senglea" => Some("20"),
        "Kalkara" => Some("21"),
        "Kerċem" => Some("22"),
        "Kirkop" => Some("23"),
        "Lija" => Some("24"),
        "Luqa" => Some("25"),
        "Marsa" => Some("26"),
        "Marsaskala" => Some("27"),
        "Marsaxlokk" => Some("28"),
        "Mdina" => Some("29"),
        "Mellieħa" => Some("30"),
        "Mosta" => Some("32"),
        "Mqabba" => Some("33"),
        "Msida" => Some("34"),
        "Mtarfa" => Some("35"),
        "Munxar" => Some("36"),
        "Mġarr" => Some("31"),
        "Nadur" => Some("37"),
        "Naxxar" => Some("38"),
        "Paola" => Some("39"),
        "Pembroke" => Some("40"),
        "Pietà" => Some("41"),
        "Qala" => Some("42"),
        "Qormi" => Some("43"),
        "Qrendi" => Some("44"),
        "Rabat" => Some("46"),
        "Saint Lawrence" => Some("50"),
        "San Ġwann" => Some("49"),
        "Sannat" => Some("52"),
        "Santa Luċija" => Some("53"),
        "Santa Venera" => Some("54"),
        "Siġġiewi" => Some("55"),
        "Sliema" => Some("56"),
        "St. Julian's" => Some("48"),
        "St. Paul's Bay" => Some("51"),
        "Swieqi" => Some("57"),
        "Ta' Xbiex" => Some("58"),
        "Tarxien" => Some("59"),
        "Valletta" => Some("60"),
        "Victoria" => Some("45"),
        "Xagħra" => Some("61"),
        "Xewkija" => Some("62"),
        "Xgħajra" => Some("63"),
        "Żabbar" => Some("64"),
        "Żebbuġ Gozo" => Some("65"),
        "Żebbuġ Malta" => Some("66"),
        "Żejtun" => Some("67"),
        "Żurrieq" => Some("68"),
        _ => None,
    }
}

fn moldova_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Anenii Noi District" => Some("AN"),
        "Basarabeasca District" => Some("BS"),
        "Bender Municipality" => Some("BD"),
        "Briceni District" => Some("BR"),
        "Bălți Municipality" => Some("BA"),
        "Cahul District" => Some("CA"),
        "Cantemir District" => Some("CT"),
        "Chișinău Municipality" => Some("CU"),
        "Cimișlia District" => Some("CM"),
        "Criuleni District" => Some("CR"),
        "Călărași District" => Some("CL"),
        "Căușeni District" => Some("CS"),
        "Dondușeni District" => Some("DO"),
        "Drochia District" => Some("DR"),
        "Dubăsari District" => Some("DU"),
        "Edineț District" => Some("ED"),
        "Florești District" => Some("FL"),
        "Fălești District" => Some("FA"),
        "Găgăuzia" => Some("GA"),
        "Glodeni District" => Some("GL"),
        "Hîncești District" => Some("HI"),
        "Ialoveni District" => Some("IA"),
        "Nisporeni District" => Some("NI"),
        "Ocnița District" => Some("OC"),
        "Orhei District" => Some("OR"),
        "Rezina District" => Some("RE"),
        "Rîșcani District" => Some("RI"),
        "Soroca District" => Some("SO"),
        "Strășeni District" => Some("ST"),
        "Sîngerei District" => Some("SI"),
        "Taraclia District" => Some("TA"),
        "Telenești District" => Some("TE"),
        "Transnistria Autonomous Territorial Unit" => Some("SN"),
        "Ungheni District" => Some("UN"),
        "Șoldănești District" => Some("SD"),
        "Ștefan Vodă District" => Some("SV"),
        _ => None,
    }
}

fn monaco_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Monaco" => Some("Monaco"),
        _ => None,
    }
}

fn montenegro_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Andrijevica Municipality" => Some("01"),
        "Bar Municipality" => Some("02"),
        "Berane Municipality" => Some("03"),
        "Bijelo Polje Municipality" => Some("04"),
        "Budva Municipality" => Some("05"),
        "Danilovgrad Municipality" => Some("07"),
        "Gusinje Municipality" => Some("22"),
        "Kolašin Municipality" => Some("09"),
        "Kotor Municipality" => Some("10"),
        "Mojkovac Municipality" => Some("11"),
        "Nikšić Municipality" => Some("12"),
        "Petnjica Municipality" => Some("23"),
        "Plav Municipality" => Some("13"),
        "Pljevlja Municipality" => Some("14"),
        "Plužine Municipality" => Some("15"),
        "Podgorica Municipality" => Some("16"),
        "Rožaje Municipality" => Some("17"),
        "Tivat Municipality" => Some("19"),
        "Ulcinj Municipality" => Some("20"),
        "Žabljak Municipality" => Some("21"),
        _ => None,
    }
}

fn netherlands_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Bonaire" => Some("BQ1"),
        "Drenthe" => Some("DR"),
        "Flevoland" => Some("FL"),
        "Friesland" => Some("FR"),
        "Gelderland" => Some("GE"),
        "Groningen" => Some("GR"),
        "Limburg" => Some("LI"),
        "North Brabant" => Some("NB"),
        "North Holland" => Some("NH"),
        "Overijssel" => Some("OV"),
        "Saba" => Some("BQ2"),
        "Sint Eustatius" => Some("BQ3"),
        "South Holland" => Some("ZH"),
        "Utrecht" => Some("UT"),
        "Zeeland" => Some("ZE"),
        _ => None,
    }
}

fn newzealand_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "auckland" | "tamakimakaurau" => Some("AUK"),
        "bayofplenty" | "toimoana" => Some("BOP"),
        "canterbury" | "waitaha" => Some("CAN"),
        "chathamislandsterritory" | "wharekauri" => Some("CIT"),
        "gisborne" | "tetairawhiti" => Some("GIS"),
        "hawkesbay" | "tematauamaui" => Some("HKB"),
        "manawatuwanganui" => Some("MWT"),
        "marlborough" => Some("MBH"),
        "nelson" | "whakatu" => Some("NSN"),
        "northland" | "tetaitokerau" => Some("NTL"),
        "otago" | "otakou" => Some("OTA"),
        "southland" | "tetaiaotonga" => Some("STL"),
        "taranaki" => Some("TKI"),
        "tasman" | "tetaioaorere" => Some("TAS"),
        "waikato" => Some("WKO"),
        "greaterwellington" | "tepanematuataiao" => Some("WGN"),
        "westcoast" | "tetaiopoutini" => Some("WTC"),
        _ => None,
    }
}

fn northmacedonia_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Aerodrom Municipality" => Some("01"),
        "Aračinovo Municipality" => Some("02"),
        "Berovo Municipality" => Some("03"),
        "Bitola Municipality" => Some("04"),
        "Bogdanci Municipality" => Some("05"),
        "Bogovinje Municipality" => Some("06"),
        "Bosilovo Municipality" => Some("07"),
        "Brvenica Municipality" => Some("08"),
        "Butel Municipality" => Some("09"),
        "Centar Municipality" => Some("77"),
        "Centar Župa Municipality" => Some("78"),
        "Debarca Municipality" => Some("22"),
        "Delčevo Municipality" => Some("23"),
        "Demir Hisar Municipality" => Some("25"),
        "Demir Kapija Municipality" => Some("24"),
        "Dojran Municipality" => Some("26"),
        "Dolneni Municipality" => Some("27"),
        "Drugovo Municipality" => Some("28"),
        "Gazi Baba Municipality" => Some("17"),
        "Gevgelija Municipality" => Some("18"),
        "Gjorče Petrov Municipality" => Some("29"),
        "Gostivar Municipality" => Some("19"),
        "Gradsko Municipality" => Some("20"),
        "Greater Skopje" => Some("85"),
        "Ilinden Municipality" => Some("34"),
        "Jegunovce Municipality" => Some("35"),
        "Karbinci" => Some("37"),
        "Karpoš Municipality" => Some("38"),
        "Kavadarci Municipality" => Some("36"),
        "Kisela Voda Municipality" => Some("39"),
        "Kičevo Municipality" => Some("40"),
        "Konče Municipality" => Some("41"),
        "Kočani Municipality" => Some("42"),
        "Kratovo Municipality" => Some("43"),
        "Kriva Palanka Municipality" => Some("44"),
        "Krivogaštani Municipality" => Some("45"),
        "Kruševo Municipality" => Some("46"),
        "Kumanovo Municipality" => Some("47"),
        "Lipkovo Municipality" => Some("48"),
        "Lozovo Municipality" => Some("49"),
        "Makedonska Kamenica Municipality" => Some("51"),
        "Makedonski Brod Municipality" => Some("52"),
        "Mavrovo and Rostuša Municipality" => Some("50"),
        "Mogila Municipality" => Some("53"),
        "Negotino Municipality" => Some("54"),
        "Novaci Municipality" => Some("55"),
        "Novo Selo Municipality" => Some("56"),
        "Ohrid Municipality" => Some("58"),
        "Oslomej Municipality" => Some("57"),
        "Pehčevo Municipality" => Some("60"),
        "Petrovec Municipality" => Some("59"),
        "Plasnica Municipality" => Some("61"),
        "Prilep Municipality" => Some("62"),
        "Probištip Municipality" => Some("63"),
        "Radoviš Municipality" => Some("64"),
        "Rankovce Municipality" => Some("65"),
        "Resen Municipality" => Some("66"),
        "Rosoman Municipality" => Some("67"),
        "Saraj Municipality" => Some("68"),
        "Sopište Municipality" => Some("70"),
        "Staro Nagoričane Municipality" => Some("71"),
        "Struga Municipality" => Some("72"),
        "Strumica Municipality" => Some("73"),
        "Studeničani Municipality" => Some("74"),
        "Sveti Nikole Municipality" => Some("69"),
        "Tearce Municipality" => Some("75"),
        "Tetovo Municipality" => Some("76"),
        "Valandovo Municipality" => Some("10"),
        "Vasilevo Municipality" => Some("11"),
        "Veles Municipality" => Some("13"),
        "Vevčani Municipality" => Some("12"),
        "Vinica Municipality" => Some("14"),
        "Vraneštica Municipality" => Some("15"),
        "Vrapčište Municipality" => Some("16"),
        "Zajas Municipality" => Some("31"),
        "Zelenikovo Municipality" => Some("32"),
        "Zrnovci Municipality" => Some("33"),
        "Čair Municipality" => Some("79"),
        "Čaška Municipality" => Some("80"),
        "Češinovo-Obleševo Municipality" => Some("81"),
        "Čučer-Sandevo Municipality" => Some("82"),
        "Štip Municipality" => Some("83"),
        "Šuto Orizari Municipality" => Some("84"),
        "Želino Municipality" => Some("30"),
        _ => None,
    }
}

fn norway_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Akershus" => Some("02"),
        "Buskerud" => Some("06"),
        "Finnmark" => Some("20"),
        "Hedmark" => Some("04"),
        "Hordaland" => Some("12"),
        "Jan Mayen" => Some("22"),
        "Møre og Romsdal" => Some("15"),
        "Nord-Trøndelag" => Some("17"),
        "Nordland" => Some("18"),
        "Oppland" => Some("05"),
        "Oslo" => Some("03"),
        "Rogaland" => Some("11"),
        "Sogn og Fjordane" => Some("14"),
        "Svalbard" => Some("21"),
        "Sør-Trøndelag" => Some("16"),
        "Telemark" => Some("08"),
        "Troms" => Some("19"),
        "Trøndelag" => Some("50"),
        "Vest-Agder" => Some("10"),
        "Vestfold" => Some("07"),
        "Østfold" => Some("01"),
        _ => None,
    }
}

fn poland_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Greater Poland" => Some("30"),
        "Holy Cross" => Some("26"),
        "Kuyavia-Pomerania" => Some("04"),
        "Lesser Poland" => Some("12"),
        "Lower Silesia" => Some("02"),
        "Lublin" => Some("06"),
        "Lubusz" => Some("08"),
        "Łódź" => Some("10"),
        "Mazovia" => Some("14"),
        "Podlaskie" => Some("20"),
        "Pomerania" => Some("22"),
        "Silesia" => Some("24"),
        "Subcarpathia" => Some("18"),
        "Upper Silesia" => Some("16"),
        "Warmia-Masuria" => Some("28"),
        "West Pomerania" => Some("32"),
        _ => None,
    }
}

fn portugal_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Aveiro District" => Some("01"),
        "Azores" => Some("20"),
        "Beja District" => Some("02"),
        "Braga District" => Some("03"),
        "Bragança District" => Some("04"),
        "Castelo Branco District" => Some("05"),
        "Coimbra District" => Some("06"),
        "Faro District" => Some("08"),
        "Guarda District" => Some("09"),
        "Leiria District" => Some("10"),
        "Lisbon District" => Some("11"),
        "Madeira" => Some("30"),
        "Portalegre District" => Some("12"),
        "Porto District" => Some("13"),
        "Santarém District" => Some("14"),
        "Setúbal District" => Some("15"),
        "Viana do Castelo District" => Some("16"),
        "Vila Real District" => Some("17"),
        "Viseu District" => Some("18"),
        "Évora District" => Some("07"),
        _ => None,
    }
}

fn spain_state_code(state: &str) -> Option<&'static str> {
    match state {
        "A Coruña Province" => Some("C"),
        "Albacete Province" => Some("AB"),
        "Alicante Province" => Some("A"),
        "Almería Province" => Some("AL"),
        "Andalusia" => Some("AN"),
        "Araba / Álava" => Some("VI"),
        "Aragon" => Some("AR"),
        "Badajoz Province" => Some("BA"),
        "Balearic Islands" => Some("PM"),
        "Barcelona Province" => Some("B"),
        "Basque Country" => Some("PV"),
        "Biscay" => Some("BI"),
        "Burgos Province" => Some("BU"),
        "Canary Islands" => Some("CN"),
        "Cantabria" => Some("S"),
        "Castellón Province" => Some("CS"),
        "Castile and León" => Some("CL"),
        "Castilla-La Mancha" => Some("CM"),
        "Catalonia" => Some("CT"),
        "Ceuta" => Some("CE"),
        "Ciudad Real Province" => Some("CR"),
        "Community of Madrid" => Some("MD"),
        "Cuenca Province" => Some("CU"),
        "Cáceres Province" => Some("CC"),
        "Cádiz Province" => Some("CA"),
        "Córdoba Province" => Some("CO"),
        "Extremadura" => Some("EX"),
        "Galicia" => Some("GA"),
        "Gipuzkoa" => Some("SS"),
        "Girona Province" => Some("GI"),
        "Granada Province" => Some("GR"),
        "Guadalajara Province" => Some("GU"),
        "Huelva Province" => Some("H"),
        "Huesca Province" => Some("HU"),
        "Jaén Province" => Some("J"),
        "La Rioja" => Some("RI"),
        "Las Palmas Province" => Some("GC"),
        "León Province" => Some("LE"),
        "Lleida Province" => Some("L"),
        "Lugo Province" => Some("LU"),
        "Madrid Province" => Some("M"),
        "Melilla" => Some("ML"),
        "Murcia Province" => Some("MU"),
        "Málaga Province" => Some("MA"),
        "Navarre" => Some("NC"),
        "Ourense Province" => Some("OR"),
        "Palencia Province" => Some("P"),
        "Pontevedra Province" => Some("PO"),
        "Province of Asturias" => Some("O"),
        "Province of Ávila" => Some("AV"),
        "Region of Murcia" => Some("MC"),
        "Salamanca Province" => Some("SA"),
        "Santa Cruz de Tenerife Province" => Some("TF"),
        "Segovia Province" => Some("SG"),
        "Seville Province" => Some("SE"),
        "Soria Province" => Some("SO"),
        "Tarragona Province" => Some("T"),
        "Teruel Province" => Some("TE"),
        "Toledo Province" => Some("TO"),
        "Valencia Province" => Some("V"),
        "Valencian Community" => Some("VC"),
        "Valladolid Province" => Some("VA"),
        "Zamora Province" => Some("ZA"),
        "Zaragoza Province" => Some("Z"),
        _ => None,
    }
}

fn switzerland_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Aargau" => Some("AG"),
        "Appenzell Ausserrhoden" => Some("AR"),
        "Appenzell Innerrhoden" => Some("AI"),
        "Basel-Landschaft" => Some("BL"),
        "Canton of Fribourg" => Some("FR"),
        "Canton of Geneva" => Some("GE"),
        "Canton of Jura" => Some("JU"),
        "Canton of Lucerne" => Some("LU"),
        "Canton of Neuchâtel" => Some("NE"),
        "Canton of Schaffhausen" => Some("SH"),
        "Canton of Solothurn" => Some("SO"),
        "Canton of St. Gallen" => Some("SG"),
        "Canton of Valais" => Some("VS"),
        "Canton of Vaud" => Some("VD"),
        "Canton of Zug" => Some("ZG"),
        "Glarus" => Some("GL"),
        "Graubünden" => Some("GR"),
        "Nidwalden" => Some("NW"),
        "Obwalden" => Some("OW"),
        "Schwyz" => Some("SZ"),
        "Thurgau" => Some("TG"),
        "Ticino" => Some("TI"),
        "Uri" => Some("UR"),
        "canton of Bern" => Some("BE"),
        "canton of Zürich" => Some("ZH"),
        _ => None,
    }
}

fn unitedkingdom_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Aberdeen" => Some("ABE"),
        "Aberdeenshire" => Some("ABD"),
        "Angus" => Some("ANS"),
        "Antrim" => Some("ANT"),
        "Antrim and Newtownabbey" => Some("ANN"),
        "Ards" => Some("ARD"),
        "Ards and North Down" => Some("AND"),
        "Argyll and Bute" => Some("AGB"),
        "Armagh City and District Council" => Some("ARM"),
        "Armagh, Banbridge and Craigavon" => Some("ABC"),
        "Ascension Island" => Some("SH-AC"),
        "Ballymena Borough" => Some("BLA"),
        "Ballymoney" => Some("BLY"),
        "Banbridge" => Some("BNB"),
        "Barnsley" => Some("BNS"),
        "Bath and North East Somerset" => Some("BAS"),
        "Bedford" => Some("BDF"),
        "Belfast district" => Some("BFS"),
        "Birmingham" => Some("BIR"),
        "Blackburn with Darwen" => Some("BBD"),
        "Blackpool" => Some("BPL"),
        "Blaenau Gwent County Borough" => Some("BGW"),
        "Bolton" => Some("BOL"),
        "Bournemouth" => Some("BMH"),
        "Bracknell Forest" => Some("BRC"),
        "Bradford" => Some("BRD"),
        "Bridgend County Borough" => Some("BGE"),
        "Brighton and Hove" => Some("BNH"),
        "Buckinghamshire" => Some("BKM"),
        "Bury" => Some("BUR"),
        "Caerphilly County Borough" => Some("CAY"),
        "Calderdale" => Some("CLD"),
        "Cambridgeshire" => Some("CAM"),
        "Carmarthenshire" => Some("CMN"),
        "Carrickfergus Borough Council" => Some("CKF"),
        "Castlereagh" => Some("CSR"),
        "Causeway Coast and Glens" => Some("CCG"),
        "Central Bedfordshire" => Some("CBF"),
        "Ceredigion" => Some("CGN"),
        "Cheshire East" => Some("CHE"),
        "Cheshire West and Chester" => Some("CHW"),
        "City and County of Cardiff" => Some("CRF"),
        "City and County of Swansea" => Some("SWA"),
        "City of Bristol" => Some("BST"),
        "City of Derby" => Some("DER"),
        "City of Kingston upon Hull" => Some("KHL"),
        "City of Leicester" => Some("LCE"),
        "City of London" => Some("LND"),
        "City of Nottingham" => Some("NGM"),
        "City of Peterborough" => Some("PTE"),
        "City of Plymouth" => Some("PLY"),
        "City of Portsmouth" => Some("POR"),
        "City of Southampton" => Some("STH"),
        "City of Stoke-on-Trent" => Some("STE"),
        "City of Sunderland" => Some("SND"),
        "City of Westminster" => Some("WSM"),
        "City of Wolverhampton" => Some("WLV"),
        "City of York" => Some("YOR"),
        "Clackmannanshire" => Some("CLK"),
        "Coleraine Borough Council" => Some("CLR"),
        "Conwy County Borough" => Some("CWY"),
        "Cookstown District Council" => Some("CKT"),
        "Cornwall" => Some("CON"),
        "County Durham" => Some("DUR"),
        "Coventry" => Some("COV"),
        "Craigavon Borough Council" => Some("CGV"),
        "Cumbria" => Some("CMA"),
        "Darlington" => Some("DAL"),
        "Denbighshire" => Some("DEN"),
        "Derbyshire" => Some("DBY"),
        "Derry City and Strabane" => Some("DRS"),
        "Derry City Council" => Some("DRY"),
        "Devon" => Some("DEV"),
        "Doncaster" => Some("DNC"),
        "Dorset" => Some("DOR"),
        "Down District Council" => Some("DOW"),
        "Dudley" => Some("DUD"),
        "Dumfries and Galloway" => Some("DGY"),
        "Dundee" => Some("DND"),
        "Dungannon and South Tyrone Borough Council" => Some("DGN"),
        "East Ayrshire" => Some("EAY"),
        "East Dunbartonshire" => Some("EDU"),
        "East Lothian" => Some("ELN"),
        "East Renfrewshire" => Some("ERW"),
        "East Riding of Yorkshire" => Some("ERY"),
        "East Sussex" => Some("ESX"),
        "Edinburgh" => Some("EDH"),
        "England" => Some("ENG"),
        "Essex" => Some("ESS"),
        "Falkirk" => Some("FAL"),
        "Fermanagh and Omagh" => Some("FMO"),
        "Fermanagh District Council" => Some("FER"),
        "Fife" => Some("FIF"),
        "Flintshire" => Some("FLN"),
        "Gateshead" => Some("GAT"),
        "Glasgow" => Some("GLG"),
        "Gloucestershire" => Some("GLS"),
        "Gwynedd" => Some("GWN"),
        "Halton" => Some("HAL"),
        "Hampshire" => Some("HAM"),
        "Hartlepool" => Some("HPL"),
        "Herefordshire" => Some("HEF"),
        "Hertfordshire" => Some("HRT"),
        "Highland" => Some("HLD"),
        "Inverclyde" => Some("IVC"),
        "Isle of Wight" => Some("IOW"),
        "Isles of Scilly" => Some("IOS"),
        "Kent" => Some("KEN"),
        "Kirklees" => Some("KIR"),
        "Knowsley" => Some("KWL"),
        "Lancashire" => Some("LAN"),
        "Larne Borough Council" => Some("LRN"),
        "Leeds" => Some("LDS"),
        "Leicestershire" => Some("LEC"),
        "Limavady Borough Council" => Some("LMV"),
        "Lincolnshire" => Some("LIN"),
        "Lisburn and Castlereagh" => Some("LBC"),
        "Lisburn City Council" => Some("LSB"),
        "Liverpool" => Some("LIV"),
        "London Borough of Barking and Dagenham" => Some("BDG"),
        "London Borough of Barnet" => Some("BNE"),
        "London Borough of Bexley" => Some("BEX"),
        "London Borough of Brent" => Some("BEN"),
        "London Borough of Bromley" => Some("BRY"),
        "London Borough of Camden" => Some("CMD"),
        "London Borough of Croydon" => Some("CRY"),
        "London Borough of Ealing" => Some("EAL"),
        "London Borough of Enfield" => Some("ENF"),
        "London Borough of Hackney" => Some("HCK"),
        "London Borough of Hammersmith and Fulham" => Some("HMF"),
        "London Borough of Haringey" => Some("HRY"),
        "London Borough of Harrow" => Some("HRW"),
        "London Borough of Havering" => Some("HAV"),
        "London Borough of Hillingdon" => Some("HIL"),
        "London Borough of Hounslow" => Some("HNS"),
        "London Borough of Islington" => Some("ISL"),
        "London Borough of Lambeth" => Some("LBH"),
        "London Borough of Lewisham" => Some("LEW"),
        "London Borough of Merton" => Some("MRT"),
        "London Borough of Newham" => Some("NWM"),
        "London Borough of Redbridge" => Some("RDB"),
        "London Borough of Richmond upon Thames" => Some("RIC"),
        "London Borough of Southwark" => Some("SWK"),
        "London Borough of Sutton" => Some("STN"),
        "London Borough of Tower Hamlets" => Some("TWH"),
        "London Borough of Waltham Forest" => Some("WFT"),
        "London Borough of Wandsworth" => Some("WND"),
        "Magherafelt District Council" => Some("MFT"),
        "Manchester" => Some("MAN"),
        "Medway" => Some("MDW"),
        "Merthyr Tydfil County Borough" => Some("MTY"),
        "Metropolitan Borough of Wigan" => Some("WGN"),
        "Mid and East Antrim" => Some("MEA"),
        "Mid Ulster" => Some("MUL"),
        "Middlesbrough" => Some("MDB"),
        "Midlothian" => Some("MLN"),
        "Milton Keynes" => Some("MIK"),
        "Monmouthshire" => Some("MON"),
        "Moray" => Some("MRY"),
        "Moyle District Council" => Some("MYL"),
        "Neath Port Talbot County Borough" => Some("NTL"),
        "Newcastle upon Tyne" => Some("NET"),
        "Newport" => Some("NWP"),
        "Newry and Mourne District Council" => Some("NYM"),
        "Newry, Mourne and Down" => Some("NMD"),
        "Newtownabbey Borough Council" => Some("NTA"),
        "Norfolk" => Some("NFK"),
        "North Ayrshire" => Some("NAY"),
        "North Down Borough Council" => Some("NDN"),
        "North East Lincolnshire" => Some("NEL"),
        "North Lanarkshire" => Some("NLK"),
        "North Lincolnshire" => Some("NLN"),
        "North Somerset" => Some("NSM"),
        "North Tyneside" => Some("NTY"),
        "North Yorkshire" => Some("NYK"),
        "Northamptonshire" => Some("NTH"),
        "Northern Ireland" => Some("NIR"),
        "Northumberland" => Some("NBL"),
        "Nottinghamshire" => Some("NTT"),
        "Oldham" => Some("OLD"),
        "Omagh District Council" => Some("OMH"),
        "Orkney Islands" => Some("ORK"),
        "Outer Hebrides" => Some("ELS"),
        "Oxfordshire" => Some("OXF"),
        "Pembrokeshire" => Some("PEM"),
        "Perth and Kinross" => Some("PKN"),
        "Poole" => Some("POL"),
        "Powys" => Some("POW"),
        "Reading" => Some("RDG"),
        "Redcar and Cleveland" => Some("RCC"),
        "Renfrewshire" => Some("RFW"),
        "Rhondda Cynon Taf" => Some("RCT"),
        "Rochdale" => Some("RCH"),
        "Rotherham" => Some("ROT"),
        "Royal Borough of Greenwich" => Some("GRE"),
        "Royal Borough of Kensington and Chelsea" => Some("KEC"),
        "Royal Borough of Kingston upon Thames" => Some("KTT"),
        "Rutland" => Some("RUT"),
        "Saint Helena" => Some("SH-HL"),
        "Salford" => Some("SLF"),
        "Sandwell" => Some("SAW"),
        "Scotland" => Some("SCT"),
        "Scottish Borders" => Some("SCB"),
        "Sefton" => Some("SFT"),
        "Sheffield" => Some("SHF"),
        "Shetland Islands" => Some("ZET"),
        "Shropshire" => Some("SHR"),
        "Slough" => Some("SLG"),
        "Solihull" => Some("SOL"),
        "Somerset" => Some("SOM"),
        "South Ayrshire" => Some("SAY"),
        "South Gloucestershire" => Some("SGC"),
        "South Lanarkshire" => Some("SLK"),
        "South Tyneside" => Some("STY"),
        "Southend-on-Sea" => Some("SOS"),
        "St Helens" => Some("SHN"),
        "Staffordshire" => Some("STS"),
        "Stirling" => Some("STG"),
        "Stockport" => Some("SKP"),
        "Stockton-on-Tees" => Some("STT"),
        "Strabane District Council" => Some("STB"),
        "Suffolk" => Some("SFK"),
        "Surrey" => Some("SRY"),
        "Swindon" => Some("SWD"),
        "Tameside" => Some("TAM"),
        "Telford and Wrekin" => Some("TFW"),
        "Thurrock" => Some("THR"),
        "Torbay" => Some("TOB"),
        "Torfaen" => Some("TOF"),
        "Trafford" => Some("TRF"),
        "United Kingdom" => Some("UKM"),
        "Vale of Glamorgan" => Some("VGL"),
        "Wakefield" => Some("WKF"),
        "Wales" => Some("WLS"),
        "Walsall" => Some("WLL"),
        "Warrington" => Some("WRT"),
        "Warwickshire" => Some("WAR"),
        "West Berkshire" => Some("WBK"),
        "West Dunbartonshire" => Some("WDU"),
        "West Lothian" => Some("WLN"),
        "West Sussex" => Some("WSX"),
        "Wiltshire" => Some("WIL"),
        "Windsor and Maidenhead" => Some("WNM"),
        "Wirral" => Some("WRL"),
        "Wokingham" => Some("WOK"),
        "Worcestershire" => Some("WOR"),
        "Wrexham County Borough" => Some("WRX"),
        _ => None,
    }
}

fn brazil_state_code(state: &str) -> Option<&'static str> {
    match state {
        "Acre" => Some("AC"),
        "Alagoas" => Some("AL"),
        "Amapá" => Some("AP"),
        "Amazonas" => Some("AM"),
        "Bahia" => Some("BA"),
        "Ceará" => Some("CE"),
        "Distrito Federal" => Some("DF"),
        "Espírito Santo" => Some("ES"),
        "Goiás" => Some("GO"),
        "Maranhão" => Some("MA"),
        "Mato Grosso" => Some("MT"),
        "Mato Grosso do Sul" => Some("MS"),
        "Minas Gerais" => Some("MG"),
        "Pará" => Some("PA"),
        "Paraíba" => Some("PB"),
        "Paraná" => Some("PR"),
        "Pernambuco" => Some("PE"),
        "Piauí" => Some("PI"),
        "Rio de Janeiro" => Some("RJ"),
        "Rio Grande do Norte" => Some("RN"),
        "Rio Grande do Sul" => Some("RS"),
        "Rondônia" => Some("RO"),
        "Roraima" => Some("RR"),
        "Santa Catarina" => Some("SC"),
        "São Paulo" => Some("SP"),
        "Sergipe" => Some("SE"),
        "Tocantins" => Some("TO"),
        _ => None,
    }
}

fn australia_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "newsouthwales" => Some("NSW"),
        "queensland" => Some("QLD"),
        "southaustralia" => Some("SA"),
        "westernaustralia" => Some("WA"),
        "victoria" => Some("VIC"),
        "northernterritory" => Some("NT"),
        "australiancapitalterritory" => Some("ACT"),
        "tasmania" => Some("TAS"),
        _ => None,
    }
}

fn singapore_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "centralsingapore" => Some("01"),
        "northeast" => Some("02"),
        "northwest" => Some("03"),
        "southeast" => Some("04"),
        "southwest" => Some("05"),
        _ => None,
    }
}

fn thailand_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "amnatcharoen" => Some("37"),
        "angthong" => Some("15"),
        "bangkok" => Some("10"),
        "buengkan" => Some("38"),
        "buriram" => Some("31"),
        "chachoengsao" => Some("24"),
        "chainat" => Some("18"),
        "chaiyaphum" => Some("36"),
        "chanthaburi" => Some("22"),
        "chiangmai" => Some("50"),
        "chiangrai" => Some("57"),
        "chonburi" => Some("20"),
        "chumphon" => Some("86"),
        "kalasin" => Some("46"),
        "kamphaengphet" => Some("62"),
        "kanchanaburi" => Some("71"),
        "khonkaen" => Some("40"),
        "krabi" => Some("81"),
        "lampang" => Some("52"),
        "lamphun" => Some("51"),
        "loei" => Some("42"),
        "lopburi" => Some("16"),
        "maehongson" => Some("58"),
        "mahasarakham" => Some("44"),
        "mukdahan" => Some("49"),
        "nakhonnayok" => Some("26"),
        "nakhonpathom" => Some("73"),
        "nakhonphanom" => Some("48"),
        "nakhonratchasima" => Some("30"),
        "nakhonsawan" => Some("60"),
        "nakhonsithammarat" => Some("80"),
        "nan" => Some("55"),
        "narathiwat" => Some("96"),
        "nongbualamphu" => Some("39"),
        "nongkhai" => Some("43"),
        "nonthaburi" => Some("12"),
        "pathumthani" => Some("13"),
        "pattani" => Some("94"),
        "phangnga" => Some("82"),
        "phatthalung" => Some("93"),
        "phayao" => Some("56"),
        "phatthaya" => Some("S"),
        "phetchabun" => Some("67"),
        "phetchaburi" => Some("76"),
        "phichit" => Some("66"),
        "phitsanulok" => Some("65"),
        "phrae" => Some("54"),
        "phuket" => Some("83"),
        "prachinburi" => Some("25"),
        "phranakhonsiayutthaya" => Some("14"),
        "prachuapkhirikhan" => Some("77"),
        "ranong" => Some("85"),
        "ratchaburi" => Some("70"),
        "rayong" => Some("21"),
        "roiet" => Some("45"),
        "sakaeo" => Some("27"),
        "sakonnakhon" => Some("47"),
        "samutprakan" => Some("11"),
        "samutsakhon" => Some("74"),
        "samutsongkhram" => Some("75"),
        "saraburi" => Some("19"),
        "satun" => Some("91"),
        "sisaket" => Some("33"),
        "singburi" => Some("17"),
        "songkhla" => Some("90"),
        "sukhothai" => Some("64"),
        "suphanburi" => Some("72"),
        "suratthani" => Some("84"),
        "surin" => Some("32"),
        "tak" => Some("63"),
        "trang" => Some("92"),
        "trat" => Some("23"),
        "ubonratchathani" => Some("34"),
        "udonthani" => Some("41"),
        "uthaithani" => Some("61"),
        "uttaradit" => Some("53"),
        "yala" => Some("95"),
        "yasothon" => Some("35"),
        _ => None,
    }
}

fn philippines_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "abra" => Some("ABR"),
        "agusandelnorte" | "hilagangagusan" => Some("AGN"),
        "agusandelsur" | "timogagusan" => Some("AGS"),
        "aklan" => Some("AKL"),
        "albay" => Some("ALB"),
        "antique" | "antike" => Some("ANT"),
        "apayao" | "apayaw" => Some("APA"),
        "aurora" => Some("AUR"),
        "autonomousregioninmuslimmindanao" | "nagsasarilingrehiyonngmuslimsamindanaw" => Some("14"),
        "basilan" => Some("BAS"),
        "bataan" => Some("BAN"),
        "batanes" => Some("BTN"),
        "batangas" => Some("BTG"),
        "benguet" | "benget" => Some("BEN"),
        "bicol" | "rehiyonngbikol" => Some("05"),
        "biliran" => Some("BIL"),
        "bohol" => Some("BOH"),
        "bukidnon" => Some("BUK"),
        "bulacan" | "bulakan" => Some("BUL"),
        "cagayan" | "kagayan" => Some("CAG"),
        "cagayanvalley" | "rehiyonnglambakngkagayan" => Some("02"),
        "calabarzon" | "rehiyonngcalabarzon" => Some("40"),
        "camarinesnorte" | "hilagangkamarines" => Some("CAN"),
        "camarinessur" | "timogkamarines" => Some("CAS"),
        "camiguin" | "kamigin" => Some("CAM"),
        "capiz" | "kapis" => Some("CAP"),
        "caraga" | "rehiyonngkaraga" => Some("13"),
        "catanduanes" | "katanduanes" => Some("CAT"),
        "cavite" | "kabite" => Some("CAV"),
        "cebu" | "sebu" => Some("CEB"),
        "centralluzon" | "rehiyonnggitnangluzon" => Some("03"),
        "centralvisayas" | "rehiyonnggitnangbisaya" => Some("07"),
        "cordilleraadministrativeregion" | "rehiyonngadministratibongkordilyera" => Some("15"),
        "cotabato" | "kotabato" => Some("NCO"),
        "davao" | "rehiyonngdabaw" => Some("11"),
        "davaooccidental" | "kanlurangdabaw" => Some("DVO"),
        "davaooriental" | "silangangdabaw" => Some("DAO"),
        "davaodeoro" => Some("COM"),
        "davaodelnorte" | "hilagangdabaw" => Some("DAV"),
        "davaodelsur" | "timogdabaw" => Some("DAS"),
        "dinagatislands" | "pulongdinagat" => Some("DIN"),
        "easternsamar" | "silangangsamar" => Some("EAS"),
        "easternvisayas" | "rehiyonngsilangangbisaya" => Some("08"),
        "guimaras" | "gimaras" => Some("GUI"),
        "hilagangiloko" | "ilocosnorte" => Some("ILN"),
        "hilaganglanaw" | "lanaodelnorte" => Some("LAN"),
        "hilagangmagindanaw" | "maguindanaodelnorte" => Some("MGN"),
        "hilagangsamar" | "northernsamar" => Some("NSA"),
        "hilagangsambuwangga" | "zamboangadelnorte" => Some("ZAN"),
        "hilagangsurigaw" | "surigaodelnorte" => Some("SUN"),
        "ifugao" | "ipugaw" => Some("IFU"),
        "ilocos" | "rehiyonngiloko" => Some("01"),
        "ilocossur" | "timogiloko" => Some("ILS"),
        "iloilo" | "iloylo" => Some("ILI"),
        "isabela" => Some("ISA"),
        "kalinga" => Some("KAL"),
        "kanlurangmindoro" | "mindorooccidental" => Some("MDC"),
        "kanlurangmisamis" | "misamisoriental" => Some("MSC"),
        "kanlurangnegros" | "negrosoccidental" => Some("NEC"),
        "katimogangleyte" | "southernleyte" => Some("SLE"),
        "keson" | "quezon" => Some("QUE"),
        "kirino" | "quirino" => Some("QUI"),
        "launion" => Some("LUN"),
        "laguna" => Some("LAG"),
        "lalawigangbulubundukin" | "mountainprovince" => Some("MOU"),
        "lanaodelsur" | "timoglanaw" => Some("LAS"),
        "leyte" => Some("LEY"),
        "maguidanaodelsur" | "timogmaguindanao" => Some("MGS"),
        "marinduque" => Some("MAD"),
        "masbate" => Some("MAS"),
        "mimaropa" | "rehiyonngmimaropa" => Some("41"),
        "mindorooriental" | "silingangmindoro" => Some("MDR"),
        "misamisoccidental" | "silingangmisamis" => Some("MSR"),
        "nationalcapitalregion" | "pambansangpunonglungsod" => Some("00"),
        "negrosoriental" | "silingangnegros" => Some("NER"),
        "northernmindanao" | "rehiyonnghilagangmindanao" => Some("10"),
        "nuevaecija" | "nuwevaesiha" => Some("NUE"),
        "nuevavizcaya" => Some("NUV"),
        "palawan" => Some("PLW"),
        "pampanga" => Some("PAM"),
        "pangasinan" => Some("PAN"),
        "rehiyonngkanlurangbisaya" | "westernvisayas" => Some("06"),
        "rehiyonngsoccsksargen" | "soccsksargen" => Some("12"),
        "rehiyonngtangwayngsambuwangga" | "zamboangapeninsula" => Some("09"),
        "risal" | "rizal" => Some("RIZ"),
        "romblon" => Some("ROM"),
        "samar" => Some("WSA"),
        "sambales" | "zambales" => Some("ZMB"),
        "sambuwanggasibugay" | "zamboangasibugay" => Some("ZSI"),
        "sarangani" => Some("SAR"),
        "siquijor" | "sikihor" => Some("SIG"),
        "sorsogon" => Some("SOR"),
        "southcotabato" | "timogkotabato" => Some("SCO"),
        "sultankudarat" => Some("SUK"),
        "sulu" => Some("SLU"),
        "surigaodelsur" | "timogsurigaw" => Some("SUR"),
        "tarlac" => Some("TAR"),
        "tawitawi" => Some("TAW"),
        "timogsambuwangga" | "zamboangadelsur" => Some("ZAS"),
        _ => None,
    }
}

fn india_state_code(state: &str) -> Option<&'static str> {
    match normalize_state_name(state).as_str() {
        "andamanandnicobarislands" => Some("AN"),
        "andhrapradesh" => Some("AP"),
        "arunachalpradesh" => Some("AR"),
        "assam" => Some("AS"),
        "bihar" => Some("BR"),
        "chandigarh" => Some("CH"),
        "chhattisgarh" => Some("CG"),
        "dadraandnagarhavelianddamananddiu" => Some("DH"),
        "delhi" => Some("DL"),
        "goa" => Some("GA"),
        "gujarat" => Some("GJ"),
        "haryana" => Some("HR"),
        "himachalpradesh" => Some("HP"),
        "jammuandkashmir" => Some("JK"),
        "jharkhand" => Some("JH"),
        "karnataka" => Some("KA"),
        "kerala" => Some("KL"),
        "ladakh" => Some("LA"),
        "lakshadweep" => Some("LD"),
        "madhyapradesh" => Some("MP"),
        "maharashtra" => Some("MH"),
        "manipur" => Some("MN"),
        "meghalaya" => Some("ML"),
        "mizoram" => Some("MZ"),
        "nagaland" => Some("NL"),
        "odisha" => Some("OD"),
        "puducherry" | "pondicherry" => Some("PY"),
        "punjab" => Some("PB"),
        "rajasthan" => Some("RJ"),
        "sikkim" => Some("SK"),
        "tamilnadu" => Some("TN"),
        "telangana" => Some("TG"),
        "tripura" => Some("TR"),
        "uttarpradesh" => Some("UP"),
        "uttarakhand" => Some("UK"),
        "westbengal" => Some("WB"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use common_enums::CountryAlpha2;

    use super::convert_state_to_code;

    #[test]
    fn converts_exact_match_state_names() {
        assert_eq!(
            convert_state_to_code(CountryAlpha2::GB, "Lancashire"),
            Some("LAN")
        );
        assert_eq!(
            convert_state_to_code(CountryAlpha2::DE, "Bavaria"),
            Some("BY")
        );
        assert_eq!(
            convert_state_to_code(CountryAlpha2::FR, "Île-de-France"),
            Some("IDF")
        );
    }

    #[test]
    fn converts_normalized_state_names() {
        assert_eq!(
            convert_state_to_code(CountryAlpha2::AU, "New South Wales"),
            Some("NSW")
        );
        assert_eq!(
            convert_state_to_code(CountryAlpha2::JP, "Tōkyō"),
            Some("13")
        );
    }

    #[test]
    fn returns_none_for_unknown_state_or_country() {
        assert_eq!(convert_state_to_code(CountryAlpha2::GB, "Atlantis"), None);
        assert_eq!(convert_state_to_code(CountryAlpha2::GB, "LAN"), None);
        assert_eq!(convert_state_to_code(CountryAlpha2::AE, "Dubai"), None);
    }
}
