//! Source-level lint tests for typed connector observability.
//!
//! These tests scan connector source files to verify that manual implementations
//! of key trait methods include the required typed serialization calls.
//! They run as `cargo test` and fail CI if a connector bypasses the pattern.

#[cfg(test)]
#[allow(clippy::unwrap_used)]
#[allow(clippy::expect_used)]
#[allow(clippy::panic)]
mod tests {
    use std::{
        fs,
        path::{Path, PathBuf},
    };

    /// Root of the connector-integration crate source.
    fn crate_src_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src")
    }

    /// Collect all `.rs` files under a directory, recursively.
    fn collect_rs_files(dir: &Path) -> Vec<PathBuf> {
        let mut files = Vec::new();
        if !dir.is_dir() {
            return files;
        }
        for entry in fs::read_dir(dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.is_dir() {
                files.extend(collect_rs_files(&path));
            } else if path.extension().is_some_and(|e| e == "rs") {
                files.push(path);
            }
        }
        files
    }

    /// All connector source directories to scan.
    fn connector_dirs() -> Vec<PathBuf> {
        let root = crate_src_root();
        vec![
            root.join("connectors"),
            root.join("payout_connectors"),
            root.join("surcharge_connectors"),
            root.join("authenticator_connectors"),
        ]
    }

    /// Extract the text of each function body for `fn <fn_name>` occurrences
    /// in the given source. Returns a vec of (line_number, body_text) for each
    /// occurrence. Uses brace-counting to find the function body.
    fn extract_fn_bodies(source: &str, fn_name: &str) -> Vec<(usize, String)> {
        let pattern = format!("fn {fn_name}");
        let mut results = Vec::new();
        let lines: Vec<&str> = source.lines().collect();

        for (i, line) in lines.iter().enumerate() {
            if !line.contains(&pattern) {
                continue;
            }
            // Find the opening brace
            let mut brace_depth = 0;
            let mut body_started = false;
            let mut body = String::new();

            for l in lines.get(i..).unwrap_or_default() {
                for ch in l.chars() {
                    if ch == '{' {
                        if brace_depth == 0 {
                            body_started = true;
                        }
                        brace_depth += 1;
                    } else if ch == '}' {
                        brace_depth -= 1;
                        if brace_depth == 0 && body_started {
                            // Include this closing line
                            body.push_str(l);
                            body.push('\n');
                            results.push((i + 1, body.clone()));
                            break;
                        }
                    }
                }
                if brace_depth == 0 && body_started {
                    break;
                }
                if body_started {
                    body.push_str(l);
                    body.push('\n');
                }
            }
        }
        results
    }

    /// Check: manual `handle_response_v2` implementations must call
    /// `set_typed_connector_response`.
    ///
    /// The macro-generated version (in macros.rs) already does this.
    /// Manual overrides must do it explicitly.
    #[test]
    fn lint_handle_response_v2_sets_typed_response() {
        let macros_file = crate_src_root().join("connectors").join("macros.rs");
        let mut violations: Vec<String> = Vec::new();

        for dir in connector_dirs() {
            for file in collect_rs_files(&dir) {
                // Skip the macro definition file itself
                if file == macros_file {
                    continue;
                }
                let source = fs::read_to_string(&file).unwrap();

                // Skip files that don't have manual handle_response_v2
                if !source.contains("fn handle_response_v2") {
                    continue;
                }

                // Skip if the file only has macro-generated handle_response_v2
                // (the macro invocation line contains `expand_fn_handle_response`)
                let bodies = extract_fn_bodies(&source, "handle_response_v2");

                for (line, body) in &bodies {
                    // The macro-expanded version contains `bridge.response` — skip those
                    // because they're generated by expand_fn_handle_response macro
                    // and already include set_typed_connector_response.
                    // We only care about truly manual implementations.
                    if body.contains("expand_fn_handle_response") {
                        continue;
                    }

                    // `set_typed_response!` macro expands to include
                    // `set_typed_connector_response`, so accept it too.
                    if !body.contains("set_typed_connector_response")
                        && !body.contains("set_typed_response!")
                    {
                        let rel = file
                            .strip_prefix(crate_src_root().parent().unwrap())
                            .unwrap_or(&file);
                        violations.push(format!(
                            "  {}:{} — handle_response_v2 does not call set_typed_connector_response",
                            rel.display(),
                            line
                        ));
                    }
                }
            }
        }

        if !violations.is_empty() {
            panic!(
                "\n\nTyped observability lint failure: handle_response_v2 implementations \
                 must call `set_typed_connector_response` on the result's resource_common_data.\n\
                 \nViolations:\n{}\n",
                violations.join("\n")
            );
        }
    }

    /// Check: manual `build_error_response` implementations must call
    /// `serialize_typed_connector_payload` to produce the typed error value.
    ///
    /// The return type is `(ErrorResponse, Option<String>)` — the second
    /// element should come from `serialize_typed_connector_payload`.
    #[test]
    fn lint_build_error_response_serializes_typed_payload() {
        let mut violations: Vec<String> = Vec::new();

        for dir in connector_dirs() {
            for file in collect_rs_files(&dir) {
                let source = fs::read_to_string(&file).unwrap();

                if !source.contains("fn build_error_response") {
                    continue;
                }

                let bodies = extract_fn_bodies(&source, "build_error_response");

                for (line, body) in &bodies {
                    // Skip non-trait implementations (e.g. private helpers in transformers.rs
                    // that have different signatures)
                    if !body.contains("ErrorResponse") || !body.contains("ConnectorError") {
                        continue;
                    }

                    // Accept direct serialization or delegation to a helper
                    // like `build_custom_error_response` that itself serializes.
                    let has_serialize = body.contains("serialize_typed_connector_payload");
                    let has_delegation = body.contains("build_custom_error_response");

                    if !has_serialize && !has_delegation {
                        let rel = file
                            .strip_prefix(crate_src_root().parent().unwrap())
                            .unwrap_or(&file);
                        violations.push(format!(
                            "  {}:{} — build_error_response does not call serialize_typed_connector_payload",
                            rel.display(),
                            line
                        ));
                    }
                }
            }
        }

        if !violations.is_empty() {
            panic!(
                "\n\nTyped observability lint failure: build_error_response implementations \
                 must call `serialize_typed_connector_payload` on the parsed error struct.\n\
                 \nViolations:\n{}\n",
                violations.join("\n")
            );
        }
    }

    /// Check: manual `get_error_response_v2` implementations must either
    /// delegate to `build_error_response` or call `serialize_typed_connector_payload`.
    ///
    /// The macro-generated version delegates to `self.build_error_response(...)`.
    #[test]
    fn lint_get_error_response_v2_produces_typed_value() {
        let macros_file = crate_src_root().join("connectors").join("macros.rs");
        let mut violations: Vec<String> = Vec::new();

        for dir in connector_dirs() {
            for file in collect_rs_files(&dir) {
                if file == macros_file {
                    continue;
                }
                let source = fs::read_to_string(&file).unwrap();

                if !source.contains("fn get_error_response_v2") {
                    continue;
                }

                let bodies = extract_fn_bodies(&source, "get_error_response_v2");

                for (line, body) in &bodies {
                    // Accept delegation to build_error_response or helper methods
                    // like get_order_error_response that themselves serialize.
                    let has_delegation = body.contains("build_error_response")
                        || body.contains("get_order_error_response")
                        || body.contains("build_custom_error_response");
                    let has_serialize = body.contains("serialize_typed_connector_payload");

                    if !has_delegation && !has_serialize {
                        let rel = file
                            .strip_prefix(crate_src_root().parent().unwrap())
                            .unwrap_or(&file);
                        violations.push(format!(
                            "  {}:{} — get_error_response_v2 neither delegates to build_error_response \
                             nor calls serialize_typed_connector_payload",
                            rel.display(),
                            line
                        ));
                    }
                }
            }
        }

        if !violations.is_empty() {
            panic!(
                "\n\nTyped observability lint failure: get_error_response_v2 implementations \
                 must either delegate to `build_error_response` or call \
                 `serialize_typed_connector_payload`.\n\
                 \nViolations:\n{}\n",
                violations.join("\n")
            );
        }
    }
}
