/*
 * Copyright 2024 Juspay
 *
 * Licensed under the Apache License, version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package org.killbill.billing.plugin.hyperswitch.dao;

import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import javax.annotation.Nullable;
import javax.sql.DataSource;

import org.joda.time.DateTime;
import org.jooq.DSLContext;
import org.jooq.impl.DSL;
import org.killbill.billing.catalog.api.Currency;
import org.killbill.billing.payment.api.TransactionType;
import org.killbill.billing.plugin.dao.payment.PluginPaymentDao;

import com.fasterxml.jackson.annotation.JsonInclude.Include;

// Generated by jOOQ codegen (mvn -Pgenerate-jooq) against ddl.sql; committed under dao/gen.
import org.killbill.billing.plugin.hyperswitch.dao.gen.tables.HyperswitchPaymentMethods;
import org.killbill.billing.plugin.hyperswitch.dao.gen.tables.HyperswitchResponses;
import org.killbill.billing.plugin.hyperswitch.dao.gen.tables.records.HyperswitchPaymentMethodsRecord;
import org.killbill.billing.plugin.hyperswitch.dao.gen.tables.records.HyperswitchResponsesRecord;

import static org.killbill.billing.plugin.hyperswitch.dao.gen.tables.HyperswitchPaymentMethods.HYPERSWITCH_PAYMENT_METHODS;
import static org.killbill.billing.plugin.hyperswitch.dao.gen.tables.HyperswitchResponses.HYPERSWITCH_RESPONSES;

public class HyperswitchDao extends PluginPaymentDao<HyperswitchResponsesRecord, HyperswitchResponses, HyperswitchPaymentMethodsRecord, HyperswitchPaymentMethods> {

    // KillBill stores boolean smallint columns as the ASCII codes of '1'/'0' (49/48), via PluginDao.TRUE/FALSE
    // (protected byte). Public copy so the model/api classes (other packages) can compare is_default correctly.
    public static final short DB_TRUE = (short) '1';

    public HyperswitchDao(final DataSource dataSource) throws SQLException {
        super(HYPERSWITCH_RESPONSES, HYPERSWITCH_PAYMENT_METHODS, dataSource);
        objectMapper.setSerializationInclusion(Include.NON_EMPTY);
    }

    // ------------------------------------------------------------------ Responses

    /**
     * Persist one transaction attempt. {@code hyperswitchId} is Prism's {@code connectorTransactionId};
     * {@code additionalDataMap} carries the mapped plugin status, raw prism status, mandate/token/refund ids,
     * gateway error and the raw response snapshot.
     */
    public HyperswitchResponsesRecord addResponse(final UUID kbAccountId,
                                                  final UUID kbPaymentId,
                                                  final UUID kbPaymentTransactionId,
                                                  final TransactionType transactionType,
                                                  final BigDecimal amount,
                                                  @Nullable final Currency currency,
                                                  @Nullable final String hyperswitchId,
                                                  final Map<String, Object> additionalDataMap,
                                                  final DateTime utcNow,
                                                  final UUID kbTenantId) throws SQLException {
        return execute(dataSource.getConnection(),
                       conn -> DSL.using(conn, dialect, settings).transactionResult(configuration -> {
                           final DSLContext dslContext = DSL.using(configuration);
                           dslContext.insertInto(HYPERSWITCH_RESPONSES,
                                                 HYPERSWITCH_RESPONSES.KB_ACCOUNT_ID,
                                                 HYPERSWITCH_RESPONSES.KB_PAYMENT_ID,
                                                 HYPERSWITCH_RESPONSES.KB_PAYMENT_TRANSACTION_ID,
                                                 HYPERSWITCH_RESPONSES.TRANSACTION_TYPE,
                                                 HYPERSWITCH_RESPONSES.AMOUNT,
                                                 HYPERSWITCH_RESPONSES.CURRENCY,
                                                 HYPERSWITCH_RESPONSES.HYPERSWITCH_ID,
                                                 HYPERSWITCH_RESPONSES.ADDITIONAL_DATA,
                                                 HYPERSWITCH_RESPONSES.CREATED_DATE,
                                                 HYPERSWITCH_RESPONSES.KB_TENANT_ID)
                                     .values(kbAccountId.toString(),
                                             kbPaymentId.toString(),
                                             kbPaymentTransactionId.toString(),
                                             transactionType.toString(),
                                             amount,
                                             currency == null ? null : currency.name(),
                                             hyperswitchId,
                                             asString(additionalDataMap),
                                             toLocalDateTime(utcNow),
                                             kbTenantId.toString())
                                     .execute();
                           return dslContext.fetchOne(HYPERSWITCH_RESPONSES,
                                                      HYPERSWITCH_RESPONSES.RECORD_ID.eq(
                                                              HYPERSWITCH_RESPONSES.RECORD_ID.getDataType().convert(dslContext.lastID())));
                       }));
    }

    /** Merge extra key/values into an existing response's additional_data (e.g. after a PSync). */
    public void updateResponseAdditionalData(final HyperswitchResponsesRecord record,
                                             final Map<String, Object> extra) throws SQLException {
        final Map<String, Object> merged = new HashMap<>(fromAdditionalData(record.getAdditionalData()));
        merged.putAll(extra);
        execute(dataSource.getConnection(),
                (WithConnectionCallback<Void>) conn -> {
                    DSL.using(conn, dialect, settings)
                       .update(HYPERSWITCH_RESPONSES)
                       .set(HYPERSWITCH_RESPONSES.ADDITIONAL_DATA, asString(merged))
                       .where(HYPERSWITCH_RESPONSES.RECORD_ID.equal(record.getRecordId()))
                       .execute();
                    return null;
                });
    }

    @Override
    public HyperswitchResponsesRecord getSuccessfulAuthorizationResponse(final UUID kbPaymentId, final UUID kbTenantId) throws SQLException {
        return execute(dataSource.getConnection(),
                       (WithConnectionCallback<HyperswitchResponsesRecord>) conn ->
                               DSL.using(conn, dialect, settings)
                                  .selectFrom(HYPERSWITCH_RESPONSES)
                                  .where(HYPERSWITCH_RESPONSES.KB_PAYMENT_ID.equal(kbPaymentId.toString()))
                                  .and(HYPERSWITCH_RESPONSES.TRANSACTION_TYPE.equal(TransactionType.AUTHORIZE.toString())
                                               .or(HYPERSWITCH_RESPONSES.TRANSACTION_TYPE.equal(TransactionType.PURCHASE.toString())))
                                  .and(HYPERSWITCH_RESPONSES.KB_TENANT_ID.equal(kbTenantId.toString()))
                                  .orderBy(HYPERSWITCH_RESPONSES.RECORD_ID.desc())
                                  .limit(1)
                                  .fetchOne());
    }

    // ------------------------------------------------------------------ Payment methods

    public void addPaymentMethod(final UUID kbAccountId,
                                 final UUID kbPaymentMethodId,
                                 @Nullable final String hyperswitchId,
                                 final boolean isDefault,
                                 final Map<String, Object> additionalDataMap,
                                 final DateTime utcNow,
                                 final UUID kbTenantId) throws SQLException {
        execute(dataSource.getConnection(),
                (WithConnectionCallback<Void>) conn -> {
                    DSL.using(conn, dialect, settings)
                       .insertInto(HYPERSWITCH_PAYMENT_METHODS,
                                   HYPERSWITCH_PAYMENT_METHODS.KB_ACCOUNT_ID,
                                   HYPERSWITCH_PAYMENT_METHODS.KB_PAYMENT_METHOD_ID,
                                   HYPERSWITCH_PAYMENT_METHODS.HYPERSWITCH_ID,
                                   HYPERSWITCH_PAYMENT_METHODS.IS_DEFAULT,
                                   HYPERSWITCH_PAYMENT_METHODS.IS_DELETED,
                                   HYPERSWITCH_PAYMENT_METHODS.ADDITIONAL_DATA,
                                   HYPERSWITCH_PAYMENT_METHODS.CREATED_DATE,
                                   HYPERSWITCH_PAYMENT_METHODS.UPDATED_DATE,
                                   HYPERSWITCH_PAYMENT_METHODS.KB_TENANT_ID)
                       .values(kbAccountId.toString(),
                               kbPaymentMethodId.toString(),
                               hyperswitchId,
                               (short) (isDefault ? TRUE : FALSE),
                               (short) FALSE,
                               asString(additionalDataMap),
                               toLocalDateTime(utcNow),
                               toLocalDateTime(utcNow),
                               kbTenantId.toString())
                       .execute();
                    return null;
                });
    }

    // getResponses(kbPaymentId, kbTenantId) and getPaymentMethod(kbPaymentMethodId, kbTenantId) are inherited
    // from PluginPaymentDao — do not redeclare them.

    /** Find the most recent response row for a given Prism connector_transaction_id (webhook correlation). */
    public HyperswitchResponsesRecord findResponseByHyperswitchId(final String hyperswitchId, final UUID kbTenantId) throws SQLException {
        return execute(dataSource.getConnection(),
                       (WithConnectionCallback<HyperswitchResponsesRecord>) conn ->
                               DSL.using(conn, dialect, settings)
                                  .selectFrom(HYPERSWITCH_RESPONSES)
                                  .where(HYPERSWITCH_RESPONSES.HYPERSWITCH_ID.equal(hyperswitchId))
                                  .and(HYPERSWITCH_RESPONSES.KB_TENANT_ID.equal(kbTenantId.toString()))
                                  .orderBy(HYPERSWITCH_RESPONSES.RECORD_ID.desc())
                                  .limit(1)
                                  .fetchOne());
    }

    public static Map fromAdditionalData(@Nullable final String additionalData) {
        if (additionalData == null) {
            return Collections.emptyMap();
        }
        try {
            return objectMapper.readValue(additionalData, Map.class);
        } catch (final IOException e) {
            throw new RuntimeException(e);
        }
    }
}
