"""
Pydantic models for the documentation generator.

These models define the data structures for:
- Behavioral specifications (scenarios, status rules)
- Flow graph structures (nodes, edges, field dependencies)
- Hydrated scenarios (probe data + behavioral spec combined)
"""

from pydantic import BaseModel, Field, field_validator, ConfigDict
from typing import Optional, Any, List, Dict
from enum import Enum


# ── Behavioral Spec (from scenarios.yaml) ─────────────────────────────────────

class StatusAction(str, Enum):
    """What to do when a status matches."""
    ERROR = "error"
    RETURN_EARLY = "return_early"
    CONTINUE = "continue"  # Proceed to next flow (for polling scenarios)


class StatusRule(BaseModel):
    """
    One behavioral rule for response handling.
    
    This is the core consistency mechanism. All 4 languages receive
    the same StatusRule and must implement it — they differ only in
    syntax, not in which statuses are checked or what action is taken.
    """
    status: List[str]  # ["FAILED", "AUTHORIZATION_FAILED"]
    action: StatusAction  # error | return_early
    message: Optional[str] = None  # "Payment failed: {error}"
    return_fields: Optional[Dict[str, str]] = None  # For return_early: field map


class FlowDefinition(BaseModel):
    """One flow within a scenario (from scenarios.yaml)."""
    name: str
    pm_type: Optional[str] = None
    pm_type_variants: Optional[List[str]] = None  # Try each, use first supported
    required: bool = True
    capture_method: Optional[str] = None  # "AUTOMATIC" or "MANUAL"
    depends_on: Optional[str] = None
    use_from_previous: List[str] = Field(default_factory=list)
    status_handling: List[StatusRule] = Field(default_factory=list)
    
    model_config = ConfigDict(validate_assignment=True)


class Scenario(BaseModel):
    """Abstract scenario — no connector-specific data."""
    key: str
    name: str
    description: str
    flows: List[FlowDefinition]
    return_fields: Dict[str, str] = Field(default_factory=dict)
    
    @property
    def required_flows(self) -> List[str]:
        """Derive required flows from flow definitions."""
        return [f.name for f in self.flows if f.required]


# ── Flow Graph (from field-probe, per connector) ─────────────────────────────

class FlowNodeType(str, Enum):
    """Node type classification in the flow graph."""
    PREREQUISITE = "prerequisite"   # create_access_token, create_customer, create_order
    ENTRY_POINT = "entry_point"     # authorize, setup_recurring, tokenize
    DEPENDENT = "dependent"         # capture, refund, void, get, recurring_charge


class FieldProvider(BaseModel):
    """A field that a flow provides in its response."""
    response_path: str  # "connector_transaction_id" or "mandate_reference.connector_mandate_id.connector_mandate_id"
    description: str    # "Stripe PaymentIntent ID (pi_xxx)"


class FieldRequirement(BaseModel):
    """A field that a flow requires from a prior flow's response."""
    from_flow: str      # "authorize"
    from_field: str     # Key in the source flow's "provides"
    request_path: str   # Path in this flow's request where the value goes


class FlowNode(BaseModel):
    """One flow in the connector's flow graph."""
    node_type: FlowNodeType  # Matches Rust field name
    description: str = ""
    provides: Dict[str, FieldProvider] = Field(default_factory=dict)
    requires: Dict[str, FieldRequirement] = Field(default_factory=dict)


class FlowEdge(BaseModel):
    """Directed edge: from_flow must complete before to_flow can run."""
    from_: str = Field(alias="from")      # "authorize"
    to: str        # "capture"
    
    model_config = ConfigDict(populate_by_name=True)


class FlowGraph(BaseModel):
    """
    Connector-specific flow dependency graph.
    
    Generated by field-probe. Captures:
    - Which flows exist and their type (prerequisite, entry_point, dependent)
    - What each flow provides (response fields usable by downstream flows)
    - What each flow requires (fields from upstream flows)
    - Edges defining valid ordering
    
    This is the single source of truth for multi-step flow linking.
    It replaces the 5 hardcoded _DYNAMIC_FIELDS dicts and the
    dependency knowledge scattered across generator, test suite, and router.
    """
    nodes: Dict[str, FlowNode]     # flow_key -> FlowNode
    edges: List[FlowEdge]


# ── Field Link (resolved at hydration time from flow_graph) ───────────────────

class FieldLink(BaseModel):
    """
    Resolved field dependency for a specific flow in a hydrated scenario.
    
    Created by the hydrator from the flow_graph's requires/provides.
    The renderer uses this to generate cross-flow variable references
    in language-specific syntax.
    """
    from_flow: str      # "authorize"
    from_field: str     # "connector_transaction_id"
    target_path: str    # Path in the request payload to substitute


# ── Hydrated Models (probe data + behavioral spec + flow graph resolved) ──────

class FlowAvailability(str, Enum):
    """Availability states for a hydrated scenario."""
    SUPPORTED = "supported"
    PARTIALLY_SUPPORTED = "partially_supported"


class HydratedFlow(BaseModel):
    """Flow with actual payload from probe + behavioral spec + resolved field links."""
    name: str
    payload: Dict[str, Any]                    # From probe (pure data, no markers)
    status_handling: List[StatusRule]           # From scenario spec
    field_links: Dict[str, FieldLink] = Field(default_factory=dict)  # From flow_graph
    depends_on: Optional[str] = None
    use_from_previous: List[str] = Field(default_factory=list)
    capture_method: Optional[str] = None
    is_prerequisite: bool = False              # True for auto-discovered prereq flows


class HydratedScenario(BaseModel):
    """Scenario ready for rendering — probe data + behavioral spec + flow graph combined."""
    key: str
    name: str
    description: str
    connector_name: str
    prerequisite_flows: List[HydratedFlow] = Field(default_factory=list)  # From flow_graph
    flows: List[HydratedFlow]
    return_fields: Dict[str, str]              # From scenario spec
    availability: FlowAvailability = FlowAvailability.SUPPORTED
    skipped_optional: List[str] = Field(default_factory=list)


# ── Render Manifest (for structural validation) ───────────────────────────────

class RenderManifest(BaseModel):
    """What a renderer claims it produced — checked post-render."""
    scenario_key: str
    language: str
    flow_count: int
    status_checks: Dict[str, int]  # flow_name -> number of status checks
    return_field_count: int
    cross_flow_refs: List[str]     # ["capture.connector_transaction_id"]
    prerequisite_count: int = 0
